Allocator API
Functions for memory allocation.
Functions
void * uvrpc_alloc (size_t size)
Allocate memory.
void uvrpc_allocator_cleanup (void)
Cleanup allocator resources.
const char * uvrpc_allocator_get_name (void)
Get current allocator name.
uvrpc_allocator_type_t uvrpc_allocator_get_type (void)
Get current allocator type.
void uvrpc_allocator_init (uvrpc_allocator_type_t type, const uvrpc_custom_allocator_t *custom)
Initialize allocator (runtime selection)
void * uvrpc_calloc (size_t count, size_t size)
Allocate zero-initialized memory.
void uvrpc_free (void *ptr)
Free memory.
void * uvrpc_realloc (void *ptr, size_t size)
Reallocate memory.
char * uvrpc_strdup (const char *s)
Duplicate a string.
Detailed Description
Functions for memory allocation.
Function Documentation
uvrpc_alloc()
void * uvrpc_alloc (size_t size)
Allocate memory.
Parameters
size Size to allocate
Returns
Pointer to allocated memory, or NULL on failure
Definition at line 116 of file uvrpc_allocator.c.
                               {
    switch (g_allocator_type) {
        case UVRPC_ALLOCATOR_SYSTEM:
            return system_alloc(size);
        case UVRPC_ALLOCATOR_MIMALLOC:
#if UVRPC_DEFAULT_ALLOCATOR == UVRPC_ALLOCATOR_MIMALLOC
            return mimalloc_alloc(size);
#else
            fprintf(stderr, "Error: Mimalloc not compiled in\n");
            return system_alloc(size);
#endif
        case UVRPC_ALLOCATOR_CUSTOM:
            return g_custom_allocator.alloc ? g_custom_allocator.alloc(size) : system_alloc(size);
        default:
            return system_alloc(size);
    }
}
References uvrpc_custom_allocator_t::alloc, g_allocator_type, g_custom_allocator, mimalloc_alloc(), system_alloc(), UVRPC_ALLOCATOR_CUSTOM, UVRPC_ALLOCATOR_MIMALLOC, and UVRPC_ALLOCATOR_SYSTEM.
Referenced by async_response_callback(), client_recv_callback(), concurrent_callback(), create_inproc_transport(), create_ipc_transport(), create_tcp_transport(), create_udp_transport(), inproc_connect(), inproc_listen(), inproc_send_to_all(), ipc_connect(), ipc_listen(), ipc_send(), ipc_send_to(), on_client_alloc(), on_client_read(), on_server_alloc(), on_server_connection(), on_server_recv(), parse_ipc_address(), parse_tcp_address(), parse_udp_address(), subscriber_recv_callback(), tcp_connect(), tcp_listen(), tcp_send(), tcp_send_to(), udp_connect(), udp_listen(), udp_send(), udp_send_to(), uvbus_client_new(), uvbus_config_new(), uvbus_server_new(), uvrpc_async_all(), uvrpc_async_ctx_new(), uvrpc_async_retry(), uvrpc_async_retry_with_backoff(), uvrpc_encode_error(), uvrpc_publisher_publish(), and uvrpc_strdup().
uvrpc_allocator_cleanup()
void uvrpc_allocator_cleanup (void)
Cleanup allocator resources.
Definition at line 90 of file uvrpc_allocator.c.
                                   {
    /* Reset to default allocator */
    g_allocator_type = UVRPC_DEFAULT_ALLOCATOR;
    memset(&g_custom_allocator, 0, sizeof(g_custom_allocator));
}
References g_allocator_type, and g_custom_allocator.
uvrpc_allocator_get_name()
const char * uvrpc_allocator_get_name (void)
Get current allocator name.
Returns
Allocator name string
Definition at line 102 of file uvrpc_allocator.c.
                                           {
    switch (g_allocator_type) {
        case UVRPC_ALLOCATOR_SYSTEM:
            return "system";
        case UVRPC_ALLOCATOR_MIMALLOC:
            return "mimalloc";
        case UVRPC_ALLOCATOR_CUSTOM:
            return g_custom_allocator.name ? g_custom_allocator.name : "custom";
        default:
            return "unknown";
    }
}
References g_allocator_type, g_custom_allocator, uvrpc_custom_allocator_t::name, UVRPC_ALLOCATOR_CUSTOM, UVRPC_ALLOCATOR_MIMALLOC, and UVRPC_ALLOCATOR_SYSTEM.
uvrpc_allocator_get_type()
uvrpc_allocator_type_t uvrpc_allocator_get_type (void)
Get current allocator type.
Returns
Current allocator type
Definition at line 97 of file uvrpc_allocator.c.
                                                      {
    return g_allocator_type;
}
References g_allocator_type.
uvrpc_allocator_init()
void uvrpc_allocator_init (uvrpc_allocator_type_t type, const uvrpc_custom_allocator_t * custom)
Initialize allocator (runtime selection)
Parameters
type Allocator type
custom Custom allocator (required if type is CUSTOM)
Definition at line 76 of file uvrpc_allocator.c.
                                                                                               {
    g_allocator_type = type;
    if (type == UVRPC_ALLOCATOR_CUSTOM && custom) {
        if (custom->alloc && custom->calloc && custom->realloc && custom->free) {
            g_custom_allocator = *custom;
        } else {
            fprintf(stderr, "Warning: Invalid custom allocator, falling back to system\n");
            g_allocator_type = UVRPC_ALLOCATOR_SYSTEM;
        }
    }
}
References uvrpc_custom_allocator_t::alloc, uvrpc_custom_allocator_t::calloc, uvrpc_custom_allocator_t::free, g_allocator_type, g_custom_allocator, uvrpc_custom_allocator_t::realloc, UVRPC_ALLOCATOR_CUSTOM, and UVRPC_ALLOCATOR_SYSTEM.
uvrpc_calloc()
void * uvrpc_calloc (size_t count, size_t size)
Allocate zero-initialized memory.
Parameters
count Number of elements
size Size of each element
Returns
Pointer to allocated memory, or NULL on failure
Definition at line 134 of file uvrpc_allocator.c.
                                              {
    switch (g_allocator_type) {
        case UVRPC_ALLOCATOR_SYSTEM:
            return system_calloc(count, size);
        case UVRPC_ALLOCATOR_MIMALLOC:
#if UVRPC_DEFAULT_ALLOCATOR == UVRPC_ALLOCATOR_MIMALLOC
            return mimalloc_calloc(count, size);
#else
            fprintf(stderr, "Error: Mimalloc not compiled in\n");
            return system_calloc(count, size);
#endif
        case UVRPC_ALLOCATOR_CUSTOM:
            return g_custom_allocator.calloc ? g_custom_allocator.calloc(count, size) : system_calloc(count, size);
        default:
            return system_calloc(count, size);
    }
}
References uvrpc_custom_allocator_t::calloc, g_allocator_type, g_custom_allocator, mimalloc_calloc(), system_calloc(), UVRPC_ALLOCATOR_CUSTOM, UVRPC_ALLOCATOR_MIMALLOC, and UVRPC_ALLOCATOR_SYSTEM.
Referenced by uvrpc_client_call_batch(), uvrpc_client_call_no_retry_internal(), uvrpc_client_create(), uvrpc_config_new(), uvrpc_context_new(), uvrpc_idmap_ctx_new(), uvrpc_idmap_to_gateway(), uvrpc_msgid_ctx_new(), uvrpc_publisher_create(), uvrpc_server_create(), uvrpc_server_register(), uvrpc_subscriber_create(), and uvrpc_subscriber_subscribe().
uvrpc_free()
void uvrpc_free (void * ptr)
Free memory.
Parameters
ptr Pointer to free
Definition at line 170 of file uvrpc_allocator.c.
                           {
    if (!ptr) return;
    switch (g_allocator_type) {
        case UVRPC_ALLOCATOR_SYSTEM:
            system_free(ptr);
            break;
        case UVRPC_ALLOCATOR_MIMALLOC:
#if UVRPC_DEFAULT_ALLOCATOR == UVRPC_ALLOCATOR_MIMALLOC
            mimalloc_free(ptr);
#else
            fprintf(stderr, "Error: Mimalloc not compiled in\n");
            system_free(ptr);
#endif
            break;
        case UVRPC_ALLOCATOR_CUSTOM:
            if (g_custom_allocator.free) {
                g_custom_allocator.free(ptr);
            } else {
                system_free(ptr);
            }
            break;
        default:
            system_free(ptr);
            break;
    }
}
References uvrpc_custom_allocator_t::free, g_allocator_type, g_custom_allocator, mimalloc_free(), system_free(), UVRPC_ALLOCATOR_CUSTOM, UVRPC_ALLOCATOR_MIMALLOC, and UVRPC_ALLOCATOR_SYSTEM.
Referenced by __ac_hash_resize(), client_recv_callback(), inproc_disconnect(), inproc_free(), inproc_send_to_all(), ipc_connect(), ipc_disconnect(), ipc_free(), ipc_listen(), ipc_send(), ipc_send_to(), on_client_close(), on_client_read(), on_client_recv(), on_send(), on_server_close(), on_server_connection(), on_server_recv(), on_write(), retry_delay_callback(), server_recv_callback(), subscriber_recv_callback(), tcp_connect(), tcp_disconnect(), tcp_free(), tcp_listen(), tcp_send(), tcp_send_to(), udp_connect(), udp_disconnect(), udp_free(), udp_listen(), udp_send(), udp_send_to(), uvbus_client_new(), uvbus_config_free(), uvbus_free(), uvbus_server_new(), uvrpc_async_ctx_free(), uvrpc_async_result_free(), uvrpc_async_retry(), uvrpc_async_retry_with_backoff(), uvrpc_client_call_batch(), uvrpc_client_call_no_retry_internal(), uvrpc_client_create(), uvrpc_client_free(), uvrpc_config_free(), uvrpc_config_set_address(), uvrpc_context_free(), uvrpc_encode_error(), uvrpc_free_decoded(), uvrpc_idmap_ctx_free(), uvrpc_idmap_remove(), uvrpc_msgid_ctx_free(), uvrpc_publisher_create(), uvrpc_publisher_free(), uvrpc_publisher_publish(), uvrpc_request_send_response(), uvrpc_response_send(), uvrpc_response_send_error(), uvrpc_server_create(), uvrpc_server_free(), uvrpc_server_register(), uvrpc_subscriber_create(), uvrpc_subscriber_free(), uvrpc_subscriber_subscribe(), uvrpc_subscriber_unsubscribe(), and write_callback().
uvrpc_realloc()
void * uvrpc_realloc (void * ptr, size_t size)
Reallocate memory.
Parameters
ptr Pointer to reallocate
size New size
Returns
Pointer to reallocated memory, or NULL on failure
Definition at line 152 of file uvrpc_allocator.c.
                                            {
    switch (g_allocator_type) {
        case UVRPC_ALLOCATOR_SYSTEM:
            return system_realloc(ptr, size);
        case UVRPC_ALLOCATOR_MIMALLOC:
#if UVRPC_DEFAULT_ALLOCATOR == UVRPC_ALLOCATOR_MIMALLOC
            return mimalloc_realloc(ptr, size);
#else
            fprintf(stderr, "Error: Mimalloc not compiled in\n");
            return system_realloc(ptr, size);
#endif
        case UVRPC_ALLOCATOR_CUSTOM:
            return g_custom_allocator.realloc ? g_custom_allocator.realloc(ptr, size) : system_realloc(ptr, size);
        default:
            return system_realloc(ptr, size);
    }
}
References g_allocator_type, g_custom_allocator, mimalloc_realloc(), uvrpc_custom_allocator_t::realloc, system_realloc(), UVRPC_ALLOCATOR_CUSTOM, UVRPC_ALLOCATOR_MIMALLOC, and UVRPC_ALLOCATOR_SYSTEM.
Referenced by inproc_add_client(), and on_server_connection().
uvrpc_strdup()
char * uvrpc_strdup (const char * s)
Duplicate a string.
Parameters
s String to duplicate
Returns
Newly allocated string, or NULL on failure
Definition at line 199 of file uvrpc_allocator.c.
                                  {
    if (!s) return NULL;
    size_t len = strlen(s) + 1;
    char* copy = (char*)uvrpc_alloc(len);
    if (copy) {
        memcpy(copy, s, len);
    }
    return copy;
}
References uvrpc_alloc().
Referenced by inproc_listen(), server_recv_callback(), uvbus_client_new(), uvbus_server_new(), uvrpc_async_retry(), uvrpc_async_retry_with_backoff(), uvrpc_client_create(), uvrpc_config_set_address(), uvrpc_decode_error(), uvrpc_decode_request(), uvrpc_publisher_create(), uvrpc_server_create(), uvrpc_server_register(), uvrpc_subscriber_create(), and uvrpc_subscriber_subscribe().