Configuration API
Functions for creating and configuring UVRPC instances.
Functions
void uvrpc_config_free (uvrpc_config_t *config)
Free a configuration structure.
uvrpc_config_t * uvrpc_config_new (void)
Create a new configuration structure.
uvrpc_config_t * uvrpc_config_set_address (uvrpc_config_t *config, const char *address)
Set the address.
uvrpc_config_t * uvrpc_config_set_comm_type (uvrpc_config_t *config, uvrpc_comm_type_t comm_type)
Set the communication type.
uvrpc_config_t * uvrpc_config_set_loop (uvrpc_config_t *config, uv_loop_t *loop)
Set the event loop.
uvrpc_config_t * uvrpc_config_set_max_concurrent (uvrpc_config_t *config, int max_concurrent)
Set the maximum concurrent requests.
uvrpc_config_t * uvrpc_config_set_max_pending_callbacks (uvrpc_config_t *config, int max_pending)
Set the maximum pending callbacks.
uvrpc_config_t * uvrpc_config_set_msgid_offset (uvrpc_config_t *config, uint32_t msgid_offset)
Set the message ID offset.
uvrpc_config_t * uvrpc_config_set_performance_mode (uvrpc_config_t *config, uvrpc_perf_mode_t mode)
Set the performance mode.
uvrpc_config_t * uvrpc_config_set_pool_size (uvrpc_config_t *config, int pool_size)
Set the connection pool size.
uvrpc_config_t * uvrpc_config_set_timeout (uvrpc_config_t *config, uint64_t timeout_ms)
Set the default timeout.
uvrpc_config_t * uvrpc_config_set_transport (uvrpc_config_t *config, uvrpc_transport_type transport)
Set the transport type.
Detailed Description
Functions for creating and configuring UVRPC instances.
IMPORTANT: Request/Response Data Lifetime
Server Request (uvrpc_request_t):
req->method and req->params point to frame data and are ONLY VALID during the handler callback
Do NOT store these pointers for later use - they will be freed after the callback returns
If you need to use the data later, make a copy using uvrpc_strdup() for method or uvrpc_alloc() + memcpy() for params
req->client_stream can be used to send responses during the callback
Client Response (uvrpc_response_t):
resp->result points to copied data that is valid until the callback returns
The framework automatically frees resp->result after the callback
Do NOT store resp->result for later use - make a copy if needed
Use uvrpc_response_free() only if you allocated the response structure yourself (rare)
Function Documentation
uvrpc_config_free()
void uvrpc_config_free (uvrpc_config_t * config)
Free a configuration structure.
Parameters
config Configuration to free
Definition at line 35 of file uvrpc_config.c.
                                               {
    if (!config) return;
    if (config->address) {
        uvrpc_free(config->address);
    }
    uvrpc_free(config);
}
References uvrpc_config::address, and uvrpc_free().
uvrpc_config_new()
uvrpc_config_t * uvrpc_config_new (void)
Create a new configuration structure.
Creates a configuration structure with default values.
Returns
New configuration instance, or NULL on failure
Definition at line 18 of file uvrpc_config.c.
                                       {
    uvrpc_config_t* config = (uvrpc_config_t*)uvrpc_calloc(1, sizeof(uvrpc_config_t));
    if (!config) return NULL;
    config->loop = NULL;
    config->address = NULL;
    config->transport = UVRPC_TRANSPORT_TCP; /* Default to TCP */
    config->performance_mode = UVRPC_PERF_LOW_LATENCY; /* Default to low latency */
    config->pool_size = UVRPC_DEFAULT_POOL_SIZE;
    config->max_concurrent = UVRPC_MAX_CONCURRENT_REQUESTS;
    config->max_pending_callbacks = UVRPC_MAX_PENDING_CALLBACKS;
    config->timeout_ms = 0;
    config->msgid_offset = 0; /* Default: 0 = auto-assign */
    return config;
}
References uvrpc_config::address, uvrpc_config::loop, uvrpc_config::max_concurrent, uvrpc_config::max_pending_callbacks, uvrpc_config::msgid_offset, uvrpc_config::performance_mode, uvrpc_config::pool_size, uvrpc_config::timeout_ms, uvrpc_config::transport, uvrpc_calloc(), UVRPC_PERF_LOW_LATENCY, and UVRPC_TRANSPORT_TCP.
uvrpc_config_set_address()
uvrpc_config_t * uvrpc_config_set_address (uvrpc_config_t * config, const char * address)
Set the address.
Parameters
config Configuration structure
address Server or client address (e.g., `tcp://127.0.0.1:5555`)
Returns
Configuration structure for chaining
Definition at line 51 of file uvrpc_config.c.
                                                                                      {
    if (!config || !address) return NULL;
    if (config->address) {
        uvrpc_free(config->address);
    }
    config->address = uvrpc_strdup(address);
    if (!config->address) {
        return NULL;
    }
    /* Auto-detect transport type from address prefix */
    if (strncmp(address, "inproc://", 9) == 0) {
        config->transport = UVRPC_TRANSPORT_INPROC;
    } else if (strncmp(address, "ipc://", 6) == 0) {
        config->transport = UVRPC_TRANSPORT_IPC;
    } else if (strncmp(address, "tcp://", 6) == 0) {
        config->transport = UVRPC_TRANSPORT_TCP;
    } else if (strncmp(address, "udp://", 6) == 0) {
        config->transport = UVRPC_TRANSPORT_UDP;
    }
    /* For addresses without prefix, keep the current/transport default */
    return config;
}
References uvrpc_config::address, uvrpc_config::transport, uvrpc_free(), uvrpc_strdup(), UVRPC_TRANSPORT_INPROC, UVRPC_TRANSPORT_IPC, UVRPC_TRANSPORT_TCP, and UVRPC_TRANSPORT_UDP.
uvrpc_config_set_comm_type()
uvrpc_config_t * uvrpc_config_set_comm_type (uvrpc_config_t * config, uvrpc_comm_type_t comm_type)
Set the communication type.
Parameters
config Configuration structure
comm_type Communication type (SERVER_CLIENT or BROADCAST)
Returns
Configuration structure for chaining
Definition at line 84 of file uvrpc_config.c.
                                                                                                {
    if (!config) return NULL;
    config->comm_type = comm_type;
    return config;
}
References uvrpc_config::comm_type.
uvrpc_config_set_loop()
uvrpc_config_t * uvrpc_config_set_loop (uvrpc_config_t * config, uv_loop_t * loop)
Set the event loop.
Parameters
config Configuration structure
loop libuv event loop
Returns
Configuration structure for chaining
Definition at line 45 of file uvrpc_config.c.
                                                                               {
    if (!config) return NULL;
    config->loop = loop;
    return config;
}
References uvrpc_config::loop.
uvrpc_config_set_max_concurrent()
uvrpc_config_t * uvrpc_config_set_max_concurrent (uvrpc_config_t * config, int max_concurrent)
Set the maximum concurrent requests.
Parameters
config Configuration structure
max_concurrent Maximum concurrent requests
Returns
Configuration structure for chaining
Definition at line 102 of file uvrpc_config.c.
                                                                                            {
    if (!config) return NULL;
    config->max_concurrent = (max_concurrent > 0) ? max_concurrent : UVRPC_MAX_CONCURRENT_REQUESTS;
    return config;
}
References uvrpc_config::max_concurrent.
uvrpc_config_set_max_pending_callbacks()
uvrpc_config_t * uvrpc_config_set_max_pending_callbacks (uvrpc_config_t * config, int max_pending)
Set the maximum pending callbacks.
Parameters
config Configuration structure
max_pending Maximum pending callbacks (must be power of 2)
Returns
Configuration structure for chaining
Definition at line 108 of file uvrpc_config.c.
                                                                                                {
    if (!config) return NULL;
    /* Validate that max_pending is a power of 2 */
    if (max_pending > 0 && (max_pending & (max_pending - 1)) == 0) {
        config->max_pending_callbacks = max_pending;
    } else {
        /* Use default value if invalid */
        config->max_pending_callbacks = UVRPC_MAX_PENDING_CALLBACKS;
    }
    return config;
}
References uvrpc_config::max_pending_callbacks.
uvrpc_config_set_msgid_offset()
uvrpc_config_t * uvrpc_config_set_msgid_offset (uvrpc_config_t * config, uint32_t msgid_offset)
Set the message ID offset.
Parameters
config Configuration structure
msgid_offset Message ID offset for multi-instance isolation
Returns
Configuration structure for chaining
Definition at line 126 of file uvrpc_config.c.
                                                                                             {
    if (!config) return NULL;
    config->msgid_offset = msgid_offset;
    return config;
}
References uvrpc_config::msgid_offset.
uvrpc_config_set_performance_mode()
uvrpc_config_t * uvrpc_config_set_performance_mode (uvrpc_config_t * config, uvrpc_perf_mode_t mode)
Set the performance mode.
Parameters
config Configuration structure
mode Performance mode (LOW_LATENCY or HIGH_THROUGHPUT)
Returns
Configuration structure for chaining
Definition at line 90 of file uvrpc_config.c.
                                                                                                  {
    if (!config) return NULL;
    config->performance_mode = mode;
    return config;
}
References uvrpc_config::performance_mode.
uvrpc_config_set_pool_size()
uvrpc_config_t * uvrpc_config_set_pool_size (uvrpc_config_t * config, int pool_size)
Set the connection pool size.
Parameters
config Configuration structure
pool_size Number of connections in pool
Returns
Configuration structure for chaining
Definition at line 96 of file uvrpc_config.c.
                                                                                  {
    if (!config) return NULL;
    config->pool_size = (pool_size > 0) ? pool_size : UVRPC_DEFAULT_POOL_SIZE;
    return config;
}
References uvrpc_config::pool_size.
uvrpc_config_set_timeout()
uvrpc_config_t * uvrpc_config_set_timeout (uvrpc_config_t * config, uint64_t timeout_ms)
Set the default timeout.
Parameters
config Configuration structure
timeout_ms Timeout in milliseconds (0 for no timeout)
Returns
Configuration structure for chaining
Definition at line 120 of file uvrpc_config.c.
                                                                                      {
    if (!config) return NULL;
    config->timeout_ms = timeout_ms;
    return config;
}
References uvrpc_config::timeout_ms.
uvrpc_config_set_transport()
uvrpc_config_t * uvrpc_config_set_transport (uvrpc_config_t * config, uvrpc_transport_type transport)
Set the transport type.
Parameters
config Configuration structure
transport Transport type (TCP/UDP/IPC/INPROC)
Returns
Configuration structure for chaining
Definition at line 78 of file uvrpc_config.c.
                                                                                                   {
    if (!config) return NULL;
    config->transport = transport;
    return config;
}
References uvrpc_config::transport.