Server API
Functions for creating and managing UVRPC servers.
Functions
int uvrpc_response_send (uvrpc_request_t *req, const uint8_t *result, size_t result_size)
Send a response to a request.
int uvrpc_response_send_error (uvrpc_request_t *req, int32_t error_code, const char *error_message)
Send an error response to a request.
uvrpc_server_t * uvrpc_server_create (uvrpc_config_t *config)
Create a new RPC server.
void uvrpc_server_free (uvrpc_server_t *server)
Free the server.
uvrpc_context_t * uvrpc_server_get_context (uvrpc_server_t *server)
Get server context.
uint64_t uvrpc_server_get_total_requests (uvrpc_server_t *server)
Get total requests received.
uint64_t uvrpc_server_get_total_responses (uvrpc_server_t *server)
Get total responses sent.
int uvrpc_server_register (uvrpc_server_t *server, const char *method, uvrpc_handler_t handler, void *ctx)
Register a method handler.
void uvrpc_server_set_context (uvrpc_server_t *server, uvrpc_context_t *ctx)
Set server context.
int uvrpc_server_start (uvrpc_server_t *server)
Start the server.
void uvrpc_server_stop (uvrpc_server_t *server)
Stop the server.
Detailed Description
Functions for creating and managing UVRPC servers.
Function Documentation
uvrpc_response_send()
int uvrpc_response_send (uvrpc_request_t * req, const uint8_t * result, size_t result_size)
Send a response to a request.
Parameters
req Request object
result Response data
result_size Size of response data
Returns
UVRPC_OK on success, error code on failure
Definition at line 390 of file uvrpc_server.c.
                                                                                         {
    if (!req || !req->server || !req->client_ctx) {
        return UVRPC_ERROR_INVALID_PARAM;
    }
    /* Encode response */
    uint8_t* response_data;
    size_t response_size;
    if (uvrpc_encode_response(req->msgid, result, result_size,
                              &response_data, &response_size) != UVRPC_OK) {
        return UVRPC_ERROR_TRANSPORT;
    }
    /* Send response via UVBus */
    uvbus_t* uvbus = req->server->uvbus;
    uvbus_error_t err = uvbus_send_to(uvbus, response_data,
                                       response_size, req->client_ctx);
    uvrpc_free(response_data);
    if (err != UVBUS_OK) {
        return UVRPC_ERROR_TRANSPORT;
    }
    req->server->total_responses++;
    return UVRPC_OK;
}
References uvrpc_request::client_ctx, uvrpc_request::msgid, uvrpc_request::server, uvrpc_server::total_responses, uvrpc_server::uvbus, UVBUS_OK, uvbus_send_to(), uvrpc_encode_response(), UVRPC_ERROR_INVALID_PARAM, UVRPC_ERROR_TRANSPORT, uvrpc_free(), and UVRPC_OK.
uvrpc_response_send_error()
int uvrpc_response_send_error (uvrpc_request_t * req, int32_t error_code, const char * error_message)
Send an error response to a request.
Parameters
req Request object
error_code RPC error code
error_message Error message
Returns
UVRPC_OK on success, error code on failure
Definition at line 420 of file uvrpc_server.c.
                                                                                                   {
    if (!req || !req->server || !req->client_ctx) {
        return UVRPC_ERROR_INVALID_PARAM;
    }
    /* Encode error response */
    uint8_t* response_data;
    size_t response_size;
    if (uvrpc_encode_error(req->msgid, error_code, error_message,
                           &response_data, &response_size) != UVRPC_OK) {
        return UVRPC_ERROR_TRANSPORT;
    }
    /* Send response via UVBus */
    uvbus_t* uvbus = req->server->uvbus;
    uvbus_error_t err = uvbus_send_to(uvbus, response_data,
                                       response_size, req->client_ctx);
    uvrpc_free(response_data);
    if (err != UVBUS_OK) {
        return UVRPC_ERROR_TRANSPORT;
    }
    req->server->total_responses++;
    return UVRPC_OK;
}
References uvrpc_request::client_ctx, uvrpc_request::msgid, uvrpc_request::server, uvrpc_server::total_responses, uvrpc_server::uvbus, UVBUS_OK, uvbus_send_to(), uvrpc_encode_error(), UVRPC_ERROR_INVALID_PARAM, UVRPC_ERROR_TRANSPORT, uvrpc_free(), and UVRPC_OK.
uvrpc_server_create()
uvrpc_server_t * uvrpc_server_create (uvrpc_config_t * config)
Create a new RPC server.
Parameters
config Configuration structure
Returns
New server instance, or NULL on failure
Definition at line 154 of file uvrpc_server.c.
                                                            {
    if (!config || !config->loop || !config->address) return NULL;
    
    uvrpc_server_t* server = uvrpc_calloc(1, sizeof(uvrpc_server_t));
    if (!server) return NULL;
    server->loop = config->loop;
    server->address = uvrpc_strdup(config->address);
    if (!server->address) {
        uvrpc_free(server);
        return NULL;
    }
    server->handlers = NULL;
    server->is_running = 0;
    
    /* Initialize ring buffer */
    server->max_pending_requests = (config->max_pending_callbacks > 0) ?
                                   config->max_pending_callbacks : UVRPC_MAX_PENDING_CALLBACKS;
    server->generation = 0;
    
    /* Allocate ring buffer array */
    server->pending_requests = (pending_request_t**)uvrpc_calloc(
        server->max_pending_requests, sizeof(pending_request_t*));
    if (!server->pending_requests) {
        uvrpc_free(server->address);
        uvrpc_free(server);
        return NULL;
    }
    /* Create UVBus configuration */
    uvbus_config_t* bus_config = uvbus_config_new();
    if (!bus_config) {
        uvrpc_free(server->pending_requests);
        uvrpc_free(server->address);
        uvrpc_free(server);
        return NULL;
    }
    
    uvbus_config_set_loop(bus_config, config->loop);
    
    /* Map UVRPC transport type to UVBus transport type */
    uvbus_transport_type_t uvbus_type;
    switch (config->transport) {
        case UVRPC_TRANSPORT_TCP:
            uvbus_type = UVBUS_TRANSPORT_TCP;
            break;
        case UVRPC_TRANSPORT_UDP:
            uvbus_type = UVBUS_TRANSPORT_UDP;
            break;
        case UVRPC_TRANSPORT_IPC:
            uvbus_type = UVBUS_TRANSPORT_IPC;
            break;
        case UVRPC_TRANSPORT_INPROC:
            uvbus_type = UVBUS_TRANSPORT_INPROC;
            break;
        default:
            uvbus_config_free(bus_config);
            uvrpc_free(server->pending_requests);
            uvrpc_free(server->address);
            uvrpc_free(server);
            return NULL;
    }
    
    uvbus_config_set_transport(bus_config, uvbus_type);
    uvbus_config_set_address(bus_config, server->address);
    
    /* Set up receive callback */
    uvbus_config_set_recv_callback(bus_config, server_recv_callback, server);
    
    /* Create UVBus server */
    server->uvbus = uvbus_server_new(bus_config);
    if (!server->uvbus) {
        uvbus_config_free(bus_config);
        uvrpc_free(server->pending_requests);
        uvrpc_free(server->address);
        uvrpc_free(server);
        return NULL;
    }
    
    uvbus_config_free(bus_config);
    
    return server;
}
References uvrpc_config::address, uvrpc_server::address, uvrpc_server::generation, uvrpc_server::handlers, uvrpc_server::is_running, uvrpc_config::loop, uvrpc_server::loop, uvrpc_config::max_pending_callbacks, uvrpc_server::max_pending_requests, uvrpc_server::pending_requests, server_recv_callback(), uvrpc_config::transport, uvrpc_server::uvbus, uvbus_config_free(), uvbus_config_new(), uvbus_config_set_address(), uvbus_config_set_loop(), uvbus_config_set_recv_callback(), uvbus_config_set_transport(), uvbus_server_new(), UVBUS_TRANSPORT_INPROC, UVBUS_TRANSPORT_IPC, UVBUS_TRANSPORT_TCP, UVBUS_TRANSPORT_UDP, uvrpc_calloc(), uvrpc_free(), uvrpc_strdup(), UVRPC_TRANSPORT_INPROC, UVRPC_TRANSPORT_IPC, UVRPC_TRANSPORT_TCP, and UVRPC_TRANSPORT_UDP.
uvrpc_server_free()
void uvrpc_server_free (uvrpc_server_t * server)
Free the server.
Parameters
server Server instance
Definition at line 274 of file uvrpc_server.c.
                                               {
    if (!server) return;
    
    uvrpc_server_stop(server);
    
    /* Free UVBus */
    if (server->uvbus) {
        uvbus_free(server->uvbus);
    }
    
    /* Free handlers */
    handler_entry_t* entry, *tmp;
    HASH_ITER(hh, server->handlers, entry, tmp) {
        HASH_DEL(server->handlers, entry);
        uvrpc_free(entry->name);
        uvrpc_free(entry);
    }
    
    /* Free pending requests ring buffer */
    if (server->pending_requests) {
        for (int i = 0; i < server->max_pending_requests; i++) {
            if (server->pending_requests[i]) {
                uvrpc_free(server->pending_requests[i]);
            }
        }
        uvrpc_free(server->pending_requests);
    }
    uvrpc_free(server->address);
    uvrpc_free(server);
}
References uvrpc_server::address, uvrpc_server::handlers, uvrpc_server::max_pending_requests, handler_entry::name, uvrpc_server::pending_requests, uvrpc_server::uvbus, uvbus_free(), uvrpc_free(), and uvrpc_server_stop().
uvrpc_server_get_context()
uvrpc_context_t * uvrpc_server_get_context (uvrpc_server_t * server)
Get server context.
Parameters
server Server instance
Returns
Context instance
Definition at line 351 of file uvrpc_server.c.
                                                                  {
    return server ? server->ctx : NULL;
}
References uvrpc_server::ctx.
uvrpc_server_get_total_requests()
uint64_t uvrpc_server_get_total_requests (uvrpc_server_t * server)
Get total requests received.
Parameters
server Server instance
Returns
Total number of requests received
Definition at line 143 of file uvrpc_server.c.
                                                                 {
    if (!server) return 0;
    return server->total_requests;
}
References uvrpc_server::total_requests.
uvrpc_server_get_total_responses()
uint64_t uvrpc_server_get_total_responses (uvrpc_server_t * server)
Get total responses sent.
Parameters
server Server instance
Returns
Total number of responses sent
Definition at line 148 of file uvrpc_server.c.
                                                                  {
    if (!server) return 0;
    return server->total_responses;
}
References uvrpc_server::total_responses.
uvrpc_server_register()
int uvrpc_server_register (uvrpc_server_t * server, const char * method, uvrpc_handler_t handler, void * ctx)
Register a method handler.
Parameters
server Server instance
method Method name
handler Handler function
ctx User context passed to handler
Returns
UVRPC_OK on success, error code on failure
Definition at line 307 of file uvrpc_server.c.
                                                              {
    if (!server || !method || !handler) return UVRPC_ERROR_INVALID_PARAM;
    
    
    /* Check if handler already exists */
    handler_entry_t* entry = NULL;
    HASH_FIND_STR(server->handlers, method, entry);
    if (entry) {
        return UVRPC_ERROR; /* Handler already registered */
    }
    
    /* Create new entry */
    entry = uvrpc_calloc(1, sizeof(handler_entry_t));
    if (!entry) return UVRPC_ERROR_NO_MEMORY;
    /* Create lowercase copy for case-insensitive lookup */
    char* method_lower = uvrpc_strdup(method);
    if (!method_lower) {
        uvrpc_free(entry);
        return UVRPC_ERROR_NO_MEMORY;
    }
    
    for (char* p = method_lower; *p; p++) {
        *p = tolower((unsigned char)*p);
    }
    
    entry->name = method_lower; /* Store lowercase name in hash table */
    entry->handler = handler;
    entry->ctx = ctx;
    
    HASH_ADD_STR(server->handlers, name, entry);
    
    return UVRPC_OK;
}
References handler_entry::ctx, handler_entry::handler, uvrpc_server::handlers, handler_entry::name, uvrpc_calloc(), UVRPC_ERROR, UVRPC_ERROR_INVALID_PARAM, UVRPC_ERROR_NO_MEMORY, uvrpc_free(), UVRPC_OK, and uvrpc_strdup().
uvrpc_server_set_context()
void uvrpc_server_set_context (uvrpc_server_t * server, uvrpc_context_t * ctx)
Set server context.
Parameters
server Server instance
ctx Context to attach
Definition at line 344 of file uvrpc_server.c.
                                                                            {
    if (server) {
        server->ctx = ctx;
    }
}
References uvrpc_server::ctx.
uvrpc_server_start()
int uvrpc_server_start (uvrpc_server_t * server)
Start the server.
Parameters
server Server instance
Returns
UVRPC_OK on success, error code on failure
Definition at line 239 of file uvrpc_server.c.
                                               {
    if (!server || !server->uvbus) return UVRPC_ERROR_INVALID_PARAM;
    if (server->is_running) return UVRPC_OK;
    uvbus_error_t err = uvbus_listen(server->uvbus);
    if (err != UVBUS_OK) {
        /* Map UVBus errors to UVRPC errors */
        switch (err) {
            case UVBUS_ERROR_ALREADY_EXISTS:
                return UVRPC_ERROR_ALREADY_EXISTS;
            case UVBUS_ERROR_NO_MEMORY:
                return UVRPC_ERROR_NO_MEMORY;
            case UVBUS_ERROR_INVALID_PARAM:
                return UVRPC_ERROR_INVALID_PARAM;
            default:
                return UVRPC_ERROR_TRANSPORT;
        }
    }
    
    server->is_running = 1;
    
    printf("Server started on %s\n", server->address);
    
    return UVRPC_OK;
}
References uvrpc_server::address, uvrpc_server::is_running, uvrpc_server::uvbus, UVBUS_ERROR_ALREADY_EXISTS, UVBUS_ERROR_INVALID_PARAM, UVBUS_ERROR_NO_MEMORY, uvbus_listen(), UVBUS_OK, UVRPC_ERROR_ALREADY_EXISTS, UVRPC_ERROR_INVALID_PARAM, UVRPC_ERROR_NO_MEMORY, UVRPC_ERROR_TRANSPORT, and UVRPC_OK.
uvrpc_server_stop()
void uvrpc_server_stop (uvrpc_server_t * server)
Stop the server.
Stops accepting new connections but allows existing connections to complete.
Parameters
server Server instance
Definition at line 267 of file uvrpc_server.c.
                                               {
    if (!server) return;
    
    server->is_running = 0;
}
References uvrpc_server::is_running.
Referenced by uvrpc_server_free().