Broadcast API
Functions for publish-subscribe messaging.
Functions
uvrpc_publisher_t * uvrpc_publisher_create (uvrpc_config_t *config)
Create a new publisher.
void uvrpc_publisher_free (uvrpc_publisher_t *publisher)
Free the publisher.
int uvrpc_publisher_publish (uvrpc_publisher_t *publisher, const char *topic, const uint8_t *data, size_t size, uvrpc_publish_callback_t callback, void *ctx)
Publish a message to a topic.
int uvrpc_publisher_start (uvrpc_publisher_t *publisher)
Start the publisher.
void uvrpc_publisher_stop (uvrpc_publisher_t *publisher)
Stop the publisher.
int uvrpc_subscriber_connect (uvrpc_subscriber_t *subscriber)
Connect subscriber to publisher.
uvrpc_subscriber_t * uvrpc_subscriber_create (uvrpc_config_t *config)
Create a new subscriber.
void uvrpc_subscriber_disconnect (uvrpc_subscriber_t *subscriber)
Disconnect subscriber.
void uvrpc_subscriber_free (uvrpc_subscriber_t *subscriber)
Free the subscriber.
int uvrpc_subscriber_subscribe (uvrpc_subscriber_t *subscriber, const char *topic, uvrpc_subscribe_callback_t callback, void *ctx)
Subscribe to a topic.
int uvrpc_subscriber_unsubscribe (uvrpc_subscriber_t *subscriber, const char *topic)
Unsubscribe from a topic.
Detailed Description
Functions for publish-subscribe messaging.
Function Documentation
uvrpc_publisher_create()
uvrpc_publisher_t * uvrpc_publisher_create (uvrpc_config_t * config)
Create a new publisher.
Parameters
config Configuration structure
Returns
New publisher instance, or NULL on failure
Definition at line 31 of file uvrpc_publisher.c.
                                                                  {
    if (!config || !config->loop || !config->address) return NULL;
    uvrpc_publisher_t* publisher = uvrpc_calloc(1, sizeof(uvrpc_publisher_t));
    if (!publisher) return NULL;
    publisher->loop = config->loop;
    publisher->address = uvrpc_strdup(config->address);
    if (!publisher->address) {
        uvrpc_free(publisher);
        return NULL;
    }
    /* Convert uvrpc_transport_type to uvbus_transport_type_t */
    publisher->transport_type = (uvbus_transport_type_t)config->transport;
    publisher->is_running = 0;
    /* Create uvbus config */
    uvbus_config_t* bus_config = uvbus_config_new();
    if (!bus_config) {
        uvrpc_free(publisher->address);
        uvrpc_free(publisher);
        return NULL;
    }
    uvbus_config_set_loop(bus_config, publisher->loop);
    uvbus_config_set_transport(bus_config, publisher->transport_type);
    uvbus_config_set_address(bus_config, publisher->address);
    /* Create uvbus server (broadcast publisher) */
    publisher->uvbus = uvbus_server_new(bus_config);
    uvbus_config_free(bus_config);
    if (!publisher->uvbus) {
        uvrpc_free(publisher->address);
        uvrpc_free(publisher);
        return NULL;
    }
    return publisher;
}
References uvrpc_config::address, uvrpc_publisher::address, uvrpc_publisher::is_running, uvrpc_config::loop, uvrpc_publisher::loop, uvrpc_config::transport, uvrpc_publisher::transport_type, uvrpc_publisher::uvbus, uvbus_config_free(), uvbus_config_new(), uvbus_config_set_address(), uvbus_config_set_loop(), uvbus_config_set_transport(), uvbus_server_new(), uvrpc_calloc(), uvrpc_free(), and uvrpc_strdup().
uvrpc_publisher_free()
void uvrpc_publisher_free (uvrpc_publisher_t * publisher)
Free the publisher.
Parameters
publisher Publisher instance
Definition at line 96 of file uvrpc_publisher.c.
                                                        {
    if (!publisher) return;
    uvrpc_publisher_stop(publisher);
    /* Free uvbus */
    if (publisher->uvbus) {
        uvbus_free(publisher->uvbus);
    }
    uvrpc_free(publisher->address);
    uvrpc_free(publisher);
}
References uvrpc_publisher::address, uvrpc_publisher::uvbus, uvbus_free(), uvrpc_free(), and uvrpc_publisher_stop().
uvrpc_publisher_publish()
int uvrpc_publisher_publish (uvrpc_publisher_t * publisher, const char * topic, const uint8_t * data, size_t size, uvrpc_publish_callback_t callback, void * ctx)
Publish a message to a topic.
Parameters
publisher Publisher instance
topic Topic name
data Message data
size Data size
callback Publish callback
ctx User context
Returns
UVRPC_OK on success, error code on failure
Definition at line 111 of file uvrpc_publisher.c.
                                                                           {
    if (!publisher || !topic) return UVRPC_ERROR_INVALID_PARAM;
    if (!publisher->is_running) {
        return UVRPC_ERROR;
    }
    /* Encode broadcast message: [topic_len, topic, data_len, data] */
    size_t topic_len = strlen(topic);
    size_t total_size = 4 + topic_len + 4 + size;
    uint8_t* msg = (uint8_t*)uvrpc_alloc(total_size);
    if (!msg) return UVRPC_ERROR_NO_MEMORY;
    uint8_t* p = msg;
    /* Topic length (4 bytes little-endian for consistency with FlatBuffers) */
    *(uint32_t*)p = (uint32_t)topic_len;
    p += 4;
    /* Topic */
    memcpy(p, topic, topic_len);
    p += topic_len;
    /* Data length (4 bytes little-endian) */
    *(uint32_t*)p = (uint32_t)size;
    p += 4;
    /* Data */
    if (data && size > 0) {
        memcpy(p, data, size);
    }
    /* Send message */
    if (publisher->uvbus) {
        uvbus_client_send(publisher->uvbus, msg, total_size);
    }
    uvrpc_free(msg);
    /* Call callback */
    if (callback) {
        callback(UVRPC_OK, ctx);
    }
    return UVRPC_OK;
}
References uvrpc_publisher::is_running, uvrpc_publisher::uvbus, uvbus_client_send(), uvrpc_alloc(), UVRPC_ERROR, UVRPC_ERROR_INVALID_PARAM, UVRPC_ERROR_NO_MEMORY, uvrpc_free(), and UVRPC_OK.
uvrpc_publisher_start()
int uvrpc_publisher_start (uvrpc_publisher_t * publisher)
Start the publisher.
Parameters
publisher Publisher instance
Returns
UVRPC_OK on success, error code on failure
Definition at line 74 of file uvrpc_publisher.c.
                                                        {
    if (!publisher || !publisher->uvbus) return UVRPC_ERROR_INVALID_PARAM;
    if (publisher->is_running) return UVRPC_OK;
    /* Broadcast doesn't need a receive callback */
    int rv = uvbus_listen(publisher->uvbus);
    if (rv != UVBUS_OK) return UVRPC_ERROR_TRANSPORT;
    publisher->is_running = 1;
    printf("Publisher started on %s\n", publisher->address);
    return UVRPC_OK;
}
References uvrpc_publisher::address, uvrpc_publisher::is_running, uvrpc_publisher::uvbus, uvbus_listen(), UVBUS_OK, UVRPC_ERROR_INVALID_PARAM, UVRPC_ERROR_TRANSPORT, and UVRPC_OK.
uvrpc_publisher_stop()
void uvrpc_publisher_stop (uvrpc_publisher_t * publisher)
Stop the publisher.
Parameters
publisher Publisher instance
Definition at line 90 of file uvrpc_publisher.c.
                                                        {
    if (!publisher) return;
    publisher->is_running = 0;
}
References uvrpc_publisher::is_running.
Referenced by uvrpc_publisher_free().
uvrpc_subscriber_connect()
int uvrpc_subscriber_connect (uvrpc_subscriber_t * subscriber)
Connect subscriber to publisher.
Parameters
subscriber Subscriber instance
Returns
UVRPC_OK on success, error code on failure
Definition at line 154 of file uvrpc_subscriber.c.
                                                             {
    if (!subscriber || !subscriber->uvbus) return UVRPC_ERROR_INVALID_PARAM;
    if (subscriber->is_connected) return UVRPC_OK;
    int rv = uvbus_connect(subscriber->uvbus);
    if (rv != 0) return UVRPC_ERROR_TRANSPORT;
    return UVRPC_OK;
}
References uvrpc_subscriber::is_connected, uvrpc_subscriber::uvbus, uvbus_connect(), UVRPC_ERROR_INVALID_PARAM, UVRPC_ERROR_TRANSPORT, and UVRPC_OK.
uvrpc_subscriber_create()
uvrpc_subscriber_t * uvrpc_subscriber_create (uvrpc_config_t * config)
Create a new subscriber.
Parameters
config Configuration structure
Returns
New subscriber instance, or NULL on failure
Definition at line 108 of file uvrpc_subscriber.c.
                                                                    {
    if (!config || !config->loop || !config->address) return NULL;
    uvrpc_subscriber_t* subscriber = uvrpc_calloc(1, sizeof(uvrpc_subscriber_t));
    if (!subscriber) return NULL;
    subscriber->loop = config->loop;
    subscriber->address = uvrpc_strdup(config->address);
    if (!subscriber->address) {
        uvrpc_free(subscriber);
        return NULL;
    }
    /* Convert uvrpc_transport_type to uvbus_transport_type_t */
    subscriber->transport_type = (uvbus_transport_type_t)config->transport;
    subscriber->is_connected = 0;
    subscriber->subscriptions = NULL;
    /* Create uvbus config */
    uvbus_config_t* bus_config = uvbus_config_new();
    if (!bus_config) {
        uvrpc_free(subscriber->address);
        uvrpc_free(subscriber);
        return NULL;
    }
    uvbus_config_set_loop(bus_config, subscriber->loop);
    uvbus_config_set_transport(bus_config, subscriber->transport_type);
    uvbus_config_set_address(bus_config, subscriber->address);
    uvbus_config_set_recv_callback(bus_config, subscriber_recv_callback, subscriber);
    uvbus_config_set_connect_callback(bus_config, subscriber_connect_callback, subscriber);
    /* Create uvbus client (broadcast subscriber) */
    subscriber->uvbus = uvbus_client_new(bus_config);
    uvbus_config_free(bus_config);
    if (!subscriber->uvbus) {
        uvrpc_free(subscriber->address);
        uvrpc_free(subscriber);
        return NULL;
    }
    return subscriber;
}
References uvrpc_config::address, uvrpc_subscriber::address, uvrpc_subscriber::is_connected, uvrpc_config::loop, uvrpc_subscriber::loop, subscriber_connect_callback(), subscriber_recv_callback(), uvrpc_subscriber::subscriptions, uvrpc_config::transport, uvrpc_subscriber::transport_type, uvrpc_subscriber::uvbus, uvbus_client_new(), uvbus_config_free(), uvbus_config_new(), uvbus_config_set_address(), uvbus_config_set_connect_callback(), uvbus_config_set_loop(), uvbus_config_set_recv_callback(), uvbus_config_set_transport(), uvrpc_calloc(), uvrpc_free(), and uvrpc_strdup().
uvrpc_subscriber_disconnect()
void uvrpc_subscriber_disconnect (uvrpc_subscriber_t * subscriber)
Disconnect subscriber.
Parameters
subscriber Subscriber instance
Definition at line 166 of file uvrpc_subscriber.c.
                                                                 {
    if (!subscriber) return;
    if (subscriber->uvbus) {
        uvbus_disconnect(subscriber->uvbus);
    }
    subscriber->is_connected = 0;
}
References uvrpc_subscriber::is_connected, uvrpc_subscriber::uvbus, and uvbus_disconnect().
Referenced by uvrpc_subscriber_free().
uvrpc_subscriber_free()
void uvrpc_subscriber_free (uvrpc_subscriber_t * subscriber)
Free the subscriber.
Parameters
subscriber Subscriber instance
Definition at line 177 of file uvrpc_subscriber.c.
                                                           {
    if (!subscriber) return;
    uvrpc_subscriber_disconnect(subscriber);
    /* Free uvbus */
    if (subscriber->uvbus) {
        uvbus_free(subscriber->uvbus);
    }
    /* Free subscriptions */
    subscription_entry_t* entry, *tmp;
    HASH_ITER(hh, subscriber->subscriptions, entry, tmp) {
        HASH_DEL(subscriber->subscriptions, entry);
        uvrpc_free(entry->topic);
        uvrpc_free(entry);
    }
    uvrpc_free(subscriber->address);
    uvrpc_free(subscriber);
}
References uvrpc_subscriber::address, uvrpc_subscriber::subscriptions, subscription_entry::topic, uvrpc_subscriber::uvbus, uvbus_free(), uvrpc_free(), and uvrpc_subscriber_disconnect().
uvrpc_subscriber_subscribe()
int uvrpc_subscriber_subscribe (uvrpc_subscriber_t * subscriber, const char * topic, uvrpc_subscribe_callback_t callback, void * ctx)
Subscribe to a topic.
Parameters
subscriber Subscriber instance
topic Topic name
callback Subscription callback
ctx User context
Returns
UVRPC_OK on success, error code on failure
Definition at line 200 of file uvrpc_subscriber.c.
                                                                                 {
    if (!subscriber || !topic || !callback) return UVRPC_ERROR_INVALID_PARAM;
    /* Check if already subscribed */
    subscription_entry_t* entry = NULL;
    HASH_FIND_STR(subscriber->subscriptions, topic, entry);
    if (entry) return UVRPC_ERROR; /* Already subscribed */
    /* Create new subscription */
    entry = uvrpc_calloc(1, sizeof(subscription_entry_t));
    if (!entry) return UVRPC_ERROR_NO_MEMORY;
    entry->topic = uvrpc_strdup(topic);
    if (!entry->topic) {
        uvrpc_free(entry);
        return UVRPC_ERROR_NO_MEMORY;
    }
    entry->callback = callback;
    entry->ctx = ctx;
    HASH_ADD_STR(subscriber->subscriptions, topic, entry);
    printf("Subscribed to topic: %s\n", topic);
    return UVRPC_OK;
}
References subscription_entry::callback, subscription_entry::ctx, uvrpc_subscriber::subscriptions, subscription_entry::topic, uvrpc_calloc(), UVRPC_ERROR, UVRPC_ERROR_INVALID_PARAM, UVRPC_ERROR_NO_MEMORY, uvrpc_free(), UVRPC_OK, and uvrpc_strdup().
uvrpc_subscriber_unsubscribe()
int uvrpc_subscriber_unsubscribe (uvrpc_subscriber_t * subscriber, const char * topic)
Unsubscribe from a topic.
Parameters
subscriber Subscriber instance
topic Topic name
Returns
UVRPC_OK on success, error code on failure
Definition at line 229 of file uvrpc_subscriber.c.
                                                                                    {
    if (!subscriber || !topic) return UVRPC_ERROR_INVALID_PARAM;
    /* Find subscription */
    subscription_entry_t* entry = NULL;
    HASH_FIND_STR(subscriber->subscriptions, topic, entry);
    if (!entry) return UVRPC_ERROR; /* Not subscribed */
    /* Remove subscription */
    HASH_DEL(subscriber->subscriptions, entry);
    uvrpc_free(entry->topic);
    uvrpc_free(entry);
    printf("Unsubscribed from topic: %s\n", topic);
    return UVRPC_OK;
}
References uvrpc_subscriber::subscriptions, subscription_entry::topic, UVRPC_ERROR, UVRPC_ERROR_INVALID_PARAM, uvrpc_free(), and UVRPC_OK.