Request/Response API
Functions for handling requests and responses.
Functions
void uvrpc_request_free (uvrpc_request_t *req)
Free a request object.
void uvrpc_request_send_response (uvrpc_request_t *req, int status, const uint8_t *result, size_t result_size)
Send a response to a request (deprecated, use uvrpc_response_send)
void uvrpc_response_free (uvrpc_response_t *resp)
Free a response object.
Detailed Description
Functions for handling requests and responses.
Function Documentation
uvrpc_request_free()
void uvrpc_request_free (uvrpc_request_t * req)
Free a request object.
Parameters
req Request object
Definition at line 384 of file uvrpc_server.c.
                                              {
    if (!req) return;
    /* Note: method and params point to frame data, don't free them here */
}
uvrpc_request_send_response()
void uvrpc_request_send_response (uvrpc_request_t * req, int status, const uint8_t * result, size_t result_size)
Send a response to a request (deprecated, use uvrpc_response_send)
Parameters
req Request object
status Response status
result Response data
result_size Size of response data
Definition at line 356 of file uvrpc_server.c.
                                                                             {
    if (!req || !req->server || !req->client_ctx) {
        fprintf(stderr, "[SERVER] Invalid request or client_ctx is NULL\n");
        return;
    }
    uvrpc_server_t* server = req->server;
    /* Encode response */
    uint8_t* resp_data = NULL;
    size_t resp_size = 0;
    if (uvrpc_encode_response(req->msgid, result, result_size,
                              &resp_data, &resp_size) == UVRPC_OK) {
        /* Send response via UVBus */
        uvbus_t* uvbus = server->uvbus;
        uvbus_error_t err = uvbus_send_to(uvbus, resp_data, resp_size, req->client_ctx);
        if (err == UVBUS_OK) {
            server->total_responses++;
        } else {
            fprintf(stderr, "[SERVER] Failed to send response: %d\n", err);
        }
        uvrpc_free(resp_data);
    }
}
References uvrpc_request::client_ctx, uvrpc_request::msgid, uvrpc_request::server, uvrpc_server::total_responses, uvrpc_server::uvbus, UVBUS_OK, uvbus_send_to(), uvrpc_encode_response(), uvrpc_free(), and UVRPC_OK.
uvrpc_response_free()
void uvrpc_response_free (uvrpc_response_t * resp)
Free a response object.
Parameters
resp Response object
Definition at line 539 of file uvrpc_client.c.
                                                 {
    if (!resp) return;
    /* Note: error and result point to frame data, don't free them here */
}