Client API
Functions for creating and managing UVRPC clients.
Functions
int uvrpc_client_call (uvrpc_client_t *client, const char *method, const uint8_t *params, size_t params_size, uvrpc_callback_t callback, void *ctx)
Call RPC method with automatic retry.
int uvrpc_client_call_batch (uvrpc_client_t *client, const char **methods, const uint8_t **params_array, size_t *params_sizes, uvrpc_callback_t *callbacks, void **contexts, int count)
Call multiple RPC methods in batch.
int uvrpc_client_call_no_retry (uvrpc_client_t *client, const char *method, const uint8_t *params, size_t params_size, uvrpc_callback_t callback, void *ctx)
Call RPC method without retry.
int uvrpc_client_connect (uvrpc_client_t *client)
Connect to server synchronously.
int uvrpc_client_connect_with_callback (uvrpc_client_t *client, uvrpc_connect_callback_t callback, void *ctx)
Connect to server asynchronously.
uvrpc_client_t * uvrpc_client_create (uvrpc_config_t *config)
Create a new RPC client.
void uvrpc_client_disconnect (uvrpc_client_t *client)
Disconnect from server.
void uvrpc_client_free (uvrpc_client_t *client)
Free the client.
uvrpc_context_t * uvrpc_client_get_context (uvrpc_client_t *client)
Get client context.
uv_loop_t * uvrpc_client_get_loop (uvrpc_client_t *client)
Get the event loop.
int uvrpc_client_get_max_retries (uvrpc_client_t *client)
Get maximum retry count.
int uvrpc_client_get_pending_count (uvrpc_client_t *client)
Get pending request count.
void uvrpc_client_set_context (uvrpc_client_t *client, uvrpc_context_t *ctx)
Set client context.
int uvrpc_client_set_max_concurrent (uvrpc_client_t *client, int max_concurrent)
Set maximum concurrent requests.
int uvrpc_client_set_max_retries (uvrpc_client_t *client, int max_retries)
Set maximum retry count.
Detailed Description
Functions for creating and managing UVRPC clients.
Function Documentation
uvrpc_client_call()
int uvrpc_client_call (uvrpc_client_t * client, const char * method, const uint8_t * params, size_t params_size, uvrpc_callback_t callback, void * ctx)
Call RPC method with automatic retry.
Parameters
client Client instance
method Method name
params Request parameters
params_size Size of parameters
callback Response callback
ctx User context
Returns
UVRPC_OK on success, error code on failure
Definition at line 502 of file uvrpc_client.c.
                                                             {
    if (!client || !method) return UVRPC_ERROR_INVALID_PARAM;
    
    /* If retry is disabled, call directly */
    if (client->max_retries <= 0) {
        return uvrpc_client_call_no_retry_internal(client, method, params, params_size, callback, ctx);
    }
    
    /* Retry logic - just retry without running event loop */
    /* The event loop is driven externally, retries will be handled naturally */
    int ret;
    int retries = 0;
    
    do {
        ret = uvrpc_client_call_no_retry_internal(client, method, params, params_size, callback, ctx);
        
        if (ret == UVRPC_OK) {
            break; /* Success - exit retry loop */
        }
        
        retries++;
        
    } while (retries < client->max_retries);
    
    return ret;
}
References uvrpc_client::max_retries, uvrpc_client_call_no_retry_internal(), UVRPC_ERROR_INVALID_PARAM, and UVRPC_OK.
Referenced by uvrpc_async_all(), uvrpc_async_any(), and uvrpc_client_call_async().
uvrpc_client_call_batch()
int uvrpc_client_call_batch (uvrpc_client_t * client, const char ** methods, const uint8_t ** params_array, size_t * params_sizes, uvrpc_callback_t * callbacks, void ** contexts, int count)
Call multiple RPC methods in batch.
Parameters
client Client instance
methods Array of method names
params_array Array of parameter arrays
params_sizes Array of parameter sizes
callbacks Array of response callbacks
contexts Array of user contexts
count Number of calls
Returns
UVRPC_OK on success, error code on failure
Definition at line 558 of file uvrpc_client.c.
                                        {
    if (!client || !methods || !params_array || !params_sizes || !callbacks || !contexts) {
        return UVRPC_ERROR_INVALID_PARAM;
    }
    if (!client->is_connected) {
        return UVRPC_ERROR_NOT_CONNECTED;
    }
    if (count <= 0) {
        return UVRPC_ERROR_INVALID_PARAM;
    }
    /* Check concurrency limit */
    if (client->max_concurrent > 0 &&
        (client->current_concurrent + count) > client->max_concurrent) {
        return UVRPC_ERROR_RATE_LIMITED;
    }
    /* Send all requests */
    for (int i = 0; i < count; i++) {
        if (!methods[i]) {
            return UVRPC_ERROR_INVALID_PARAM;
        }
        /* Generate message ID */
        uint32_t msgid = uvrpc_msgid_next(client->msgid_ctx);
        /* Encode request */
        uint8_t* req_data = NULL;
        size_t req_size = 0;
        if (uvrpc_encode_request(msgid, methods[i], params_array[i], params_sizes[i],
                                  &req_data, &req_size) != UVRPC_OK) {
            return UVRPC_ERROR;
        }
        /* Register callback */
        if (callbacks[i]) {
            pending_callback_t* pending = uvrpc_calloc(1, sizeof(pending_callback_t));
            if (!pending) {
                uvrpc_free(req_data);
                return UVRPC_ERROR_NO_MEMORY;
            }
            uint32_t idx = (uint32_t)msgid % client->max_pending_callbacks;
            if (client->pending_callbacks[idx] != NULL) {
                uvrpc_free(pending);
                uvrpc_free(req_data);
                return UVRPC_ERROR_CALLBACK_LIMIT;
            }
            pending->msgid = (uint32_t)msgid;
            pending->callback = callbacks[i];
            pending->ctx = contexts[i];
            client->pending_callbacks[idx] = pending;
            /* Increase concurrent count */
            client->current_concurrent++;
        }
        /* Send request (no flush for batch except last) */
        if (client->uvbus) {
            uvbus_send(client->uvbus, req_data, req_size);
        }
        uvrpc_free(req_data);
    }
    return UVRPC_OK;
}
References pending_callback::callback, pending_callback::ctx, uvrpc_client::current_concurrent, uvrpc_client::is_connected, uvrpc_client::max_concurrent, uvrpc_client::max_pending_callbacks, pending_callback::msgid, uvrpc_client::msgid_ctx, uvrpc_client::pending_callbacks, uvrpc_client::uvbus, uvbus_send(), uvrpc_calloc(), uvrpc_encode_request(), UVRPC_ERROR, UVRPC_ERROR_CALLBACK_LIMIT, UVRPC_ERROR_INVALID_PARAM, UVRPC_ERROR_NO_MEMORY, UVRPC_ERROR_NOT_CONNECTED, UVRPC_ERROR_RATE_LIMITED, uvrpc_free(), uvrpc_msgid_next(), and UVRPC_OK.
uvrpc_client_call_no_retry()
int uvrpc_client_call_no_retry (uvrpc_client_t * client, const char * method, const uint8_t * params, size_t params_size, uvrpc_callback_t callback, void * ctx)
Call RPC method without retry.
Parameters
client Client instance
method Method name
params Request parameters
params_size Size of parameters
callback Response callback
ctx User context
Returns
UVRPC_OK on success, error code on failure
Definition at line 532 of file uvrpc_client.c.
                                                                      {
    return uvrpc_client_call_no_retry_internal(client, method, params, params_size, callback, ctx);
}
References uvrpc_client_call_no_retry_internal().
uvrpc_client_connect()
int uvrpc_client_connect (uvrpc_client_t * client)
Connect to server synchronously.
Parameters
client Client instance
Returns
UVRPC_OK on success, error code on failure
Definition at line 312 of file uvrpc_client.c.
                                                 {
    if (!client || !client->uvbus) return UVRPC_ERROR_INVALID_PARAM;
    
    if (client->is_connected) return UVRPC_OK;
    
    uvbus_error_t err = uvbus_connect(client->uvbus);
    if (err != UVBUS_OK) {
        return UVRPC_ERROR_TRANSPORT;
    }
    
    /* Note: is_connected will be set in the async callback */
    return UVRPC_OK;
}
References uvrpc_client::is_connected, uvrpc_client::uvbus, uvbus_connect(), UVBUS_OK, UVRPC_ERROR_INVALID_PARAM, UVRPC_ERROR_TRANSPORT, and UVRPC_OK.
uvrpc_client_connect_with_callback()
int uvrpc_client_connect_with_callback (uvrpc_client_t * client, uvrpc_connect_callback_t callback, void * ctx)
Connect to server asynchronously.
Parameters
client Client instance
callback Connection callback
ctx User context
Returns
UVRPC_OK on success, error code on failure
Definition at line 327 of file uvrpc_client.c.
                                                                                       {
    if (!client || !client->uvbus) return UVRPC_ERROR_INVALID_PARAM;
    
    if (client->is_connected) return UVRPC_OK;
    
    /* Store user callback */
    client->user_connect_callback = callback;
    client->user_connect_ctx = ctx;
    
    /* Update UVBus config and transport callbacks */
    uvbus_t* uvbus = client->uvbus;
    uvbus->config.connect_cb = client_connect_callback;
    uvbus->config.callback_ctx = client;
    
    /* Also update transport callbacks directly for INPROC */
    if (uvbus->transport) {
        uvbus->transport->connect_cb = client_connect_callback;
        uvbus->transport->callback_ctx = client;
    }
    
    uvbus_error_t err = uvbus_connect(uvbus);
    if (err != UVBUS_OK) {
        return UVRPC_ERROR_TRANSPORT;
    }
    
    /* Note: is_connected will be set in the async callback */
    return UVRPC_OK;
}
References uvbus_config::callback_ctx, uvbus_transport::callback_ctx, client_connect_callback(), uvbus::config, uvbus_config::connect_cb, uvbus_transport::connect_cb, uvrpc_client::is_connected, uvbus::transport, uvrpc_client::user_connect_callback, uvrpc_client::user_connect_ctx, uvrpc_client::uvbus, uvbus_connect(), UVBUS_OK, UVRPC_ERROR_INVALID_PARAM, UVRPC_ERROR_TRANSPORT, and UVRPC_OK.
uvrpc_client_create()
uvrpc_client_t * uvrpc_client_create (uvrpc_config_t * config)
Create a new RPC client.
Parameters
config Configuration structure
Returns
New client instance, or NULL on failure
Definition at line 206 of file uvrpc_client.c.
                                                            {
    if (!config || !config->loop || !config->address) return NULL;
    uvrpc_client_t* client = uvrpc_calloc(1, sizeof(uvrpc_client_t));
    if (!client) return NULL;
    client->loop = config->loop;
    client->address = uvrpc_strdup(config->address);
    if (!client->address) {
        uvrpc_free(client);
        return NULL;
    }
    client->is_connected = 0;
    client->performance_mode = config->performance_mode;
    client->user_connect_callback = NULL;
    client->user_connect_ctx = NULL;
    /* Initialize concurrency control */
    client->max_concurrent = config->max_concurrent;
    client->current_concurrent = 0;
    client->timeout_ms = config->timeout_ms;
    /* Initialize ring buffer with runtime size */
    client->max_pending_callbacks = config->max_pending_callbacks;
    client->generation = 0;
    
    /* Allocate ring buffer array */
    client->pending_callbacks = (pending_callback_t**)uvrpc_calloc(
        client->max_pending_callbacks, sizeof(pending_callback_t*));
    if (!client->pending_callbacks) {
        uvrpc_free(client->address);
        uvrpc_free(client);
        return NULL;
    }
    /* Initialize batch processing */
    client->batching_enabled = (config->performance_mode == UVRPC_PERF_HIGH_THROUGHPUT);
    client->batch_size = 0;
    client->max_batch_size = 100; /* Default batch size */
    /* Initialize retry configuration */
    client->max_retries = 0; /* Default: no retry */
    /* Create message ID generator with unique offset from config */
    client->msgid_ctx = uvrpc_msgid_ctx_new();
    if (client->msgid_ctx) {
        /* Use msgid_offset from config if set, otherwise use default offset */
        uint32_t offset = (config->msgid_offset > 0) ? config->msgid_offset : 1;
        uvrpc_msgid_ctx_set_start(client->msgid_ctx, offset);
    }
    /* Create UVBus configuration */
    uvbus_config_t* bus_config = uvbus_config_new();
    if (!bus_config) {
        uvrpc_msgid_ctx_free(client->msgid_ctx);
        uvrpc_free(client->address);
        uvrpc_free(client);
        return NULL;
    }
    
    uvbus_config_set_loop(bus_config, config->loop);
    
    /* Map UVRPC transport type to UVBus transport type */
    uvbus_transport_type_t uvbus_type;
    switch (config->transport) {
        case UVRPC_TRANSPORT_TCP:
            uvbus_type = UVBUS_TRANSPORT_TCP;
            break;
        case UVRPC_TRANSPORT_UDP:
            uvbus_type = UVBUS_TRANSPORT_UDP;
            break;
        case UVRPC_TRANSPORT_IPC:
            uvbus_type = UVBUS_TRANSPORT_IPC;
            break;
        case UVRPC_TRANSPORT_INPROC:
            uvbus_type = UVBUS_TRANSPORT_INPROC;
            break;
        default:
            uvbus_config_free(bus_config);
            uvrpc_msgid_ctx_free(client->msgid_ctx);
            uvrpc_free(client->address);
            uvrpc_free(client);
            return NULL;
    }
    
    uvbus_config_set_transport(bus_config, uvbus_type);
    uvbus_config_set_address(bus_config, client->address);
    uvbus_config_set_recv_callback(bus_config, client_recv_callback, client);
    uvbus_config_set_connect_callback(bus_config, client_connect_callback, client);
    
    /* Create UVBus client */
    client->uvbus = uvbus_client_new(bus_config);
    if (!client->uvbus) {
        uvbus_config_free(bus_config);
        uvrpc_msgid_ctx_free(client->msgid_ctx);
        uvrpc_free(client->address);
        uvrpc_free(client);
        return NULL;
    }
    
    uvbus_config_free(bus_config);
    return client;
}
References uvrpc_config::address, uvrpc_client::address, uvrpc_client::batch_size, uvrpc_client::batching_enabled, client_connect_callback(), client_recv_callback(), uvrpc_client::current_concurrent, uvrpc_client::generation, uvrpc_client::is_connected, uvrpc_config::loop, uvrpc_client::loop, uvrpc_client::max_batch_size, uvrpc_config::max_concurrent, uvrpc_client::max_concurrent, uvrpc_config::max_pending_callbacks, uvrpc_client::max_pending_callbacks, uvrpc_client::max_retries, uvrpc_client::msgid_ctx, uvrpc_config::msgid_offset, uvrpc_client::pending_callbacks, uvrpc_config::performance_mode, uvrpc_client::performance_mode, uvrpc_config::timeout_ms, uvrpc_client::timeout_ms, uvrpc_config::transport, uvrpc_client::user_connect_callback, uvrpc_client::user_connect_ctx, uvrpc_client::uvbus, uvbus_client_new(), uvbus_config_free(), uvbus_config_new(), uvbus_config_set_address(), uvbus_config_set_connect_callback(), uvbus_config_set_loop(), uvbus_config_set_recv_callback(), uvbus_config_set_transport(), UVBUS_TRANSPORT_INPROC, UVBUS_TRANSPORT_IPC, UVBUS_TRANSPORT_TCP, UVBUS_TRANSPORT_UDP, uvrpc_calloc(), uvrpc_free(), uvrpc_msgid_ctx_free(), uvrpc_msgid_ctx_new(), uvrpc_msgid_ctx_set_start(), UVRPC_PERF_HIGH_THROUGHPUT, uvrpc_strdup(), UVRPC_TRANSPORT_INPROC, UVRPC_TRANSPORT_IPC, UVRPC_TRANSPORT_TCP, and UVRPC_TRANSPORT_UDP.
uvrpc_client_disconnect()
void uvrpc_client_disconnect (uvrpc_client_t * client)
Disconnect from server.
Parameters
client Client instance
Definition at line 358 of file uvrpc_client.c.
                                                     {
    if (!client) return;
    
    if (client->uvbus) {
        uvbus_disconnect(client->uvbus);
    }
    
    client->is_connected = 0;
}
References uvrpc_client::is_connected, uvrpc_client::uvbus, and uvbus_disconnect().
Referenced by uvrpc_client_free().
uvrpc_client_free()
void uvrpc_client_free (uvrpc_client_t * client)
Free the client.
Parameters
client Client instance
Definition at line 369 of file uvrpc_client.c.
                                               {
    if (!client) return;
    uvrpc_client_disconnect(client);
    /* Free UVBus */
    if (client->uvbus) {
        uvbus_free(client->uvbus);
    }
    /* Free message ID context */
    if (client->msgid_ctx) {
        uvrpc_msgid_ctx_free(client->msgid_ctx);
    }
    client->is_connected = 0;
    /* Free all pending callbacks from ring buffer array */
    for (int i = 0; i < client->max_pending_callbacks; i++) {
        if (client->pending_callbacks[i]) {
            uvrpc_free(client->pending_callbacks[i]);
            client->pending_callbacks[i] = NULL;
        }
    }
    
    /* Free ring buffer array itself */
    if (client->pending_callbacks) {
        uvrpc_free(client->pending_callbacks);
        client->pending_callbacks = NULL;
    }
    uvrpc_free(client->address);
    uvrpc_free(client);
}
References uvrpc_client::address, uvrpc_client::is_connected, uvrpc_client::max_pending_callbacks, uvrpc_client::msgid_ctx, uvrpc_client::pending_callbacks, uvrpc_client::uvbus, uvbus_free(), uvrpc_client_disconnect(), uvrpc_free(), and uvrpc_msgid_ctx_free().
uvrpc_client_get_context()
uvrpc_context_t * uvrpc_client_get_context (uvrpc_client_t * client)
Get client context.
Parameters
client Client instance
Returns
Context instance
Definition at line 418 of file uvrpc_client.c.
                                                                  {
    return client ? client->ctx : NULL;
}
References uvrpc_client::ctx.
uvrpc_client_get_loop()
uv_loop_t * uvrpc_client_get_loop (uvrpc_client_t * client)
Get the event loop.
Parameters
client Client instance
Returns
libuv event loop
Definition at line 405 of file uvrpc_client.c.
                                                         {
    if (!client) return NULL;
    return client->loop;
}
References uvrpc_client::loop.
uvrpc_client_get_max_retries()
int uvrpc_client_get_max_retries (uvrpc_client_t * client)
Get maximum retry count.
Parameters
client Client instance
Returns
Maximum number of retries
Definition at line 431 of file uvrpc_client.c.
                                                         {
    if (!client) return 0;
    return client->max_retries;
}
References uvrpc_client::max_retries.
uvrpc_client_get_pending_count()
int uvrpc_client_get_pending_count (uvrpc_client_t * client)
Get pending request count.
Parameters
client Client instance
Returns
Number of pending requests
Definition at line 552 of file uvrpc_client.c.
                                                           {
    if (!client) return 0;
    return client->current_concurrent;
}
References uvrpc_client::current_concurrent.
uvrpc_client_set_context()
void uvrpc_client_set_context (uvrpc_client_t * client, uvrpc_context_t * ctx)
Set client context.
Parameters
client Client instance
ctx Context to attach
Definition at line 411 of file uvrpc_client.c.
                                                                            {
    if (client) {
        client->ctx = ctx;
    }
}
References uvrpc_client::ctx.
uvrpc_client_set_max_concurrent()
int uvrpc_client_set_max_concurrent (uvrpc_client_t * client, int max_concurrent)
Set maximum concurrent requests.
Parameters
client Client instance
max_concurrent Maximum concurrent requests
Returns
UVRPC_OK on success, error code on failure
Definition at line 545 of file uvrpc_client.c.
                                                                                {
    if (!client) return UVRPC_ERROR_INVALID_PARAM;
    client->max_concurrent = (max_concurrent > 0) ? max_concurrent : UVRPC_MAX_CONCURRENT_REQUESTS;
    return UVRPC_OK;
}
References uvrpc_client::max_concurrent, UVRPC_ERROR_INVALID_PARAM, and UVRPC_OK.
uvrpc_client_set_max_retries()
int uvrpc_client_set_max_retries (uvrpc_client_t * client, int max_retries)
Set maximum retry count.
Parameters
client Client instance
max_retries Maximum number of retries
Returns
UVRPC_OK on success, error code on failure
Definition at line 423 of file uvrpc_client.c.
                                                                          {
    if (!client) return UVRPC_ERROR_INVALID_PARAM;
    if (max_retries < 0) return UVRPC_ERROR_INVALID_PARAM;
    client->max_retries = max_retries;
    return UVRPC_OK;
}
References uvrpc_client::max_retries, UVRPC_ERROR_INVALID_PARAM, and UVRPC_OK.