Context API
Functions for managing user contexts.
Functions
void uvrpc_context_free (uvrpc_context_t *ctx)
Free a context.
void * uvrpc_context_get_data (uvrpc_context_t *ctx)
Get user data from context.
uvrpc_context_t * uvrpc_context_new (void *data)
Create a new context with user data.
uvrpc_context_t * uvrpc_context_new_with_cleanup (void *data, uvrpc_context_cleanup_t cleanup, void *cleanup_data)
Create a new context with cleanup callback.
Detailed Description
Functions for managing user contexts.
Function Documentation
uvrpc_context_free()
void uvrpc_context_free (uvrpc_context_t * ctx)
Free a context.
If a cleanup callback was registered, it will be called.
Parameters
ctx Context to free
Definition at line 40 of file uvrpc_context.c.
                                              {
    if (!ctx) return;
    
    if (ctx->cleanup && ctx->data) {
        ctx->cleanup(ctx->data, ctx->cleanup_data);
    }
    
    uvrpc_free(ctx);
}
References uvrpc_context::cleanup, uvrpc_context::cleanup_data, uvrpc_context::data, and uvrpc_free().
uvrpc_context_get_data()
void * uvrpc_context_get_data (uvrpc_context_t * ctx)
Get user data from context.
Parameters
ctx Context instance
Returns
User data pointer
Definition at line 51 of file uvrpc_context.c.
                                                   {
    return ctx ? ctx->data : NULL;
}
References uvrpc_context::data.
uvrpc_context_new()
uvrpc_context_t * uvrpc_context_new (void * data)
Create a new context with user data.
Parameters
data User data to attach
Returns
New context instance, or NULL on failure
Definition at line 19 of file uvrpc_context.c.
                                               {
    uvrpc_context_t* ctx = (uvrpc_context_t*)uvrpc_calloc(1, sizeof(uvrpc_context_t));
    if (ctx) {
        ctx->data = data;
    }
    return ctx;
}
References uvrpc_context::data, and uvrpc_calloc().
Referenced by uvrpc_context_new_with_cleanup().
uvrpc_context_new_with_cleanup()
uvrpc_context_t * uvrpc_context_new_with_cleanup (void * data, uvrpc_context_cleanup_t cleanup, void * cleanup_data)
Create a new context with cleanup callback.
Parameters
data User data to attach
cleanup Cleanup callback function
cleanup_data Data passed to cleanup callback
Returns
New context instance, or NULL on failure
Definition at line 28 of file uvrpc_context.c.
                                                                      {
    uvrpc_context_t* ctx = uvrpc_context_new(data);
    if (ctx) {
        ctx->cleanup = cleanup;
        ctx->cleanup_data = cleanup_data;
    }
    return ctx;
}
References uvrpc_context::cleanup, uvrpc_context::cleanup_data, and uvrpc_context_new().