src/uvbus_transport_inproc.c File Reference
Classes
struct inproc_client
struct inproc_endpoint
Typedefs
typedef struct inproc_client inproc_client_t
typedef struct inproc_endpoint inproc_endpoint_t
Functions
uvbus_transport_t * create_inproc_transport (uvbus_transport_type_t type, uv_loop_t *loop)
static unsigned int hash_string (const char *str)
static void inproc_add_client (inproc_endpoint_t *endpoint, void *client)
static void inproc_add_endpoint (inproc_endpoint_t *endpoint)
static int inproc_connect (void *impl_ptr, const char *address)
static void inproc_disconnect (void *impl_ptr)
static inproc_endpoint_t * inproc_find_endpoint (const char *name)
static void inproc_free (void *impl_ptr)
static int inproc_listen (void *impl_ptr, const char *address)
static void inproc_remove_client (inproc_endpoint_t *endpoint, void *client)
static void inproc_remove_endpoint (inproc_endpoint_t *endpoint)
static int inproc_send (void *impl_ptr, const uint8_t *data, size_t size)
static int inproc_send_to (void *impl_ptr, const uint8_t *data, size_t size, void *target)
static void inproc_send_to_all (inproc_endpoint_t *endpoint, const uint8_t *data, size_t size)
Variables
static inproc_endpoint_t * g_endpoint_hash [UVBUS_HASH_TABLE_SIZE] = {NULL}
static inproc_endpoint_t * g_endpoint_list = NULL
static pthread_mutex_t g_endpoint_mutex = PTHREAD_MUTEX_INITIALIZER
static const uvbus_transport_vtable_t inproc_vtable
Typedef Documentation
inproc_client_t
typedef struct inproc_client inproc_client_t
inproc_endpoint_t
typedef struct inproc_endpoint inproc_endpoint_t
Function Documentation
create_inproc_transport()
uvbus_transport_t * create_inproc_transport (uvbus_transport_type_t type, uv_loop_t * loop)
Definition at line 414 of file uvbus_transport_inproc.c.
                                                                                         {
    uvbus_transport_t* transport = (uvbus_transport_t*)uvrpc_alloc(sizeof(uvbus_transport_t));
    if (!transport) {
        return NULL;
    }
    
    memset(transport, 0, sizeof(uvbus_transport_t));
    transport->type = type;
    transport->loop = loop;
    transport->vtable = &inproc_vtable;
    
    return transport;
}
References inproc_vtable, uvbus_transport::loop, uvbus_transport::type, uvrpc_alloc(), and uvbus_transport::vtable.
Referenced by create_transport().
hash_string()
static unsigned int hash_string (const char * str) [static]
Definition at line 50 of file uvbus_transport_inproc.c.
                                                 {
    unsigned int hash = 5381;
    int c;
    while ((c = *str++)) {
        hash = ((hash << 5) + hash) + c;
    }
    return hash % UVBUS_HASH_TABLE_SIZE;
}
Referenced by inproc_add_endpoint(), inproc_find_endpoint(), and inproc_remove_endpoint().
inproc_add_client()
static void inproc_add_client (inproc_endpoint_t * endpoint, void * client) [static]
Definition at line 104 of file uvbus_transport_inproc.c.
                                                                         {
    pthread_mutex_lock(&g_endpoint_mutex);
    if (endpoint->client_count >= endpoint->client_capacity) {
        endpoint->client_capacity *= 2;
        endpoint->clients = (void**)uvrpc_realloc(
            endpoint->clients,
            sizeof(void*) * endpoint->client_capacity
        );
    }
    
    endpoint->clients[endpoint->client_count++] = client;
    pthread_mutex_unlock(&g_endpoint_mutex);
}
References inproc_endpoint::client_capacity, inproc_endpoint::client_count, inproc_endpoint::clients, g_endpoint_mutex, and uvrpc_realloc().
Referenced by inproc_connect().
inproc_add_endpoint()
static void inproc_add_endpoint (inproc_endpoint_t * endpoint) [static]
Definition at line 78 of file uvbus_transport_inproc.c.
                                                             {
    pthread_mutex_lock(&g_endpoint_mutex);
    unsigned int hash = hash_string(endpoint->name);
    endpoint->next = g_endpoint_hash[hash];
    g_endpoint_hash[hash] = endpoint;
    pthread_mutex_unlock(&g_endpoint_mutex);
}
References g_endpoint_hash, g_endpoint_mutex, hash_string(), inproc_endpoint::name, and inproc_endpoint::next.
Referenced by inproc_listen().
inproc_connect()
static int inproc_connect (void * impl_ptr, const char * address) [static]
Definition at line 239 of file uvbus_transport_inproc.c.
                                                               {
    uvbus_transport_t* transport = (uvbus_transport_t*)impl_ptr;
    if (!transport) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    if (transport->is_server) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    /* Skip protocol prefix */
    const char* name = address;
    if (strncmp(address, "inproc://", 9) == 0) {
        name += 9;
    }
    
    /* Find endpoint */
    inproc_endpoint_t* endpoint = inproc_find_endpoint(name);
    if (!endpoint) {
        return UVBUS_ERROR_NOT_FOUND;
    }
    
    /* Create client */
    inproc_client_t* client = (inproc_client_t*)uvrpc_alloc(sizeof(inproc_client_t));
    if (!client) {
        return UVBUS_ERROR_NO_MEMORY;
    }
    
    client->server_endpoint = endpoint;
    client->client_transport = transport;
    client->is_active = 1;
    
    /* Set client's own callbacks */
    client->recv_cb = transport->recv_cb;
    client->error_cb = transport->error_cb;
    client->callback_ctx = transport->callback_ctx;
    
    /* Add to endpoint */
    inproc_add_client(endpoint, client);
    
    transport->impl.inproc_client = (void*)client;
    transport->is_connected = 1;
    
    /* Set bus as active */
    if (transport->parent_bus) {
        transport->parent_bus->is_active = 1;
    }
    
    printf("[INPROC CONNECT] connect_cb=%p, callback_ctx=%p\n",
           (void*)transport->connect_cb, (void*)transport->callback_ctx);
    fflush(stdout);
    
    if (transport->connect_cb) {
        printf("[INPROC CONNECT] Calling connect_cb...\n");
        fflush(stdout);
        transport->connect_cb(UVBUS_OK, transport->callback_ctx);
        printf("[INPROC CONNECT] connect_cb returned\n");
        fflush(stdout);
    }
    
    return UVBUS_OK;
}
References uvbus_transport::callback_ctx, inproc_client::callback_ctx, inproc_client::client_transport, uvbus_transport::connect_cb, uvbus_transport::error_cb, inproc_client::error_cb, uvbus_transport::impl, inproc_add_client(), uvbus_transport::inproc_client, inproc_find_endpoint(), uvbus::is_active, inproc_client::is_active, uvbus_transport::is_connected, uvbus_transport::is_server, uvbus_transport::parent_bus, uvbus_transport::recv_cb, inproc_client::recv_cb, inproc_client::server_endpoint, UVBUS_ERROR_INVALID_PARAM, UVBUS_ERROR_NO_MEMORY, UVBUS_ERROR_NOT_FOUND, UVBUS_OK, and uvrpc_alloc().
inproc_disconnect()
static void inproc_disconnect (void * impl_ptr) [static]
Definition at line 303 of file uvbus_transport_inproc.c.
                                              {
    uvbus_transport_t* transport = (uvbus_transport_t*)impl_ptr;
    if (!transport) {
        return;
    }
    
    if (transport->is_server && transport->impl.inproc_server) {
        inproc_endpoint_t* endpoint = (inproc_endpoint_t*)transport->impl.inproc_server;
        /* Remove endpoint from global list */
        inproc_remove_endpoint(endpoint);
        
        /* Free all clients */
        for (int i = 0; i < endpoint->client_count; i++) {
            if (endpoint->clients[i]) {
                inproc_client_t* client = (inproc_client_t*)endpoint->clients[i];
                client->is_active = 0;
            }
        }
        
        /* Free endpoint */
        uvrpc_free(endpoint->name);
        uvrpc_free(endpoint->clients);
        uvrpc_free(endpoint);
        transport->impl.inproc_server = NULL;
    } else if (!transport->is_server && transport->impl.inproc_client) {
        inproc_client_t* client = (inproc_client_t*)transport->impl.inproc_client;
        /* Remove from endpoint */
        if (client->server_endpoint) {
            inproc_remove_client(client->server_endpoint, client);
        }
        
        client->is_active = 0;
        uvrpc_free(client);
        transport->impl.inproc_client = NULL;
    }
    
    transport->is_connected = 0;
}
References inproc_endpoint::client_count, inproc_endpoint::clients, uvbus_transport::impl, uvbus_transport::inproc_client, inproc_remove_client(), inproc_remove_endpoint(), uvbus_transport::inproc_server, inproc_client::is_active, uvbus_transport::is_connected, uvbus_transport::is_server, inproc_endpoint::name, inproc_client::server_endpoint, and uvrpc_free().
Referenced by inproc_free().
inproc_find_endpoint()
static inproc_endpoint_t * inproc_find_endpoint (const char * name) [static]
Definition at line 60 of file uvbus_transport_inproc.c.
                                                                 {
    pthread_mutex_lock(&g_endpoint_mutex);
    unsigned int hash = hash_string(name);
    inproc_endpoint_t* endpoint = g_endpoint_hash[hash];
    
    while (endpoint) {
        if (strcmp(endpoint->name, name) == 0) {
            pthread_mutex_unlock(&g_endpoint_mutex);
            return endpoint;
        }
        endpoint = endpoint->next;
    }
    
    pthread_mutex_unlock(&g_endpoint_mutex);
    return NULL;
}
References g_endpoint_hash, g_endpoint_mutex, hash_string(), inproc_endpoint::name, and inproc_endpoint::next.
Referenced by inproc_connect(), and inproc_listen().
inproc_free()
static void inproc_free (void * impl_ptr) [static]
Definition at line 398 of file uvbus_transport_inproc.c.
                                        {
    uvbus_transport_t* transport = (uvbus_transport_t*)impl_ptr;
    if (!transport) {
        return;
    }
    
    inproc_disconnect(transport);
    
    if (transport->address) {
        uvrpc_free(transport->address);
    }
    
    uvrpc_free(transport);
}
References uvbus_transport::address, inproc_disconnect(), and uvrpc_free().
inproc_listen()
static int inproc_listen (void * impl_ptr, const char * address) [static]
Definition at line 184 of file uvbus_transport_inproc.c.
                                                              {
    uvbus_transport_t* transport = (uvbus_transport_t*)impl_ptr;
    if (!transport) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    if (!transport->is_server) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    /* Skip protocol prefix */
    const char* name = address;
    if (strncmp(address, "inproc://", 9) == 0) {
        name += 9;
    }
    
    /* Check if endpoint already exists */
    inproc_endpoint_t* endpoint = inproc_find_endpoint(name);
    if (endpoint) {
        return UVBUS_ERROR_ALREADY_EXISTS;
    }
    
    /* Create endpoint */
    endpoint = (inproc_endpoint_t*)uvrpc_alloc(sizeof(inproc_endpoint_t));
    if (!endpoint) {
        return UVBUS_ERROR_NO_MEMORY;
    }
    
    endpoint->name = uvrpc_strdup(name);
    endpoint->server_transport = transport;
    endpoint->clients = (void**)uvrpc_alloc(sizeof(void*) * UVBUS_INITIAL_CLIENT_CAPACITY);
    endpoint->client_capacity = UVBUS_INITIAL_CLIENT_CAPACITY;
    endpoint->client_count = 0;
    endpoint->next = NULL;
    
    /* Set callbacks */
    endpoint->recv_cb = transport->recv_cb;
    endpoint->error_cb = transport->error_cb;
    endpoint->callback_ctx = transport->callback_ctx;
    
    /* Add to global list */
    inproc_add_endpoint(endpoint);
    
    transport->impl.inproc_server = (void*)endpoint;
    transport->is_connected = 1;
    
    /* Set bus as active */
    if (transport->parent_bus) {
        transport->parent_bus->is_active = 1;
    }
    
    return UVBUS_OK;
}
References uvbus_transport::callback_ctx, inproc_endpoint::callback_ctx, inproc_endpoint::client_capacity, inproc_endpoint::client_count, inproc_endpoint::clients, uvbus_transport::error_cb, inproc_endpoint::error_cb, uvbus_transport::impl, inproc_add_endpoint(), inproc_find_endpoint(), uvbus_transport::inproc_server, uvbus::is_active, uvbus_transport::is_connected, uvbus_transport::is_server, inproc_endpoint::name, inproc_endpoint::next, uvbus_transport::parent_bus, uvbus_transport::recv_cb, inproc_endpoint::recv_cb, inproc_endpoint::server_transport, UVBUS_ERROR_ALREADY_EXISTS, UVBUS_ERROR_INVALID_PARAM, UVBUS_ERROR_NO_MEMORY, UVBUS_OK, uvrpc_alloc(), and uvrpc_strdup().
inproc_remove_client()
static void inproc_remove_client (inproc_endpoint_t * endpoint, void * client) [static]
Definition at line 119 of file uvbus_transport_inproc.c.
                                                                            {
    pthread_mutex_lock(&g_endpoint_mutex);
    for (int i = 0; i < endpoint->client_count; i++) {
        if (endpoint->clients[i] == client) {
            /* Shift remaining clients */
            for (int j = i; j < endpoint->client_count - 1; j++) {
                endpoint->clients[j] = endpoint->clients[j + 1];
            }
            endpoint->client_count--;
            pthread_mutex_unlock(&g_endpoint_mutex);
            return;
        }
    }
    pthread_mutex_unlock(&g_endpoint_mutex);
}
References inproc_endpoint::client_count, inproc_endpoint::clients, and g_endpoint_mutex.
Referenced by inproc_disconnect().
inproc_remove_endpoint()
static void inproc_remove_endpoint (inproc_endpoint_t * endpoint) [static]
Definition at line 87 of file uvbus_transport_inproc.c.
                                                                {
    pthread_mutex_lock(&g_endpoint_mutex);
    unsigned int hash = hash_string(endpoint->name);
    inproc_endpoint_t** ptr = &g_endpoint_hash[hash];
    
    while (*ptr) {
        if (*ptr == endpoint) {
            *ptr = endpoint->next;
            pthread_mutex_unlock(&g_endpoint_mutex);
            return;
        }
        ptr = &(*ptr)->next;
    }
    pthread_mutex_unlock(&g_endpoint_mutex);
}
References g_endpoint_hash, g_endpoint_mutex, hash_string(), inproc_endpoint::name, and inproc_endpoint::next.
Referenced by inproc_disconnect().
inproc_send()
static int inproc_send (void * impl_ptr, const uint8_t * data, size_t size) [static]
Definition at line 343 of file uvbus_transport_inproc.c.
                                                                         {
    uvbus_transport_t* transport = (uvbus_transport_t*)impl_ptr;
    if (!transport) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    if (!transport->is_connected) {
        return UVBUS_ERROR_NOT_CONNECTED;
    }
    
    if (transport->is_server && transport->impl.inproc_server) {
        inproc_endpoint_t* endpoint = (inproc_endpoint_t*)transport->impl.inproc_server;
        /* Broadcast to all clients */
        inproc_send_to_all(endpoint, data, size);
    } else if (!transport->is_server && transport->impl.inproc_client) {
        inproc_client_t* client = (inproc_client_t*)transport->impl.inproc_client;
        if (client->server_endpoint) {
            /* Send to server */
            inproc_endpoint_t* endpoint = client->server_endpoint;
            if (endpoint->recv_cb) {
                /* Pass client as client_ctx, and server context as server_ctx */
                endpoint->recv_cb(data, size, client, endpoint->callback_ctx);
            }
        }
    }
    
    return UVBUS_OK;
}
References inproc_endpoint::callback_ctx, uvbus_transport::impl, uvbus_transport::inproc_client, inproc_send_to_all(), uvbus_transport::inproc_server, uvbus_transport::is_connected, uvbus_transport::is_server, inproc_endpoint::recv_cb, inproc_client::server_endpoint, UVBUS_ERROR_INVALID_PARAM, UVBUS_ERROR_NOT_CONNECTED, and UVBUS_OK.
inproc_send_to()
static int inproc_send_to (void * impl_ptr, const uint8_t * data, size_t size, void * target) [static]
Definition at line 373 of file uvbus_transport_inproc.c.
                                                                                          {
    uvbus_transport_t* transport = (uvbus_transport_t*)impl_ptr;
    if (!transport) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    if (!transport->is_server) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    inproc_client_t* client = (inproc_client_t*)target;
    if (!client || !client->is_active) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    /* Call the client's callback, not the server's callback */
    if (client->recv_cb) {
        /* Pass client as client_ctx, and client's callback_ctx as server_ctx */
        client->recv_cb(data, size, client, client->callback_ctx);
    }
    
    return UVBUS_OK;
}
References inproc_client::callback_ctx, inproc_client::is_active, uvbus_transport::is_server, inproc_client::recv_cb, UVBUS_ERROR_INVALID_PARAM, and UVBUS_OK.
inproc_send_to_all()
static void inproc_send_to_all (inproc_endpoint_t * endpoint, const uint8_t * data, size_t size) [static]
Definition at line 136 of file uvbus_transport_inproc.c.
                                                           {
    pthread_mutex_lock(&g_endpoint_mutex);
    /* Copy client count to avoid holding lock during callbacks */
    int client_count = endpoint->client_count;
    void** clients = (void**)uvrpc_alloc(sizeof(void*) * client_count);
    if (clients) {
        memcpy(clients, endpoint->clients, sizeof(void*) * client_count);
    }
    pthread_mutex_unlock(&g_endpoint_mutex);
    
    if (!clients) return;
    
    /* Trigger callbacks without holding the lock */
    for (int i = 0; i < client_count; i++) {
        inproc_client_t* client = (inproc_client_t*)clients[i];
        if (client && client->is_active) {
            /* Use client's own callback instead of endpoint's */
            if (client->recv_cb) {
                /* Pass client as client_ctx, and server context (if any) as server_ctx */
                /* For INPROC, client->callback_ctx is the server context */
                client->recv_cb(data, size, client, client->callback_ctx);
            }
        }
    }
    
    uvrpc_free(clients);
}
References inproc_client::callback_ctx, inproc_endpoint::client_count, inproc_endpoint::clients, g_endpoint_mutex, inproc_client::is_active, inproc_client::recv_cb, uvrpc_alloc(), and uvrpc_free().
Referenced by inproc_send().
Variable Documentation
g_endpoint_hash
inproc_endpoint_t* g_endpoint_hash[UVBUS_HASH_TABLE_SIZE] = {NULL} [static]
Definition at line 47 of file uvbus_transport_inproc.c.
Referenced by inproc_add_endpoint(), inproc_find_endpoint(), and inproc_remove_endpoint().
g_endpoint_list
inproc_endpoint_t* g_endpoint_list = NULL [static]
Definition at line 43 of file uvbus_transport_inproc.c.
g_endpoint_mutex
pthread_mutex_t g_endpoint_mutex = PTHREAD_MUTEX_INITIALIZER [static]
UVBus INPROC Transport Implementation (In-Process)
Definition at line 13 of file uvbus_transport_inproc.c.
Referenced by inproc_add_client(), inproc_add_endpoint(), inproc_find_endpoint(), inproc_remove_client(), inproc_remove_endpoint(), and inproc_send_to_all().
inproc_vtable
const uvbus_transport_vtable_t inproc_vtable [static]
Initial value:
= {
    .listen = inproc_listen,
    .connect = inproc_connect,
    .disconnect = inproc_disconnect,
    .send = inproc_send,
    .send_to = inproc_send_to,
    .free = inproc_free
}
Definition at line 174 of file uvbus_transport_inproc.c.
Referenced by create_inproc_transport().