src/uvbus_transport_tcp.c File Reference
Classes
struct uvbus_tcp_client
struct uvbus_tcp_server
Typedefs
typedef struct uvbus_tcp_client uvbus_tcp_client_t
typedef struct uvbus_tcp_server uvbus_tcp_server_t
Functions
uvbus_transport_t * create_tcp_transport (uvbus_transport_type_t type, uv_loop_t *loop)
static void on_client_alloc (uv_handle_t *handle, size_t suggested_size, uv_buf_t *buf)
static void on_client_close (uv_handle_t *handle)
static void on_client_connect (uv_connect_t *req, int status)
static void on_client_read (uv_stream_t *stream, ssize_t nread, const uv_buf_t *buf)
static void on_server_close (uv_handle_t *handle)
static void on_server_connection (uv_stream_t *server, int status)
static void on_write (uv_write_t *req, int status)
static int parse_tcp_address (const char *address, char **host, int *port)
static int ref_dec (int *ref_count)
static int ref_inc (int *ref_count)
static void ref_init (int *ref_count)
static int tcp_connect (void *impl_ptr, const char *address)
static void tcp_disconnect (void *impl_ptr)
static void tcp_free (void *impl_ptr)
static int tcp_listen (void *impl_ptr, const char *address)
static int tcp_send (void *impl_ptr, const uint8_t *data, size_t size)
static int tcp_send_to (void *impl_ptr, const uint8_t *data, size_t size, void *target)
Variables
static const uvbus_transport_vtable_t tcp_vtable
Typedef Documentation
uvbus_tcp_client_t
typedef struct uvbus_tcp_client uvbus_tcp_client_t
Definition at line 20 of file uvbus_transport_tcp.c.
uvbus_tcp_server_t
typedef struct uvbus_tcp_server uvbus_tcp_server_t
Definition at line 21 of file uvbus_transport_tcp.c.
Function Documentation
create_tcp_transport()
uvbus_transport_t * create_tcp_transport (uvbus_transport_type_t type, uv_loop_t * loop)
Definition at line 709 of file uvbus_transport_tcp.c.
                                                                                      {
    uvbus_transport_t* transport = (uvbus_transport_t*)uvrpc_alloc(sizeof(uvbus_transport_t));
    if (!transport) {
        return NULL;
    }
    
    memset(transport, 0, sizeof(uvbus_transport_t));
    transport->type = type;
    transport->loop = loop;
    transport->vtable = &tcp_vtable;
    
    return transport;
}
References uvbus_transport::loop, tcp_vtable, uvbus_transport::type, uvrpc_alloc(), and uvbus_transport::vtable.
Referenced by create_transport().
on_client_alloc()
static void on_client_alloc (uv_handle_t * handle, size_t suggested_size, uv_buf_t * buf) [static]
Definition at line 218 of file uvbus_transport_tcp.c.
                                                                                       {
    buf->base = (char*)uvrpc_alloc(suggested_size);
    buf->len = suggested_size;
}
References uvrpc_alloc().
Referenced by on_client_connect(), and on_server_connection().
on_client_close()
static void on_client_close (uv_handle_t * handle) [static]
Definition at line 297 of file uvbus_transport_tcp.c.
                                                 {
    uvbus_tcp_client_t* client = (uvbus_tcp_client_t*)handle->data;
    if (!client) return;
    
    if (ref_dec(&client->ref_count) == 0) {
        /* Free resources when ref count reaches 0 */
        if (client->host) {
            uvrpc_free(client->host);
        }
        uvrpc_free(client);
    }
}
References uvbus_tcp_client::host, uvbus_tcp_client::ref_count, ref_dec(), and uvrpc_free().
Referenced by tcp_disconnect().
on_client_connect()
static void on_client_connect (uv_connect_t * req, int status) [static]
Definition at line 327 of file uvbus_transport_tcp.c.
                                                             {
    if (!req) {
        fprintf(stderr, "[TCP CONNECT] req is NULL\n");
        return;
    }
    uvbus_transport_t* transport = (uvbus_transport_t*)req->data;
    if (!transport) {
        fprintf(stderr, "[TCP CONNECT] transport is NULL\n");
        return;
    }
    fprintf(stderr, "[TCP CONNECT] status=%d (%s)\n", status, status == 0 ? "OK" : uv_strerror(status));
    fflush(stderr);
    if (status == 0) {
        transport->is_connected = 1;
        /* Start reading */
        uvbus_tcp_client_t* client = (uvbus_tcp_client_t*)transport->impl.tcp_client;
        if (client) {
            uv_read_start((uv_stream_t*)&client->tcp_handle, on_client_alloc, on_client_read);
            fprintf(stderr, "[TCP CONNECT] Read started\n");
            fflush(stderr);
        }
        /* Set bus is_active flag - this is critical for sending to work */
        if (transport->parent_bus) {
            transport->parent_bus->is_active = 1;
            fprintf(stderr, "[TCP CONNECT] Set parent_bus->is_active=1\n");
            fflush(stderr);
        } else {
            fprintf(stderr, "[TCP CONNECT] WARNING: parent_bus is NULL\n");
            fflush(stderr);
        }
        if (transport->connect_cb) {
            fprintf(stderr, "[TCP CONNECT] Calling connect_cb(UVBUS_OK)\n");
            fflush(stderr);
            transport->connect_cb(UVBUS_OK, transport->callback_ctx);
        } else {
            fprintf(stderr, "[TCP CONNECT] WARNING: connect_cb is NULL\n");
            fflush(stderr);
        }
    } else {
        fprintf(stderr, "[TCP CONNECT] Connection failed: %s\n", uv_strerror(status));
        fflush(stderr);
        if (transport->connect_cb) {
            fprintf(stderr, "[TCP CONNECT] Calling connect_cb(UVBUS_ERROR_IO)\n");
            fflush(stderr);
            transport->connect_cb(UVBUS_ERROR_IO, transport->callback_ctx);
        } else {
            fprintf(stderr, "[TCP CONNECT] WARNING: connect_cb is NULL\n");
            fflush(stderr);
        }
    }
}
References uvbus_transport::callback_ctx, uvbus_transport::connect_cb, uvbus_transport::impl, uvbus::is_active, uvbus_transport::is_connected, on_client_alloc(), on_client_read(), uvbus_transport::parent_bus, uvbus_transport::tcp_client, uvbus_tcp_client::tcp_handle, UVBUS_ERROR_IO, and UVBUS_OK.
Referenced by tcp_connect().
on_client_read()
static void on_client_read (uv_stream_t * stream, ssize_t nread, const uv_buf_t * buf) [static]
Definition at line 110 of file uvbus_transport_tcp.c.
                                                                                    {
    if (!stream) return;
    uvbus_tcp_client_t* client = (uvbus_tcp_client_t*)stream->data;
    if (!client) {
        uvrpc_free(buf->base);
        return;
    }
    uvbus_transport_t* transport = (uvbus_transport_t*)client->parent_transport;
    if (!transport) {
        uvrpc_free(buf->base);
        return;
    }
    
UVRPC_LOG("Transport: is_server=%d, recv_cb=%p", transport->is_server, transport->recv_cb);
    if (nread < 0) {
        if (nread != UV_EOF) {
            if (transport->error_cb) {
                transport->error_cb(UVBUS_ERROR_IO, uv_strerror(nread), transport->callback_ctx);
            }
        }
        uvrpc_free(buf->base);
        return;
    }
    if (nread > 0) {
        /* Add data to client's read buffer */
        if (client->read_pos + nread <= sizeof(client->read_buffer)) {
            memcpy(client->read_buffer + client->read_pos, buf->base, nread);
            client->read_pos += nread;
        } else {
            /* Buffer overflow - reset and log error */
            fprintf(stderr, "[TCP READ] Buffer overflow: read_pos=%zu, nread=%zd, buffer_size=%zu\n",
                    client->read_pos, nread, sizeof(client->read_buffer));
            fflush(stderr);
            client->read_pos = 0;
            uvrpc_free(buf->base);
            return;
        }
        /* Process complete frames */
        while (client->read_pos >= 4) {
            /* Parse frame length (big-endian) */
            uint32_t frame_size = (uint32_t)client->read_buffer[0] << 24 |
                                  (uint32_t)client->read_buffer[1] << 16 |
                                  (uint32_t)client->read_buffer[2] << 8 |
                                  (uint32_t)client->read_buffer[3];
            fprintf(stderr, "[TCP READ] Frame size: %u (read_pos=%zu)\n", frame_size, client->read_pos);
            fflush(stderr);
            /* Validate frame size - stricter limit for stability */
            if (frame_size == 0 || frame_size > 64*1024) { /* 64KB max */
                /* Invalid frame size, reset buffer */
                fprintf(stderr, "[TCP READ] Invalid frame size (%u), resetting buffer\n", frame_size);
                client->read_pos = 0;
                break;
            }
            size_t total_size = 4 + frame_size;
            if (client->read_pos < total_size) {
                /* Not enough data yet */
                break;
            }
            /* Extract frame data (skip 4-byte length prefix) */
            if (transport->recv_cb) {
                /* Copy frame data to heap so callback can safely access it */
                uint8_t* frame_copy = (uint8_t*)uvrpc_alloc(frame_size);
                if (!frame_copy) {
                    UVRPC_LOG("ERROR: Failed to allocate %u bytes for frame", frame_size);
                    if (transport->error_cb) {
                        transport->error_cb(UVBUS_ERROR_NO_MEMORY, "Frame allocation failed", transport->callback_ctx);
                    }
                    client->read_pos = 0;
                    break;
                }
                memcpy(frame_copy, client->read_buffer + 4, frame_size);
                /* Determine if this is server mode or client mode */
                if (transport->is_server) {
                    /* Server mode: pass client context and server context */
                    transport->recv_cb(frame_copy, frame_size, client, transport->callback_ctx);
                } else {
                    /* Client mode: pass NULL for client context (not needed) */
                    transport->recv_cb(frame_copy, frame_size, NULL, transport->callback_ctx);
                }
                
                /* Always free the frame copy after callback returns
                 * This ensures cleanup even if callback forgets to free it */
                uvrpc_free(frame_copy);
            }
            /* Remove processed frame from buffer */
            size_t remaining = client->read_pos - total_size;
            if (remaining > 0 && remaining < sizeof(client->read_buffer)) {
                memmove(client->read_buffer, client->read_buffer + total_size, remaining);
            }
            client->read_pos = remaining;
        }
    }
    uvrpc_free(buf->base);
}
References uvbus_transport::callback_ctx, uvbus_transport::error_cb, uvbus_transport::is_server, uvbus_tcp_client::parent_transport, uvbus_tcp_client::read_buffer, uvbus_tcp_client::read_pos, uvbus_transport::recv_cb, UVBUS_ERROR_IO, UVBUS_ERROR_NO_MEMORY, uvrpc_alloc(), and uvrpc_free().
Referenced by on_client_connect(), and on_server_connection().
on_server_close()
static void on_server_close (uv_handle_t * handle) [static]
Definition at line 310 of file uvbus_transport_tcp.c.
                                                 {
    uvbus_tcp_server_t* server = (uvbus_tcp_server_t*)handle->data;
    if (!server) return;
    
    if (ref_dec(&server->ref_count) == 0) {
        /* Free resources when ref count reaches 0 */
        if (server->host) {
            uvrpc_free(server->host);
        }
        if (server->clients) {
            uvrpc_free(server->clients);
        }
        uvrpc_free(server);
    }
}
References uvbus_tcp_server::clients, uvbus_tcp_server::host, uvbus_tcp_server::ref_count, ref_dec(), and uvrpc_free().
Referenced by tcp_disconnect().
on_server_connection()
static void on_server_connection (uv_stream_t * server, int status) [static]
Definition at line 224 of file uvbus_transport_tcp.c.
                                                                  {
    if (!server) {
        fprintf(stderr, "[ERROR] server is NULL in on_server_connection\n");
        return;
    }
    
    uvbus_transport_t* transport = (uvbus_transport_t*)server->data;
    if (!transport) {
        fprintf(stderr, "[ERROR] transport is NULL in on_server_connection\n");
        return;
    }
    
    if (status < 0) {
        if (transport->error_cb) {
            transport->error_cb(UVBUS_ERROR_IO, uv_strerror(status), transport->callback_ctx);
        }
        return;
    }
    
    uvbus_tcp_server_t* tcp_server = (uvbus_tcp_server_t*)transport->impl.tcp_server;
    if (!tcp_server) {
        fprintf(stderr, "[ERROR] tcp_server is NULL in on_server_connection\n");
        return;
    }
    
    /* Create new client connection */
    uvbus_tcp_client_t* client = (uvbus_tcp_client_t*)uvrpc_alloc(sizeof(uvbus_tcp_client_t));
    if (!client) {
        return;
    }
    
    memset(client, 0, sizeof(uvbus_tcp_client_t));
    
    /* Initialize TCP handle */
    if (!transport->loop) {
        fprintf(stderr, "[ERROR] transport->loop is NULL in on_server_connection\n");
        uvrpc_free(client);
        return;
    }
    
    uv_tcp_init(transport->loop, &client->tcp_handle);
    client->tcp_handle.data = client;
    
    /* Optimize socket buffers for accepted connections */
    uv_tcp_nodelay(&client->tcp_handle, 1); /* Disable Nagle algorithm */
    /* Note: Default socket buffer sizes are used, auto-tuned by the OS */
    client->tcp_handle.data = client;
    
    /* Accept connection */
    if (uv_accept(server, (uv_stream_t*)&client->tcp_handle) == 0) {
        /* Add to client list */
        if (tcp_server->client_count >= tcp_server->client_capacity) {
            tcp_server->client_capacity *= 2;
            tcp_server->clients = (uvbus_tcp_client_t**)uvrpc_realloc(
                tcp_server->clients,
                sizeof(uvbus_tcp_client_t*) * tcp_server->client_capacity
            );
        }
        
        tcp_server->clients[tcp_server->client_count++] = client;
        
        /* Set parent reference */
        client->parent_transport = transport;
        
        /* Start reading */
        uv_read_start((uv_stream_t*)&client->tcp_handle, on_client_alloc, on_client_read);
    } else {
        uv_close((uv_handle_t*)&client->tcp_handle, NULL);
        uvrpc_free(client);
    }
}
References uvbus_transport::callback_ctx, uvbus_tcp_server::client_capacity, uvbus_tcp_server::client_count, uvbus_tcp_server::clients, uvbus_transport::error_cb, uvbus_transport::impl, uvbus_transport::loop, on_client_alloc(), on_client_read(), uvbus_tcp_client::parent_transport, uvbus_tcp_client::tcp_handle, uvbus_transport::tcp_server, UVBUS_ERROR_IO, uvrpc_alloc(), uvrpc_free(), and uvrpc_realloc().
Referenced by tcp_listen().
on_write()
static void on_write (uv_write_t * req, int status) [static]
Definition at line 386 of file uvbus_transport_tcp.c.
                                                  {
    uvrpc_free(req->data);
    uvrpc_free(req);
}
References uvrpc_free().
Referenced by tcp_send(), and tcp_send_to().
parse_tcp_address()
static int parse_tcp_address (const char * address, char ** host, int * port) [static]
Definition at line 77 of file uvbus_transport_tcp.c.
                                                                          {
    if (!address || !host || !port) {
        return -1;
    }
    
    /* Skip protocol prefix */
    const char* addr_start = address;
    if (strncmp(address, "tcp://", 6) == 0) {
        addr_start += 6;
    }
    
    /* Find port separator */
    const char* colon = strrchr(addr_start, ':');
    if (!colon) {
        return -1;
    }
    
    /* Extract host */
    size_t host_len = colon - addr_start;
    *host = (char*)uvrpc_alloc(host_len + 1);
    if (!*host) {
        return -1;
    }
    memcpy(*host, addr_start, host_len);
    (*host)[host_len] = '\0';
    
    /* Extract port */
    *port = atoi(colon + 1);
    
    return 0;
}
References uvrpc_alloc().
Referenced by tcp_connect(), and tcp_listen().
ref_dec()
static int ref_dec (int * ref_count) [static]
Definition at line 72 of file uvbus_transport_tcp.c.
                                   {
    return __sync_sub_and_fetch(ref_count, 1);
}
Referenced by on_client_close(), on_server_close(), and tcp_disconnect().
ref_inc()
static int ref_inc (int * ref_count) [static]
Definition at line 68 of file uvbus_transport_tcp.c.
                                   {
    return __sync_add_and_fetch(ref_count, 1);
}
ref_init()
static void ref_init (int * ref_count) [static]
Definition at line 64 of file uvbus_transport_tcp.c.
                                     {
    *ref_count = 1;
}
Referenced by tcp_connect(), and tcp_listen().
tcp_connect()
static int tcp_connect (void * impl_ptr, const char * address) [static]
Definition at line 481 of file uvbus_transport_tcp.c.
                                                            {
    uvbus_transport_t* transport = (uvbus_transport_t*)impl_ptr;
    if (!transport) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    if (transport->is_server) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    /* Parse address */
    char* host = NULL;
    int port = 0;
    if (parse_tcp_address(address, &host, &port) != 0) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    /* Create client */
    uvbus_tcp_client_t* client = (uvbus_tcp_client_t*)uvrpc_alloc(sizeof(uvbus_tcp_client_t));
    if (!client) {
        uvrpc_free(host);
        return UVBUS_ERROR_NO_MEMORY;
    }
    
    memset(client, 0, sizeof(uvbus_tcp_client_t));
    client->host = host;
    client->port = port;
    client->parent_transport = transport;
    ref_init(&client->ref_count);
    
    /* Initialize TCP handle */
    uv_tcp_init(transport->loop, &client->tcp_handle);
    client->tcp_handle.data = client; /* Set to client so on_client_read can find it */
    
    /* Optimize socket buffers for better memory usage */
    uv_tcp_nodelay(&client->tcp_handle, 1); /* Disable Nagle algorithm for low latency */
    /* Note: We use default socket buffer sizes which are auto-tuned by the OS */
    
    /* Set up server address */
    struct sockaddr_in addr;
    uv_ip4_addr(host, port, &addr);
    
    /* Connect */
    transport->impl.tcp_client = (void*)client;
    client->connect_req.data = transport;
    
    uv_tcp_connect(&client->connect_req, &client->tcp_handle,
                   (const struct sockaddr*)&addr, on_client_connect);
    
    return UVBUS_OK;
}
References uvbus_tcp_client::connect_req, uvbus_tcp_client::host, uvbus_transport::impl, uvbus_transport::is_server, uvbus_transport::loop, on_client_connect(), uvbus_tcp_client::parent_transport, parse_tcp_address(), uvbus_tcp_client::port, uvbus_tcp_client::ref_count, ref_init(), uvbus_transport::tcp_client, uvbus_tcp_client::tcp_handle, UVBUS_ERROR_INVALID_PARAM, UVBUS_ERROR_NO_MEMORY, UVBUS_OK, uvrpc_alloc(), and uvrpc_free().
tcp_disconnect()
static void tcp_disconnect (void * impl_ptr) [static]
Definition at line 534 of file uvbus_transport_tcp.c.
                                           {
    uvbus_transport_t* transport = (uvbus_transport_t*)impl_ptr;
    if (!transport) {
        return;
    }
    
    if (transport->is_server && transport->impl.tcp_server) {
        uvbus_tcp_server_t* server = (uvbus_tcp_server_t*)transport->impl.tcp_server;
        /* Close all client connections */
        for (int i = 0; i < server->client_count; i++) {
            if (server->clients[i]) {
                ref_dec(&server->clients[i]->ref_count);
                uv_close((uv_handle_t*)&server->clients[i]->tcp_handle, on_client_close);
            }
        }
        uvrpc_free(server->clients);
        server->clients = NULL;
        server->client_count = 0;
        
        /* Close listen handle */
        ref_dec(&server->ref_count);
        uv_close((uv_handle_t*)&server->listen_handle, on_server_close);
        
        transport->impl.tcp_server = NULL;
    } else if (!transport->is_server && transport->impl.tcp_client) {
        uvbus_tcp_client_t* client = (uvbus_tcp_client_t*)transport->impl.tcp_client;
        /* Close client connection */
        ref_dec(&client->ref_count);
        uv_close((uv_handle_t*)&client->tcp_handle, on_client_close);
        
        transport->impl.tcp_client = NULL;
    }
    
    transport->is_connected = 0;
}
References uvbus_tcp_server::client_count, uvbus_tcp_server::clients, uvbus_transport::impl, uvbus_transport::is_connected, uvbus_transport::is_server, uvbus_tcp_server::listen_handle, on_client_close(), on_server_close(), uvbus_tcp_client::ref_count, uvbus_tcp_server::ref_count, ref_dec(), uvbus_transport::tcp_client, uvbus_tcp_client::tcp_handle, uvbus_transport::tcp_server, and uvrpc_free().
Referenced by tcp_free().
tcp_free()
static void tcp_free (void * impl_ptr) [static]
Definition at line 693 of file uvbus_transport_tcp.c.
                                     {
    uvbus_transport_t* transport = (uvbus_transport_t*)impl_ptr;
    if (!transport) {
        return;
    }
    
    tcp_disconnect(transport);
    
    if (transport->address) {
        uvrpc_free(transport->address);
    }
    
    uvrpc_free(transport);
}
References uvbus_transport::address, tcp_disconnect(), and uvrpc_free().
tcp_listen()
static int tcp_listen (void * impl_ptr, const char * address) [static]
Definition at line 410 of file uvbus_transport_tcp.c.
                                                           {
    uvbus_transport_t* transport = (uvbus_transport_t*)impl_ptr;
    if (!transport) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    if (!transport->is_server) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    /* Parse address */
    char* host = NULL;
    int port = 0;
    if (parse_tcp_address(address, &host, &port) != 0) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    /* Create server */
    uvbus_tcp_server_t* server = (uvbus_tcp_server_t*)uvrpc_alloc(sizeof(uvbus_tcp_server_t));
    if (!server) {
        uvrpc_free(host);
        return UVBUS_ERROR_NO_MEMORY;
    }
    
    memset(server, 0, sizeof(uvbus_tcp_server_t));
    server->host = host;
    server->port = port;
    server->parent_transport = transport;
    ref_init(&server->ref_count);
    server->clients = (uvbus_tcp_client_t**)uvrpc_alloc(sizeof(uvbus_tcp_client_t*) * UVBUS_INITIAL_CLIENT_CAPACITY);
    server->client_capacity = UVBUS_INITIAL_CLIENT_CAPACITY;
    server->client_count = 0;
    
    /* Initialize TCP handle */
    uv_tcp_init(transport->loop, &server->listen_handle);
    server->listen_handle.data = transport;
    
    /* Bind to address */
    struct sockaddr_in addr;
    uv_ip4_addr(host, port, &addr);
    
    if (uv_tcp_bind(&server->listen_handle, (const struct sockaddr*)&addr, 0) != 0) {
        uv_close((uv_handle_t*)&server->listen_handle, NULL);
        uvrpc_free(server->host);
        uvrpc_free(server->clients);
        uvrpc_free(server);
        return UVBUS_ERROR_IO;
    }
    
    /* Listen */
    if (uv_listen((uv_stream_t*)&server->listen_handle, UVBUS_BACKLOG, on_server_connection) != 0) {
        uv_close((uv_handle_t*)&server->listen_handle, NULL);
        uvrpc_free(server->host);
        uvrpc_free(server->clients);
        uvrpc_free(server);
        return UVBUS_ERROR_IO;
    }
    
    server->is_listening = 1;
    transport->is_connected = 1;
    transport->impl.tcp_server = (void*)server;
    
    /* Set bus as active - server is ready to accept connections */
    if (transport->parent_bus) {
        transport->parent_bus->is_active = 1;
    }
    
    return UVBUS_OK;
}
References uvbus_tcp_server::client_capacity, uvbus_tcp_server::client_count, uvbus_tcp_server::clients, uvbus_tcp_server::host, uvbus_transport::impl, uvbus::is_active, uvbus_transport::is_connected, uvbus_tcp_server::is_listening, uvbus_transport::is_server, uvbus_tcp_server::listen_handle, uvbus_transport::loop, on_server_connection(), uvbus_transport::parent_bus, uvbus_tcp_server::parent_transport, parse_tcp_address(), uvbus_tcp_server::port, uvbus_tcp_server::ref_count, ref_init(), uvbus_transport::tcp_server, UVBUS_ERROR_INVALID_PARAM, UVBUS_ERROR_IO, UVBUS_ERROR_NO_MEMORY, UVBUS_OK, uvrpc_alloc(), and uvrpc_free().
tcp_send()
static int tcp_send (void * impl_ptr, const uint8_t * data, size_t size) [static]
Definition at line 571 of file uvbus_transport_tcp.c.
                                                                      {
    uvbus_transport_t* transport = (uvbus_transport_t*)impl_ptr;
    if (!transport) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    if (!transport->is_connected) {
        return UVBUS_ERROR_NOT_CONNECTED;
    }
    /* Allocate buffer with 4-byte frame length prefix */
    size_t total_size = 4 + size;
    uint8_t* frame_data = (uint8_t*)uvrpc_alloc(total_size);
    if (!frame_data) {
        return UVBUS_ERROR_NO_MEMORY;
    }
    /* Write frame length in big-endian format */
    frame_data[0] = (size >> 24) & 0xFF;
    frame_data[1] = (size >> 16) & 0xFF;
    frame_data[2] = (size >> 8) & 0xFF;
    frame_data[3] = size & 0xFF;
    /* Copy payload data */
    memcpy(frame_data + 4, data, size);
    if (transport->is_server) {
        uvbus_tcp_server_t* server = (uvbus_tcp_server_t*)transport->impl.tcp_server;
        /* Broadcast to all clients */
        for (int i = 0; i < server->client_count; i++) {
            uv_write_t* req = (uv_write_t*)uvrpc_alloc(sizeof(uv_write_t));
            if (!req) {
                continue;
            }
            /* Copy frame data for this write */
            uint8_t* data_copy = (uint8_t*)uvrpc_alloc(total_size);
            if (!data_copy) {
                uvrpc_free(req);
                continue;
            }
            memcpy(data_copy, frame_data, total_size);
            uv_buf_t buf = uv_buf_init((char*)data_copy, total_size);
            req->data = data_copy;
            uv_write(req, (uv_stream_t*)&server->clients[i]->tcp_handle, &buf, 1, on_write);
        }
    } else {
        uvbus_tcp_client_t* client = (uvbus_tcp_client_t*)transport->impl.tcp_client;
        /* Send to server */
        uv_write_t* req = (uv_write_t*)uvrpc_alloc(sizeof(uv_write_t));
        if (!req) {
            uvrpc_free(frame_data);
            return UVBUS_ERROR_NO_MEMORY;
        }
        uv_buf_t buf = uv_buf_init((char*)frame_data, total_size);
        req->data = frame_data;
        if (uv_write(req, (uv_stream_t*)&client->tcp_handle, &buf, 1, on_write) != 0) {
            uvrpc_free(frame_data);
            uvrpc_free(req);
            return UVBUS_ERROR_IO;
        }
    }
    /* Note: frame_data is now owned by the write request, don't free it here */
    return UVBUS_OK;
}
References uvbus_tcp_server::client_count, uvbus_tcp_server::clients, uvbus_transport::impl, uvbus_transport::is_connected, uvbus_transport::is_server, on_write(), uvbus_transport::tcp_client, uvbus_tcp_client::tcp_handle, uvbus_transport::tcp_server, UVBUS_ERROR_INVALID_PARAM, UVBUS_ERROR_IO, UVBUS_ERROR_NO_MEMORY, UVBUS_ERROR_NOT_CONNECTED, UVBUS_OK, uvrpc_alloc(), and uvrpc_free().
tcp_send_to()
static int tcp_send_to (void * impl_ptr, const uint8_t * data, size_t size, void * target) [static]
Definition at line 643 of file uvbus_transport_tcp.c.
                                                                                       {
    uvbus_transport_t* transport = (uvbus_transport_t*)impl_ptr;
    if (!transport) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    if (!transport->is_server) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    uvbus_tcp_client_t* client = (uvbus_tcp_client_t*)target;
    if (!client) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    /* Allocate buffer with 4-byte frame length prefix */
    size_t total_size = 4 + size;
    uint8_t* frame_data = (uint8_t*)uvrpc_alloc(total_size);
    if (!frame_data) {
        return UVBUS_ERROR_NO_MEMORY;
    }
    /* Write frame length in big-endian format */
    frame_data[0] = (size >> 24) & 0xFF;
    frame_data[1] = (size >> 16) & 0xFF;
    frame_data[2] = (size >> 8) & 0xFF;
    frame_data[3] = size & 0xFF;
    /* Copy payload data */
    memcpy(frame_data + 4, data, size);
    uv_write_t* req = (uv_write_t*)uvrpc_alloc(sizeof(uv_write_t));
    if (!req) {
        uvrpc_free(frame_data);
        return UVBUS_ERROR_NO_MEMORY;
    }
    uv_buf_t buf = uv_buf_init((char*)frame_data, total_size);
    req->data = frame_data;
    if (uv_write(req, (uv_stream_t*)&client->tcp_handle, &buf, 1, on_write) != 0) {
        uvrpc_free(frame_data);
        uvrpc_free(req);
        return UVBUS_ERROR_IO;
    }
    return UVBUS_OK;
}
References uvbus_transport::is_server, on_write(), uvbus_tcp_client::tcp_handle, UVBUS_ERROR_INVALID_PARAM, UVBUS_ERROR_IO, UVBUS_ERROR_NO_MEMORY, UVBUS_OK, uvrpc_alloc(), and uvrpc_free().
Variable Documentation
tcp_vtable
const uvbus_transport_vtable_t tcp_vtable [static]
Initial value:
= {
    .listen = tcp_listen,
    .connect = tcp_connect,
    .disconnect = tcp_disconnect,
    .send = tcp_send,
    .send_to = tcp_send_to,
    .free = tcp_free
}
Definition at line 400 of file uvbus_transport_tcp.c.
Referenced by create_tcp_transport().