include/uvbus.h File Reference
UVBus - Universal Bus for libuv-based Communication.
Classes
struct uvbus
struct uvbus_config
struct uvbus_transport
struct uvbus_transport_vtable
Typedefs
typedef void(* uvbus_close_callback_t) (void *ctx)
Close callback type.
typedef struct uvbus_config uvbus_config_t
typedef void(* uvbus_connect_callback_t) (uvbus_error_t status, void *ctx)
Connect callback type.
typedef void(* uvbus_error_callback_t) (uvbus_error_t error_code, const char *error_msg, void *ctx)
Error callback type.
typedef void(* uvbus_recv_callback_t) (const uint8_t *data, size_t size, void *client_ctx, void *server_ctx)
Receive callback type.
typedef struct uvbus uvbus_t
typedef struct uvbus_transport uvbus_transport_t
typedef struct uvbus_transport_vtable uvbus_transport_vtable_t
Enumerations
enum uvbus_error_t {
UVBUS_OK = 0
, UVBUS_ERROR = -1
, UVBUS_ERROR_INVALID_PARAM = -2
, UVBUS_ERROR_NO_MEMORY = -3
,
UVBUS_ERROR_NOT_CONNECTED = -4
, UVBUS_ERROR_TIMEOUT = -5
, UVBUS_ERROR_IO = -6
, UVBUS_ERROR_ALREADY_EXISTS = -7
,
UVBUS_ERROR_NOT_FOUND = -8
, UVBUS_ERROR_NOT_IMPLEMENTED = -9
, UVBUS_ERROR_MAX
 }
UVBus error codes.
enum uvbus_transport_type_t { UVBUS_TRANSPORT_TCP = 0
, UVBUS_TRANSPORT_UDP = 1
, UVBUS_TRANSPORT_IPC = 2
, UVBUS_TRANSPORT_INPROC = 3
 }
UVBus transport types.
Functions
uvbus_transport_t * create_inproc_transport (uvbus_transport_type_t type, uv_loop_t *loop)
uvbus_transport_t * create_ipc_transport (uvbus_transport_type_t type, uv_loop_t *loop)
uvbus_transport_t * create_tcp_transport (uvbus_transport_type_t type, uv_loop_t *loop)
uvbus_transport_t * create_udp_transport (uvbus_transport_type_t type, uv_loop_t *loop)
uvbus_t * uvbus_client_new (uvbus_config_t *config)
uvbus_error_t uvbus_client_send (uvbus_t *bus, const uint8_t *data, size_t size)
void uvbus_config_free (uvbus_config_t *config)
uvbus_config_t * uvbus_config_new (void)
void uvbus_config_set_address (uvbus_config_t *config, const char *address)
void uvbus_config_set_close_callback (uvbus_config_t *config, uvbus_close_callback_t close_cb, void *ctx)
void uvbus_config_set_connect_callback (uvbus_config_t *config, uvbus_connect_callback_t connect_cb, void *ctx)
void uvbus_config_set_error_callback (uvbus_config_t *config, uvbus_error_callback_t error_cb, void *ctx)
void uvbus_config_set_loop (uvbus_config_t *config, uv_loop_t *loop)
void uvbus_config_set_recv_callback (uvbus_config_t *config, uvbus_recv_callback_t recv_cb, void *ctx)
void uvbus_config_set_timeout (uvbus_config_t *config, uint64_t timeout_ms)
void uvbus_config_set_timeout_enabled (uvbus_config_t *config, int enabled)
void uvbus_config_set_transport (uvbus_config_t *config, uvbus_transport_type_t transport)
uvbus_error_t uvbus_connect (uvbus_t *bus)
uvbus_error_t uvbus_connect_with_callback (uvbus_t *bus, uvbus_connect_callback_t callback, void *ctx)
void uvbus_disconnect (uvbus_t *bus)
void uvbus_free (uvbus_t *bus)
const char * uvbus_get_address (uvbus_t *bus)
uv_loop_t * uvbus_get_loop (uvbus_t *bus)
uvbus_transport_type_t uvbus_get_transport_type (uvbus_t *bus)
int uvbus_is_connected (uvbus_t *bus)
int uvbus_is_server (uvbus_t *bus)
uvbus_error_t uvbus_listen (uvbus_t *bus)
uvbus_error_t uvbus_send (uvbus_t *bus, const uint8_t *data, size_t size)
uvbus_error_t uvbus_send_to (uvbus_t *bus, const uint8_t *data, size_t size, void *client)
uvbus_t * uvbus_server_new (uvbus_config_t *config)
void uvbus_stop (uvbus_t *bus)
Detailed Description
UVBus - Universal Bus for libuv-based Communication.
A unified abstraction layer for various transport protocols (TCP, UDP, IPC, INPROC) Built on top of libuv event loop for non-blocking I/O.
Design Philosophy:
Zero-copy where possible
Single-threaded event loop
Minimal overhead
Protocol-agnostic API
Author
UVRPC Team
Date
2026
Version
1.0
Copyright
Copyright (c) 2026 @license MIT License
Definition in file uvbus.h.
Typedef Documentation
uvbus_close_callback_t
typedef void(* uvbus_close_callback_t) (void *ctx)
Close callback type.
Called when connection is closed.
Parameters
ctx User context
Definition at line 93 of file uvbus.h.
uvbus_config_t
typedef struct uvbus_config uvbus_config_t
Definition at line 108 of file uvbus.h.
uvbus_connect_callback_t
typedef void(* uvbus_connect_callback_t) (uvbus_error_t status, void *ctx)
Connect callback type.
Called when connection state changes.
Parameters
status Connection status
ctx User context
Definition at line 84 of file uvbus.h.
uvbus_error_callback_t
typedef void(* uvbus_error_callback_t) (uvbus_error_t error_code, const char *error_msg, void *ctx)
Error callback type.
Called when an error occurs.
Parameters
error_code Error code
error_msg Error message
ctx User context
Definition at line 104 of file uvbus.h.
uvbus_recv_callback_t
typedef void(* uvbus_recv_callback_t) (const uint8_t *data, size_t size, void *client_ctx, void *server_ctx)
Receive callback type.
Called when data is received.
Parameters
data Received data
size Data size
client_ctx Client context (for server)
server_ctx Server context
Definition at line 74 of file uvbus.h.
uvbus_t
typedef struct uvbus uvbus_t
Definition at line 107 of file uvbus.h.
uvbus_transport_t
typedef struct uvbus_transport uvbus_transport_t
Definition at line 109 of file uvbus.h.
uvbus_transport_vtable_t
typedef struct uvbus_transport_vtable uvbus_transport_vtable_t
Enumeration Type Documentation
uvbus_error_t
enum uvbus_error_t
UVBus error codes.
Error codes returned by UVBus API functions.
Enumerator
UVBUS_OK Operation successful.
UVBUS_ERROR General error.
UVBUS_ERROR_INVALID_PARAM Invalid parameter.
UVBUS_ERROR_NO_MEMORY Memory allocation failed.
UVBUS_ERROR_NOT_CONNECTED Not connected.
UVBUS_ERROR_TIMEOUT Operation timed out.
UVBUS_ERROR_IO I/O error.
UVBUS_ERROR_ALREADY_EXISTS Resource already exists.
UVBUS_ERROR_NOT_FOUND Resource not found.
UVBUS_ERROR_NOT_IMPLEMENTED Feature not implemented.
UVBUS_ERROR_MAX Maximum error code.
Definition at line 38 of file uvbus.h.
             {
    UVBUS_OK = 0,
    UVBUS_ERROR = -1,
    UVBUS_ERROR_INVALID_PARAM = -2,
    UVBUS_ERROR_NO_MEMORY = -3,
    UVBUS_ERROR_NOT_CONNECTED = -4,
    UVBUS_ERROR_TIMEOUT = -5,
    UVBUS_ERROR_IO = -6,
    UVBUS_ERROR_ALREADY_EXISTS = -7,
    UVBUS_ERROR_NOT_FOUND = -8,
    UVBUS_ERROR_NOT_IMPLEMENTED = -9,
    UVBUS_ERROR_MAX
} uvbus_error_t;
uvbus_transport_type_t
enum uvbus_transport_type_t
UVBus transport types.
Defines the available transport protocols.
Enumerator
UVBUS_TRANSPORT_TCP TCP transport.
UVBUS_TRANSPORT_UDP UDP transport.
UVBUS_TRANSPORT_IPC Unix domain socket (IPC)
UVBUS_TRANSPORT_INPROC In-process transport.
Definition at line 57 of file uvbus.h.
             {
    UVBUS_TRANSPORT_TCP = 0,
    UVBUS_TRANSPORT_UDP = 1,
    UVBUS_TRANSPORT_IPC = 2,
    UVBUS_TRANSPORT_INPROC = 3
} uvbus_transport_type_t;
Function Documentation
create_inproc_transport()
uvbus_transport_t * create_inproc_transport (uvbus_transport_type_t type, uv_loop_t * loop)
Definition at line 414 of file uvbus_transport_inproc.c.
                                                                                         {
    uvbus_transport_t* transport = (uvbus_transport_t*)uvrpc_alloc(sizeof(uvbus_transport_t));
    if (!transport) {
        return NULL;
    }
    
    memset(transport, 0, sizeof(uvbus_transport_t));
    transport->type = type;
    transport->loop = loop;
    transport->vtable = &inproc_vtable;
    
    return transport;
}
References inproc_vtable, uvbus_transport::loop, uvbus_transport::type, uvrpc_alloc(), and uvbus_transport::vtable.
create_ipc_transport()
uvbus_transport_t * create_ipc_transport (uvbus_transport_type_t type, uv_loop_t * loop)
Definition at line 494 of file uvbus_transport_ipc.c.
                                                                                      {
    uvbus_transport_t* transport = (uvbus_transport_t*)uvrpc_alloc(sizeof(uvbus_transport_t));
    if (!transport) {
        return NULL;
    }
    
    memset(transport, 0, sizeof(uvbus_transport_t));
    transport->type = type;
    transport->loop = loop;
    transport->vtable = &ipc_vtable;
    
    return transport;
}
References ipc_vtable, uvbus_transport::loop, uvbus_transport::type, uvrpc_alloc(), and uvbus_transport::vtable.
create_tcp_transport()
uvbus_transport_t * create_tcp_transport (uvbus_transport_type_t type, uv_loop_t * loop)
Definition at line 709 of file uvbus_transport_tcp.c.
                                                                                      {
    uvbus_transport_t* transport = (uvbus_transport_t*)uvrpc_alloc(sizeof(uvbus_transport_t));
    if (!transport) {
        return NULL;
    }
    
    memset(transport, 0, sizeof(uvbus_transport_t));
    transport->type = type;
    transport->loop = loop;
    transport->vtable = &tcp_vtable;
    
    return transport;
}
References uvbus_transport::loop, tcp_vtable, uvbus_transport::type, uvrpc_alloc(), and uvbus_transport::vtable.
create_udp_transport()
uvbus_transport_t * create_udp_transport (uvbus_transport_type_t type, uv_loop_t * loop)
Definition at line 431 of file uvbus_transport_udp.c.
                                                                                      {
    uvbus_transport_t* transport = (uvbus_transport_t*)uvrpc_alloc(sizeof(uvbus_transport_t));
    if (!transport) {
        return NULL;
    }
    
    memset(transport, 0, sizeof(uvbus_transport_t));
    transport->type = type;
    transport->loop = loop;
    transport->vtable = &udp_vtable;
    
    return transport;
}
References uvbus_transport::loop, uvbus_transport::type, udp_vtable, uvrpc_alloc(), and uvbus_transport::vtable.
uvbus_client_new()
uvbus_t * uvbus_client_new (uvbus_config_t * config)
Create UVBus client
Definition at line 158 of file uvbus.c.
                                                  {
    if (!config || !config->loop) {
        return NULL;
    }
    
    uvbus_t* bus = (uvbus_t*)uvrpc_alloc(sizeof(uvbus_t));
    if (!bus) {
        return NULL;
    }
    
    memset(bus, 0, sizeof(uvbus_t));
    bus->config = *config;
    bus->is_active = 0;
    
    /* Create transport */
    bus->transport = create_transport(config->transport, config->loop);
    if (!bus->transport) {
        uvrpc_free(bus);
        return NULL;
    }
    bus->transport->parent_bus = bus;
    bus->transport->is_server = 0;
    bus->transport->type = config->transport;
    bus->transport->loop = config->loop;
    
    if (config->address) {
        bus->transport->address = uvrpc_strdup(config->address);
    }
    
    /* Set callbacks */
    bus->transport->recv_cb = config->recv_cb;
    bus->transport->connect_cb = config->connect_cb;
    bus->transport->close_cb = config->close_cb;
    bus->transport->error_cb = config->error_cb;
    bus->transport->callback_ctx = config->callback_ctx;
    
    return bus;
}
References uvbus_config::address, uvbus_transport::address, uvbus_config::callback_ctx, uvbus_transport::callback_ctx, uvbus_config::close_cb, uvbus_transport::close_cb, uvbus::config, uvbus_config::connect_cb, uvbus_transport::connect_cb, create_transport(), uvbus_config::error_cb, uvbus_transport::error_cb, uvbus::is_active, uvbus_transport::is_server, uvbus_config::loop, uvbus_transport::loop, uvbus_transport::parent_bus, uvbus_config::recv_cb, uvbus_transport::recv_cb, uvbus_config::transport, uvbus::transport, uvbus_transport::type, uvrpc_alloc(), uvrpc_free(), and uvrpc_strdup().
Referenced by uvrpc_client_create(), and uvrpc_subscriber_create().
uvbus_client_send()
uvbus_error_t uvbus_client_send (uvbus_t * bus, const uint8_t * data, size_t size)
Send data to server (client only)
Definition at line 309 of file uvbus.c.
                                                                                {
    if (!bus || !bus->transport || !bus->transport->vtable) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    if (!bus->transport->is_connected) {
        return UVBUS_ERROR_NOT_CONNECTED;
    }
    
    if (bus->transport->vtable->send) {
        return bus->transport->vtable->send(bus->transport, data, size);
    }
    
    return UVBUS_ERROR;
}
References uvbus_transport::is_connected, uvbus_transport_vtable::send, uvbus::transport, UVBUS_ERROR, UVBUS_ERROR_INVALID_PARAM, UVBUS_ERROR_NOT_CONNECTED, and uvbus_transport::vtable.
Referenced by uvrpc_publisher_publish().
uvbus_config_free()
void uvbus_config_free (uvbus_config_t * config)
Free UVBus configuration
Definition at line 39 of file uvbus.c.
                                               {
    if (config) {
        uvrpc_free(config);
    }
}
References uvrpc_free().
Referenced by uvrpc_client_create(), uvrpc_publisher_create(), uvrpc_server_create(), and uvrpc_subscriber_create().
uvbus_config_new()
uvbus_config_t * uvbus_config_new (void)
Create UVBus configuration
Definition at line 26 of file uvbus.c.
                                       {
    uvbus_config_t* config = (uvbus_config_t*)uvrpc_alloc(sizeof(uvbus_config_t));
    if (!config) {
        return NULL;
    }
    
    memset(config, 0, sizeof(uvbus_config_t));
    config->timeout_ms = 30000; /* Default 30 seconds */
    config->enable_timeout = 0;
    
    return config;
}
References uvbus_config::enable_timeout, uvbus_config::timeout_ms, and uvrpc_alloc().
Referenced by uvrpc_client_create(), uvrpc_publisher_create(), uvrpc_server_create(), and uvrpc_subscriber_create().
uvbus_config_set_address()
void uvbus_config_set_address (uvbus_config_t * config, const char * address)
Set address
Definition at line 57 of file uvbus.c.
                                                                           {
    if (config) {
        config->address = address;
    }
}
References uvbus_config::address.
Referenced by uvrpc_client_create(), uvrpc_publisher_create(), uvrpc_server_create(), and uvrpc_subscriber_create().
uvbus_config_set_close_callback()
void uvbus_config_set_close_callback (uvbus_config_t * config, uvbus_close_callback_t close_cb, void * ctx)
Set close callback
Definition at line 77 of file uvbus.c.
                                                                                                         {
    if (config) {
        config->close_cb = close_cb;
        config->callback_ctx = ctx;
    }
}
References uvbus_config::callback_ctx, and uvbus_config::close_cb.
uvbus_config_set_connect_callback()
void uvbus_config_set_connect_callback (uvbus_config_t * config, uvbus_connect_callback_t connect_cb, void * ctx)
Set connect callback
Definition at line 70 of file uvbus.c.
                                                                                                               {
    if (config) {
        config->connect_cb = connect_cb;
        config->callback_ctx = ctx;
    }
}
References uvbus_config::callback_ctx, and uvbus_config::connect_cb.
Referenced by uvrpc_client_create(), and uvrpc_subscriber_create().
uvbus_config_set_error_callback()
void uvbus_config_set_error_callback (uvbus_config_t * config, uvbus_error_callback_t error_cb, void * ctx)
Set error callback
Definition at line 84 of file uvbus.c.
                                                                                                         {
    if (config) {
        config->error_cb = error_cb;
        config->callback_ctx = ctx;
    }
}
References uvbus_config::callback_ctx, and uvbus_config::error_cb.
uvbus_config_set_loop()
void uvbus_config_set_loop (uvbus_config_t * config, uv_loop_t * loop)
Set event loop
Definition at line 45 of file uvbus.c.
                                                                    {
    if (config) {
        config->loop = loop;
    }
}
References uvbus_config::loop.
Referenced by uvrpc_client_create(), uvrpc_publisher_create(), uvrpc_server_create(), and uvrpc_subscriber_create().
uvbus_config_set_recv_callback()
void uvbus_config_set_recv_callback (uvbus_config_t * config, uvbus_recv_callback_t recv_cb, void * ctx)
Set receive callback
Definition at line 63 of file uvbus.c.
                                                                                                      {
    if (config) {
        config->recv_cb = recv_cb;
        config->callback_ctx = ctx;
    }
}
References uvbus_config::callback_ctx, and uvbus_config::recv_cb.
Referenced by uvrpc_client_create(), uvrpc_server_create(), and uvrpc_subscriber_create().
uvbus_config_set_timeout()
void uvbus_config_set_timeout (uvbus_config_t * config, uint64_t timeout_ms)
Set timeout
Definition at line 91 of file uvbus.c.
                                                                           {
    if (config) {
        config->timeout_ms = timeout_ms;
    }
}
References uvbus_config::timeout_ms.
uvbus_config_set_timeout_enabled()
void uvbus_config_set_timeout_enabled (uvbus_config_t * config, int enabled)
Enable/disable timeout
Definition at line 97 of file uvbus.c.
                                                                           {
    if (config) {
        config->enable_timeout = enabled;
    }
}
References uvbus_config::enable_timeout.
uvbus_config_set_transport()
void uvbus_config_set_transport (uvbus_config_t * config, uvbus_transport_type_t transport)
Set transport type
Definition at line 51 of file uvbus.c.
                                                                                          {
    if (config) {
        config->transport = transport;
    }
}
References uvbus_config::transport.
Referenced by uvrpc_client_create(), uvrpc_publisher_create(), uvrpc_server_create(), and uvrpc_subscriber_create().
uvbus_connect()
uvbus_error_t uvbus_connect (uvbus_t * bus)
Connect to server
Definition at line 258 of file uvbus.c.
                                          {
    if (!bus || !bus->transport || !bus->transport->vtable) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    if (bus->transport->is_server) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    if (bus->transport->vtable->connect) {
        /* Note: Connection is asynchronous, is_connected will be set in the callback */
        return bus->transport->vtable->connect(bus->transport, bus->transport->address);
    }
    
    return UVBUS_ERROR;
}
References uvbus_transport::address, uvbus_transport_vtable::connect, uvbus_transport::is_server, uvbus::transport, UVBUS_ERROR, UVBUS_ERROR_INVALID_PARAM, and uvbus_transport::vtable.
Referenced by uvrpc_client_connect(), uvrpc_client_connect_with_callback(), and uvrpc_subscriber_connect().
uvbus_connect_with_callback()
uvbus_error_t uvbus_connect_with_callback (uvbus_t * bus, uvbus_connect_callback_t callback, void * ctx)
Connect to server with callback
Definition at line 275 of file uvbus.c.
                                                                                                      {
    if (!bus || !bus->transport || !bus->transport->vtable) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    if (bus->transport->is_server) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    /* Override callback */
    bus->transport->connect_cb = callback;
    bus->transport->callback_ctx = ctx;
    
    if (bus->transport->vtable->connect) {
        /* Note: Connection is asynchronous, is_active will be set in the callback */
        return bus->transport->vtable->connect(bus->transport, bus->transport->address);
    }
    
    return UVBUS_ERROR;
}
References uvbus_transport::address, uvbus_transport::callback_ctx, uvbus_transport_vtable::connect, uvbus_transport::connect_cb, uvbus_transport::is_server, uvbus::transport, UVBUS_ERROR, UVBUS_ERROR_INVALID_PARAM, and uvbus_transport::vtable.
uvbus_disconnect()
void uvbus_disconnect (uvbus_t * bus)
Disconnect from server
Definition at line 296 of file uvbus.c.
                                    {
    if (!bus || !bus->transport) {
        return;
    }
    
    bus->is_active = 0;
    bus->transport->is_connected = 0;
    
    if (bus->transport->vtable && bus->transport->vtable->disconnect) {
        bus->transport->vtable->disconnect(bus->transport);
    }
}
References uvbus_transport_vtable::disconnect, uvbus::is_active, uvbus_transport::is_connected, uvbus::transport, and uvbus_transport::vtable.
Referenced by uvbus_free(), uvrpc_client_disconnect(), and uvrpc_subscriber_disconnect().
uvbus_free()
void uvbus_free (uvbus_t * bus)
Free UVBus
Definition at line 345 of file uvbus.c.
                              {
    if (!bus) {
        return;
    }
    
    /* Stop if active */
    if (bus->is_active) {
        if (bus->transport && bus->transport->is_server) {
            uvbus_stop(bus);
        } else {
            uvbus_disconnect(bus);
        }
    }
    
    /* Free transport */
    if (bus->transport) {
        if (bus->transport->vtable && bus->transport->vtable->free) {
            bus->transport->vtable->free(bus->transport);
        } else {
            if (bus->transport->address) {
                uvrpc_free(bus->transport->address);
            }
            uvrpc_free(bus->transport);
        }
    }
    
    uvrpc_free(bus);
}
References uvbus_transport::address, uvbus_transport_vtable::free, uvbus::is_active, uvbus_transport::is_server, uvbus::transport, uvbus_disconnect(), uvbus_stop(), uvrpc_free(), and uvbus_transport::vtable.
Referenced by uvrpc_client_free(), uvrpc_publisher_free(), uvrpc_server_free(), and uvrpc_subscriber_free().
uvbus_get_address()
const char * uvbus_get_address (uvbus_t * bus)
Get address
Definition at line 333 of file uvbus.c.
                                            {
    return bus ? bus->transport->address : NULL;
}
References uvbus_transport::address, and uvbus::transport.
uvbus_get_loop()
uv_loop_t * uvbus_get_loop (uvbus_t * bus)
Get event loop
Definition at line 325 of file uvbus.c.
                                        {
    return bus ? bus->transport->loop : NULL;
}
References uvbus_transport::loop, and uvbus::transport.
uvbus_get_transport_type()
uvbus_transport_type_t uvbus_get_transport_type (uvbus_t * bus)
Get transport type
Definition at line 329 of file uvbus.c.
                                                              {
    return bus ? bus->transport->type : UVBUS_TRANSPORT_TCP;
}
References uvbus::transport, uvbus_transport::type, and UVBUS_TRANSPORT_TCP.
uvbus_is_connected()
int uvbus_is_connected (uvbus_t * bus)
Check if connected
Definition at line 337 of file uvbus.c.
                                     {
    return bus ? bus->transport->is_connected : 0;
}
References uvbus_transport::is_connected, and uvbus::transport.
uvbus_is_server()
int uvbus_is_server (uvbus_t * bus)
Check if server
Definition at line 341 of file uvbus.c.
                                  {
    return bus ? bus->transport->is_server : 0;
}
References uvbus_transport::is_server, and uvbus::transport.
uvbus_listen()
uvbus_error_t uvbus_listen (uvbus_t * bus)
Start listening
Definition at line 198 of file uvbus.c.
                                         {
    if (!bus || !bus->transport || !bus->transport->vtable) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    if (!bus->transport->is_server) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    if (bus->transport->vtable->listen) {
        uvbus_error_t result = bus->transport->vtable->listen(bus->transport, bus->transport->address);
        if (result == UVBUS_OK) {
            bus->is_active = 1;
        }
        return result;
    }
    
    return UVBUS_ERROR;
}
References uvbus_transport::address, uvbus::is_active, uvbus_transport::is_server, uvbus_transport_vtable::listen, uvbus::transport, UVBUS_ERROR, UVBUS_ERROR_INVALID_PARAM, UVBUS_OK, and uvbus_transport::vtable.
Referenced by uvrpc_publisher_start(), and uvrpc_server_start().
uvbus_send()
uvbus_error_t uvbus_send (uvbus_t * bus, const uint8_t * data, size_t size)
Send data to all connected clients (server only)
Definition at line 226 of file uvbus.c.
                                                                         {
    if (!bus || !bus->transport || !bus->transport->vtable) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    if (!bus->is_active) {
        return UVBUS_ERROR_NOT_CONNECTED;
    }
    if (bus->transport->vtable->send) {
        return bus->transport->vtable->send(bus->transport, data, size);
    }
    return UVBUS_ERROR;
}
References uvbus::is_active, uvbus_transport_vtable::send, uvbus::transport, UVBUS_ERROR, UVBUS_ERROR_INVALID_PARAM, UVBUS_ERROR_NOT_CONNECTED, and uvbus_transport::vtable.
Referenced by uvrpc_client_call_batch(), and uvrpc_client_call_no_retry_internal().
uvbus_send_to()
uvbus_error_t uvbus_send_to (uvbus_t * bus, const uint8_t * data, size_t size, void * client)
Send data to specific client (server only)
Send data to specific client (server only) For request-response pattern, send response to the client that sent the request
Definition at line 242 of file uvbus.c.
                                                                                          {
    if (!bus || !bus->transport || !bus->transport->vtable) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    if (!bus->is_active) {
        return UVBUS_ERROR_NOT_CONNECTED;
    }
    
    if (bus->transport->vtable->send_to) {
        return bus->transport->vtable->send_to(bus->transport, data, size, client);
    }
    
    return UVBUS_ERROR;
}
References uvbus::is_active, uvbus_transport_vtable::send_to, uvbus::transport, UVBUS_ERROR, UVBUS_ERROR_INVALID_PARAM, UVBUS_ERROR_NOT_CONNECTED, and uvbus_transport::vtable.
Referenced by uvrpc_request_send_response(), uvrpc_response_send(), and uvrpc_response_send_error().
uvbus_server_new()
uvbus_t * uvbus_server_new (uvbus_config_t * config)
Create UVBus server
Definition at line 118 of file uvbus.c.
                                                  {
    if (!config || !config->loop) {
        return NULL;
    }
    
    uvbus_t* bus = (uvbus_t*)uvrpc_alloc(sizeof(uvbus_t));
    if (!bus) {
        return NULL;
    }
    
    memset(bus, 0, sizeof(uvbus_t));
    bus->config = *config;
    bus->is_active = 0;
    
    /* Create transport */
    bus->transport = create_transport(config->transport, config->loop);
    if (!bus->transport) {
        uvrpc_free(bus);
        return NULL;
    }
    bus->transport->parent_bus = bus;
    bus->transport->is_server = 1;
    bus->transport->type = config->transport;
    bus->transport->loop = config->loop;
    
    if (config->address) {
        bus->transport->address = uvrpc_strdup(config->address);
    }
    
    /* Set callbacks */
    bus->transport->recv_cb = config->recv_cb;
    bus->transport->connect_cb = config->connect_cb;
    bus->transport->close_cb = config->close_cb;
    bus->transport->error_cb = config->error_cb;
    bus->transport->callback_ctx = config->callback_ctx;
    
    return bus;
}
References uvbus_config::address, uvbus_transport::address, uvbus_config::callback_ctx, uvbus_transport::callback_ctx, uvbus_config::close_cb, uvbus_transport::close_cb, uvbus::config, uvbus_config::connect_cb, uvbus_transport::connect_cb, create_transport(), uvbus_config::error_cb, uvbus_transport::error_cb, uvbus::is_active, uvbus_transport::is_server, uvbus_config::loop, uvbus_transport::loop, uvbus_transport::parent_bus, uvbus_config::recv_cb, uvbus_transport::recv_cb, uvbus_config::transport, uvbus::transport, uvbus_transport::type, uvrpc_alloc(), uvrpc_free(), and uvrpc_strdup().
Referenced by uvrpc_publisher_create(), and uvrpc_server_create().
uvbus_stop()
void uvbus_stop (uvbus_t * bus)
Stop listening
Definition at line 218 of file uvbus.c.
                              {
    if (!bus) {
        return;
    }
    
    bus->is_active = 0;
}
References uvbus::is_active.
Referenced by uvbus_free().