src/uvbus_transport_ipc.c File Reference
Classes
struct uvbus_ipc_client
struct uvbus_ipc_server
Typedefs
typedef struct uvbus_ipc_client uvbus_ipc_client_t
typedef struct uvbus_ipc_server uvbus_ipc_server_t
Functions
uvbus_transport_t * create_ipc_transport (uvbus_transport_type_t type, uv_loop_t *loop)
static int ipc_connect (void *impl_ptr, const char *address)
static void ipc_disconnect (void *impl_ptr)
static void ipc_free (void *impl_ptr)
static int ipc_listen (void *impl_ptr, const char *address)
static int ipc_send (void *impl_ptr, const uint8_t *data, size_t size)
static int ipc_send_to (void *impl_ptr, const uint8_t *data, size_t size, void *target)
static void on_client_alloc (uv_handle_t *handle, size_t suggested_size, uv_buf_t *buf)
static void on_client_connect (uv_connect_t *req, int status)
static void on_client_read (uv_stream_t *stream, ssize_t nread, const uv_buf_t *buf)
static void on_server_connection (uv_stream_t *server, int status)
static void on_write (uv_write_t *req, int status)
static int parse_ipc_address (const char *address, char **socket_path)
Variables
static const uvbus_transport_vtable_t ipc_vtable
Typedef Documentation
uvbus_ipc_client_t
typedef struct uvbus_ipc_client uvbus_ipc_client_t
UVBus IPC Transport Implementation (Unix Domain Sockets)
Definition at line 12 of file uvbus_transport_ipc.c.
uvbus_ipc_server_t
typedef struct uvbus_ipc_server uvbus_ipc_server_t
Definition at line 13 of file uvbus_transport_ipc.c.
Function Documentation
create_ipc_transport()
uvbus_transport_t * create_ipc_transport (uvbus_transport_type_t type, uv_loop_t * loop)
Definition at line 494 of file uvbus_transport_ipc.c.
                                                                                      {
    uvbus_transport_t* transport = (uvbus_transport_t*)uvrpc_alloc(sizeof(uvbus_transport_t));
    if (!transport) {
        return NULL;
    }
    
    memset(transport, 0, sizeof(uvbus_transport_t));
    transport->type = type;
    transport->loop = loop;
    transport->vtable = &ipc_vtable;
    
    return transport;
}
References ipc_vtable, uvbus_transport::loop, uvbus_transport::type, uvrpc_alloc(), and uvbus_transport::vtable.
Referenced by create_transport().
ipc_connect()
static int ipc_connect (void * impl_ptr, const char * address) [static]
Definition at line 296 of file uvbus_transport_ipc.c.
                                                            {
    uvbus_transport_t* transport = (uvbus_transport_t*)impl_ptr;
    if (!transport) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    if (transport->is_server) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    /* Parse address */
    char* socket_path = NULL;
    if (parse_ipc_address(address, &socket_path) != 0) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    /* Create client */
    uvbus_ipc_client_t* client = (uvbus_ipc_client_t*)uvrpc_alloc(sizeof(uvbus_ipc_client_t));
    if (!client) {
        uvrpc_free(socket_path);
        return UVBUS_ERROR_NO_MEMORY;
    }
    
    memset(client, 0, sizeof(uvbus_ipc_client_t));
    client->socket_path = socket_path;
    client->parent_transport = transport;
    
    /* Initialize pipe handle */
    uv_pipe_init(transport->loop, &client->pipe_handle, 0);
    client->pipe_handle.data = client;
    
    /* Connect */
    transport->impl.ipc_client = (void*)client;
    client->connect_req.data = transport;
    
    uv_pipe_connect(&client->connect_req, &client->pipe_handle,
                    socket_path, on_client_connect);
    
    return UVBUS_OK;
}
References uvbus_ipc_client::connect_req, uvbus_transport::impl, uvbus_transport::ipc_client, uvbus_transport::is_server, uvbus_transport::loop, on_client_connect(), uvbus_ipc_client::parent_transport, parse_ipc_address(), uvbus_ipc_client::pipe_handle, uvbus_ipc_client::socket_path, UVBUS_ERROR_INVALID_PARAM, UVBUS_ERROR_NO_MEMORY, UVBUS_OK, uvrpc_alloc(), and uvrpc_free().
ipc_disconnect()
static void ipc_disconnect (void * impl_ptr) [static]
Definition at line 338 of file uvbus_transport_ipc.c.
                                           {
    uvbus_transport_t* transport = (uvbus_transport_t*)impl_ptr;
    if (!transport) {
        return;
    }
    
    if (transport->is_server && transport->impl.ipc_server) {
        uvbus_ipc_server_t* server = (uvbus_ipc_server_t*)transport->impl.ipc_server;
        /* Close all client connections */
        for (int i = 0; i < server->client_count; i++) {
            if (server->clients[i]) {
                uv_close((uv_handle_t*)&server->clients[i]->pipe_handle, NULL);
                uvrpc_free(server->clients[i]);
            }
        }
        uvrpc_free(server->clients);
        
        /* Close listen handle */
        uv_close((uv_handle_t*)&server->listen_pipe, NULL);
        
        /* Remove socket file */
        unlink(server->socket_path);
        
        uvrpc_free(server->socket_path);
        uvrpc_free(server);
        transport->impl.ipc_server = NULL;
    } else if (!transport->is_server && transport->impl.ipc_client) {
        uvbus_ipc_client_t* client = (uvbus_ipc_client_t*)transport->impl.ipc_client;
        /* Close client connection */
        uv_close((uv_handle_t*)&client->pipe_handle, NULL);
        
        uvrpc_free(client->socket_path);
        uvrpc_free(client);
        transport->impl.ipc_client = NULL;
    }
    
    transport->is_connected = 0;
}
References uvbus_ipc_server::client_count, uvbus_ipc_server::clients, uvbus_transport::impl, uvbus_transport::ipc_client, uvbus_transport::ipc_server, uvbus_transport::is_connected, uvbus_transport::is_server, uvbus_ipc_server::listen_pipe, uvbus_ipc_client::pipe_handle, uvbus_ipc_client::socket_path, uvbus_ipc_server::socket_path, and uvrpc_free().
Referenced by ipc_free().
ipc_free()
static void ipc_free (void * impl_ptr) [static]
Definition at line 478 of file uvbus_transport_ipc.c.
                                     {
    uvbus_transport_t* transport = (uvbus_transport_t*)impl_ptr;
    if (!transport) {
        return;
    }
    
    ipc_disconnect(transport);
    
    if (transport->address) {
        uvrpc_free(transport->address);
    }
    
    uvrpc_free(transport);
}
References uvbus_transport::address, ipc_disconnect(), and uvrpc_free().
ipc_listen()
static int ipc_listen (void * impl_ptr, const char * address) [static]
Definition at line 212 of file uvbus_transport_ipc.c.
                                                           {
    uvbus_transport_t* transport = (uvbus_transport_t*)impl_ptr;
    if (!transport) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    if (!transport->is_server) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    /* Parse address */
    char* socket_path = NULL;
    if (parse_ipc_address(address, &socket_path) != 0) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    printf("[IPC LISTEN] Starting server on %s\n", socket_path);
    fflush(stdout);
    
    /* Create server */
    uvbus_ipc_server_t* server = (uvbus_ipc_server_t*)uvrpc_alloc(sizeof(uvbus_ipc_server_t));
    if (!server) {
        uvrpc_free(socket_path);
        return UVBUS_ERROR_NO_MEMORY;
    }
    
    memset(server, 0, sizeof(uvbus_ipc_server_t));
    server->socket_path = socket_path;
    server->parent_transport = transport;
    server->clients = (uvbus_ipc_client_t**)uvrpc_alloc(sizeof(uvbus_ipc_client_t*) * 10);
    server->client_capacity = 10;
    server->client_count = 0;
    
    /* Initialize pipe handle */
    uv_pipe_init(transport->loop, &server->listen_pipe, 0);
    server->listen_pipe.data = transport;
    
    printf("[IPC LISTEN] Pipe initialized\n");
    fflush(stdout);
    
    /* Bind to socket path */
    int bind_result = uv_pipe_bind(&server->listen_pipe, socket_path);
    if (bind_result != 0) {
        fprintf(stderr, "[IPC LISTEN] Bind failed: %s\n", uv_strerror(bind_result));
        uv_close((uv_handle_t*)&server->listen_pipe, NULL);
        uvrpc_free(server->socket_path);
        uvrpc_free(server->clients);
        uvrpc_free(server);
        return UVBUS_ERROR_IO;
    }
    
    printf("[IPC LISTEN] Bind successful\n");
    fflush(stdout);
    
    /* Listen */
    int listen_result = uv_listen((uv_stream_t*)&server->listen_pipe, 128, on_server_connection);
    if (listen_result != 0) {
        fprintf(stderr, "[IPC LISTEN] Listen failed: %s\n", uv_strerror(listen_result));
        uv_close((uv_handle_t*)&server->listen_pipe, NULL);
        uvrpc_free(server->socket_path);
        uvrpc_free(server->clients);
        uvrpc_free(server);
        return UVBUS_ERROR_IO;
    }
    
    printf("[IPC LISTEN] Listen successful\n");
    fflush(stdout);
    
    server->is_listening = 1;
    transport->is_connected = 1;
    transport->impl.ipc_server = (void*)server;
    
    /* Set bus as active - server is ready to accept connections */
    if (transport->parent_bus) {
        transport->parent_bus->is_active = 1;
    }
    
    printf("[IPC LISTEN] Server started successfully\n");
    fflush(stdout);
    
    return UVBUS_OK;
}
References uvbus_ipc_server::client_capacity, uvbus_ipc_server::client_count, uvbus_ipc_server::clients, uvbus_transport::impl, uvbus_transport::ipc_server, uvbus::is_active, uvbus_transport::is_connected, uvbus_ipc_server::is_listening, uvbus_transport::is_server, uvbus_ipc_server::listen_pipe, uvbus_transport::loop, on_server_connection(), uvbus_transport::parent_bus, uvbus_ipc_server::parent_transport, parse_ipc_address(), uvbus_ipc_server::socket_path, UVBUS_ERROR_INVALID_PARAM, UVBUS_ERROR_IO, UVBUS_ERROR_NO_MEMORY, UVBUS_OK, uvrpc_alloc(), and uvrpc_free().
ipc_send()
static int ipc_send (void * impl_ptr, const uint8_t * data, size_t size) [static]
Definition at line 378 of file uvbus_transport_ipc.c.
                                                                      {
    uvbus_transport_t* transport = (uvbus_transport_t*)impl_ptr;
    if (!transport) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    if (!transport->is_connected) {
        return UVBUS_ERROR_NOT_CONNECTED;
    }
    
    if (transport->is_server) {
        uvbus_ipc_server_t* server = (uvbus_ipc_server_t*)transport->impl.ipc_server;
        /* Broadcast to all clients */
        for (int i = 0; i < server->client_count; i++) {
            uv_write_t* req = (uv_write_t*)uvrpc_alloc(sizeof(uv_write_t));
            if (!req) {
                continue;
            }
            
            uint8_t* data_copy = (uint8_t*)uvrpc_alloc(size);
            if (!data_copy) {
                uvrpc_free(req);
                continue;
            }
            memcpy(data_copy, data, size);
            
            uv_buf_t buf = uv_buf_init((char*)data_copy, size);
            req->data = data_copy;
            
            uv_write(req, (uv_stream_t*)&server->clients[i]->pipe_handle, &buf, 1, on_write);
        }
    } else {
        uvbus_ipc_client_t* client = (uvbus_ipc_client_t*)transport->impl.ipc_client;
        /* Send to server */
        uv_write_t* req = (uv_write_t*)uvrpc_alloc(sizeof(uv_write_t));
        if (!req) {
            return UVBUS_ERROR_NO_MEMORY;
        }
        
        uint8_t* data_copy = (uint8_t*)uvrpc_alloc(size);
        if (!data_copy) {
            uvrpc_free(req);
            return UVBUS_ERROR_NO_MEMORY;
        }
        memcpy(data_copy, data, size);
        
        uv_buf_t buf = uv_buf_init((char*)data_copy, size);
        req->data = data_copy;
        
        if (uv_write(req, (uv_stream_t*)&client->pipe_handle, &buf, 1, on_write) != 0) {
            uvrpc_free(data_copy);
            uvrpc_free(req);
            return UVBUS_ERROR_IO;
        }
    }
    
    return UVBUS_OK;
}
References uvbus_ipc_server::client_count, uvbus_ipc_server::clients, uvbus_transport::impl, uvbus_transport::ipc_client, uvbus_transport::ipc_server, uvbus_transport::is_connected, uvbus_transport::is_server, on_write(), uvbus_ipc_client::pipe_handle, UVBUS_ERROR_INVALID_PARAM, UVBUS_ERROR_IO, UVBUS_ERROR_NO_MEMORY, UVBUS_ERROR_NOT_CONNECTED, UVBUS_OK, uvrpc_alloc(), and uvrpc_free().
ipc_send_to()
static int ipc_send_to (void * impl_ptr, const uint8_t * data, size_t size, void * target) [static]
Definition at line 438 of file uvbus_transport_ipc.c.
                                                                                       {
    uvbus_transport_t* transport = (uvbus_transport_t*)impl_ptr;
    if (!transport) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    if (!transport->is_server) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    uvbus_ipc_client_t* client = (uvbus_ipc_client_t*)target;
    if (!client) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    uv_write_t* req = (uv_write_t*)uvrpc_alloc(sizeof(uv_write_t));
    if (!req) {
        return UVBUS_ERROR_NO_MEMORY;
    }
    
    uint8_t* data_copy = (uint8_t*)uvrpc_alloc(size);
    if (!data_copy) {
        uvrpc_free(req);
        return UVBUS_ERROR_NO_MEMORY;
    }
    memcpy(data_copy, data, size);
    
    uv_buf_t buf = uv_buf_init((char*)data_copy, size);
    req->data = data_copy;
    
    if (uv_write(req, (uv_stream_t*)&client->pipe_handle, &buf, 1, on_write) != 0) {
        uvrpc_free(data_copy);
        uvrpc_free(req);
        return UVBUS_ERROR_IO;
    }
    
    return UVBUS_OK;
}
References uvbus_transport::is_server, on_write(), uvbus_ipc_client::pipe_handle, UVBUS_ERROR_INVALID_PARAM, UVBUS_ERROR_IO, UVBUS_ERROR_NO_MEMORY, UVBUS_OK, uvrpc_alloc(), and uvrpc_free().
on_client_alloc()
static void on_client_alloc (uv_handle_t * handle, size_t suggested_size, uv_buf_t * buf) [static]
Definition at line 101 of file uvbus_transport_ipc.c.
                                                                                       {
    uvbus_ipc_client_t* client = (uvbus_ipc_client_t*)handle->data;
    
    if (client->read_pos + suggested_size > sizeof(client->read_buffer)) {
        suggested_size = sizeof(client->read_buffer) - client->read_pos;
    }
    
    buf->base = (char*)client->read_buffer + client->read_pos;
    buf->len = suggested_size;
}
References uvbus_ipc_client::read_buffer, and uvbus_ipc_client::read_pos.
Referenced by on_client_connect(), and on_server_connection().
on_client_connect()
static void on_client_connect (uv_connect_t * req, int status) [static]
Definition at line 113 of file uvbus_transport_ipc.c.
                                                             {
    uvbus_transport_t* transport = (uvbus_transport_t*)req->data;
    
    if (status == 0) {
        transport->is_connected = 1;
        
        /* Set bus as active */
        if (transport->parent_bus) {
            transport->parent_bus->is_active = 1;
        }
        
        /* Start reading */
        uvbus_ipc_client_t* client = (uvbus_ipc_client_t*)transport->impl.ipc_client;
        uv_read_start((uv_stream_t*)&client->pipe_handle, on_client_alloc, on_client_read);
        
        if (transport->connect_cb) {
            transport->connect_cb(UVBUS_OK, transport->callback_ctx);
        }
    } else {
        if (transport->connect_cb) {
            transport->connect_cb(UVBUS_ERROR_IO, transport->callback_ctx);
        }
    }
}
References uvbus_transport::callback_ctx, uvbus_transport::connect_cb, uvbus_transport::impl, uvbus_transport::ipc_client, uvbus::is_active, uvbus_transport::is_connected, on_client_alloc(), on_client_read(), uvbus_transport::parent_bus, uvbus_ipc_client::pipe_handle, UVBUS_ERROR_IO, and UVBUS_OK.
Referenced by ipc_connect().
on_client_read()
static void on_client_read (uv_stream_t * stream, ssize_t nread, const uv_buf_t * buf) [static]
Definition at line 69 of file uvbus_transport_ipc.c.
                                                                                    {
    if (!stream) return;
    
    /* Get client from stream data (pipe_handle.data should point to client, not transport) */
    uvbus_ipc_client_t* client = (uvbus_ipc_client_t*)stream->data;
    if (!client) return;
    
    uvbus_transport_t* transport = (uvbus_transport_t*)client->parent_transport;
    if (!transport) return;
    
    if (nread < 0) {
        if (nread != UV_EOF) {
            if (transport->error_cb) {
                transport->error_cb(UVBUS_ERROR_IO, uv_strerror(nread), transport->callback_ctx);
            }
        }
        return;
    }
    
    if (nread > 0 && transport->recv_cb) {
        /* Determine if this is server mode or client mode */
        if (transport->is_server) {
            /* Server mode: pass client context and server context */
            transport->recv_cb((const uint8_t*)buf->base, nread, client, transport->callback_ctx);
        } else {
            /* Client mode: pass NULL for client context */
            transport->recv_cb((const uint8_t*)buf->base, nread, NULL, transport->callback_ctx);
        }
    }
}
References uvbus_transport::callback_ctx, uvbus_transport::error_cb, uvbus_transport::is_server, uvbus_ipc_client::parent_transport, uvbus_transport::recv_cb, and UVBUS_ERROR_IO.
Referenced by on_client_connect(), and on_server_connection().
on_server_connection()
static void on_server_connection (uv_stream_t * server, int status) [static]
Definition at line 139 of file uvbus_transport_ipc.c.
                                                                  {
    uvbus_transport_t* transport = (uvbus_transport_t*)server->data;
    
    if (status < 0) {
        if (transport->error_cb) {
            transport->error_cb(UVBUS_ERROR_IO, uv_strerror(status), transport->callback_ctx);
        }
        return;
    }
    
    uvbus_ipc_server_t* ipc_server = (uvbus_ipc_server_t*)transport->impl.ipc_server;
    
    /* Create new client connection */
    uvbus_ipc_client_t* client = (uvbus_ipc_client_t*)uvrpc_alloc(sizeof(uvbus_ipc_client_t));
    if (!client) {
        return;
    }
    
    memset(client, 0, sizeof(uvbus_ipc_client_t));
    
    /* Initialize pipe handle */
    uv_pipe_init(transport->loop, &client->pipe_handle, 0);
    client->pipe_handle.data = client;
    
    /* Accept connection */
    if (uv_accept(server, (uv_stream_t*)&client->pipe_handle) == 0) {
        /* Add to client list */
        if (ipc_server->client_count >= ipc_server->client_capacity) {
            ipc_server->client_capacity *= 2;
            ipc_server->clients = (uvbus_ipc_client_t**)uvrpc_realloc(
                ipc_server->clients,
                sizeof(uvbus_ipc_client_t*) * ipc_server->client_capacity
            );
        }
        
        ipc_server->clients[ipc_server->client_count++] = client;
        
        /* Set parent reference */
        client->parent_transport = transport;
        
        /* Start reading */
        uv_read_start((uv_stream_t*)&client->pipe_handle, on_client_alloc, on_client_read);
    } else {
        uv_close((uv_handle_t*)&client->pipe_handle, NULL);
        uvrpc_free(client);
    }
}
References uvbus_transport::callback_ctx, uvbus_ipc_server::client_capacity, uvbus_ipc_server::client_count, uvbus_ipc_server::clients, uvbus_transport::error_cb, uvbus_transport::impl, uvbus_transport::ipc_server, uvbus_transport::loop, on_client_alloc(), on_client_read(), uvbus_ipc_client::parent_transport, UVBUS_ERROR_IO, uvrpc_alloc(), uvrpc_free(), and uvrpc_realloc().
Referenced by ipc_listen().
on_write()
static void on_write (uv_write_t * req, int status) [static]
Definition at line 188 of file uvbus_transport_ipc.c.
                                                  {
    uvrpc_free(req->data);
    uvrpc_free(req);
}
References uvrpc_free().
Referenced by ipc_send(), and ipc_send_to().
parse_ipc_address()
static int parse_ipc_address (const char * address, char ** socket_path) [static]
Definition at line 48 of file uvbus_transport_ipc.c.
                                                                      {
    if (!address || !socket_path) {
        return -1;
    }
    
    /* Skip protocol prefix */
    const char* path_start = address;
    if (strncmp(address, "ipc://", 6) == 0) {
        path_start += 6;
    }
    
    *socket_path = (char*)uvrpc_alloc(strlen(path_start) + 1);
    if (!*socket_path) {
        return -1;
    }
    strcpy(*socket_path, path_start);
    
    return 0;
}
References uvrpc_alloc().
Referenced by ipc_connect(), and ipc_listen().
Variable Documentation
ipc_vtable
const uvbus_transport_vtable_t ipc_vtable [static]
Initial value:
= {
    .listen = ipc_listen,
    .connect = ipc_connect,
    .disconnect = ipc_disconnect,
    .send = ipc_send,
    .send_to = ipc_send_to,
    .free = ipc_free
}
Definition at line 202 of file uvbus_transport_ipc.c.
Referenced by create_ipc_transport().