src/uvbus_transport_udp.c File Reference
Classes
struct uvbus_udp_client
struct uvbus_udp_server
Typedefs
typedef struct uvbus_udp_client uvbus_udp_client_t
typedef struct uvbus_udp_server uvbus_udp_server_t
Functions
uvbus_transport_t * create_udp_transport (uvbus_transport_type_t type, uv_loop_t *loop)
static void on_client_alloc (uv_handle_t *handle, size_t suggested_size, uv_buf_t *buf)
static void on_client_recv (uv_udp_t *handle, ssize_t nread, const uv_buf_t *buf, const struct sockaddr *addr, unsigned flags)
static void on_send (uv_udp_send_t *req, int status)
static void on_server_alloc (uv_handle_t *handle, size_t suggested_size, uv_buf_t *buf)
static void on_server_recv (uv_udp_t *handle, ssize_t nread, const uv_buf_t *buf, const struct sockaddr *addr, unsigned flags)
static int parse_udp_address (const char *address, char **host, int *port)
static int udp_connect (void *impl_ptr, const char *address)
static void udp_disconnect (void *impl_ptr)
static void udp_free (void *impl_ptr)
static int udp_listen (void *impl_ptr, const char *address)
static int udp_send (void *impl_ptr, const uint8_t *data, size_t size)
static int udp_send_to (void *impl_ptr, const uint8_t *data, size_t size, void *target)
Variables
static const uvbus_transport_vtable_t udp_vtable
Typedef Documentation
uvbus_udp_client_t
typedef struct uvbus_udp_client uvbus_udp_client_t
UVBus UDP Transport Implementation
Definition at line 13 of file uvbus_transport_udp.c.
uvbus_udp_server_t
typedef struct uvbus_udp_server uvbus_udp_server_t
Definition at line 14 of file uvbus_transport_udp.c.
Function Documentation
create_udp_transport()
uvbus_transport_t * create_udp_transport (uvbus_transport_type_t type, uv_loop_t * loop)
Definition at line 431 of file uvbus_transport_udp.c.
                                                                                      {
    uvbus_transport_t* transport = (uvbus_transport_t*)uvrpc_alloc(sizeof(uvbus_transport_t));
    if (!transport) {
        return NULL;
    }
    
    memset(transport, 0, sizeof(uvbus_transport_t));
    transport->type = type;
    transport->loop = loop;
    transport->vtable = &udp_vtable;
    
    return transport;
}
References uvbus_transport::loop, uvbus_transport::type, udp_vtable, uvrpc_alloc(), and uvbus_transport::vtable.
Referenced by create_transport().
on_client_alloc()
static void on_client_alloc (uv_handle_t * handle, size_t suggested_size, uv_buf_t * buf) [static]
Definition at line 140 of file uvbus_transport_udp.c.
                                                                                       {
    buf->base = (char*)uvrpc_alloc(UVBUS_MAX_BUFFER_SIZE);
    if (buf->base) {
        buf->len = UVBUS_MAX_BUFFER_SIZE;
    } else {
        buf->len = 0;
    }
}
References uvrpc_alloc().
Referenced by udp_connect().
on_client_recv()
static void on_client_recv (uv_udp_t * handle, ssize_t nread, const uv_buf_t * buf, const struct sockaddr * addr, unsigned flags) [static]
Definition at line 117 of file uvbus_transport_udp.c.
                                                                        {
    uvbus_transport_t* transport = (uvbus_transport_t*)handle->data;
    
    if (nread < 0) {
        if (nread != UV_EOF) {
            if (transport->error_cb) {
                transport->error_cb(UVBUS_ERROR_IO, uv_strerror(nread), transport->callback_ctx);
            }
        }
        uvrpc_free(buf->base);
        return;
    }
    
    if (nread > 0 && transport->recv_cb) {
        /* Client mode: pass NULL for client context */
        transport->recv_cb((const uint8_t*)buf->base, nread, NULL, transport->callback_ctx);
    }
    
    uvrpc_free(buf->base);
}
References uvbus_transport::callback_ctx, uvbus_transport::error_cb, uvbus_transport::recv_cb, UVBUS_ERROR_IO, and uvrpc_free().
Referenced by udp_connect().
on_send()
static void on_send (uv_udp_send_t * req, int status) [static]
Definition at line 150 of file uvbus_transport_udp.c.
                                                    {
    uvrpc_free(req->data);
    uvrpc_free(req);
}
References uvrpc_free().
Referenced by udp_send(), and udp_send_to().
on_server_alloc()
static void on_server_alloc (uv_handle_t * handle, size_t suggested_size, uv_buf_t * buf) [static]
Definition at line 107 of file uvbus_transport_udp.c.
                                                                                       {
    buf->base = (char*)uvrpc_alloc(UVBUS_MAX_BUFFER_SIZE);
    if (buf->base) {
        buf->len = UVBUS_MAX_BUFFER_SIZE;
    } else {
        buf->len = 0;
    }
}
References uvrpc_alloc().
Referenced by udp_listen().
on_server_recv()
static void on_server_recv (uv_udp_t * handle, ssize_t nread, const uv_buf_t * buf, const struct sockaddr * addr, unsigned flags) [static]
Definition at line 78 of file uvbus_transport_udp.c.
                                                                        {
    uvbus_transport_t* transport = (uvbus_transport_t*)handle->data;
    
    if (nread < 0) {
        if (nread != UV_EOF) {
            if (transport->error_cb) {
                transport->error_cb(UVBUS_ERROR_IO, uv_strerror(nread), transport->callback_ctx);
            }
        }
        uvrpc_free(buf->base);
        return;
    }
    
    if (nread > 0 && transport->recv_cb) {
        /* Copy the client address to use as client context */
        struct sockaddr_storage* addr_copy = (struct sockaddr_storage*)uvrpc_alloc(sizeof(struct sockaddr_storage));
        if (addr_copy) {
            memcpy(addr_copy, addr, sizeof(struct sockaddr_storage));
            transport->recv_cb((const uint8_t*)buf->base, nread, addr_copy, transport->callback_ctx);
        } else {
            transport->recv_cb((const uint8_t*)buf->base, nread, NULL, transport->callback_ctx);
        }
    }
    
    uvrpc_free(buf->base);
}
References uvbus_transport::callback_ctx, uvbus_transport::error_cb, uvbus_transport::recv_cb, UVBUS_ERROR_IO, uvrpc_alloc(), and uvrpc_free().
Referenced by udp_listen().
parse_udp_address()
static int parse_udp_address (const char * address, char ** host, int * port) [static]
Definition at line 45 of file uvbus_transport_udp.c.
                                                                          {
    if (!address || !host || !port) {
        return -1;
    }
    
    /* Skip protocol prefix */
    const char* addr_start = address;
    if (strncmp(address, "udp://", 6) == 0) {
        addr_start += 6;
    }
    
    /* Find port separator */
    const char* colon = strrchr(addr_start, ':');
    if (!colon) {
        return -1;
    }
    
    /* Extract host */
    size_t host_len = colon - addr_start;
    *host = (char*)uvrpc_alloc(host_len + 1);
    if (!*host) {
        return -1;
    }
    memcpy(*host, addr_start, host_len);
    (*host)[host_len] = '\0';
    
    /* Extract port */
    *port = atoi(colon + 1);
    
    return 0;
}
References uvrpc_alloc().
Referenced by udp_connect(), and udp_listen().
udp_connect()
static int udp_connect (void * impl_ptr, const char * address) [static]
Definition at line 235 of file uvbus_transport_udp.c.
                                                            {
    uvbus_transport_t* transport = (uvbus_transport_t*)impl_ptr;
    if (!transport) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    if (transport->is_server) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    /* Parse address */
    char* host = NULL;
    int port = 0;
    if (parse_udp_address(address, &host, &port) != 0) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    /* Create client */
    uvbus_udp_client_t* client = (uvbus_udp_client_t*)uvrpc_alloc(sizeof(uvbus_udp_client_t));
    if (!client) {
        uvrpc_free(host);
        return UVBUS_ERROR_NO_MEMORY;
    }
    
    memset(client, 0, sizeof(uvbus_udp_client_t));
    client->host = host;
    client->port = port;
    client->parent_transport = transport;
    
    /* Initialize UDP handle */
    uv_udp_init(transport->loop, &client->udp_handle);
    client->udp_handle.data = transport;
    
    /* Set up server address */
    uv_ip4_addr(host, port, &client->server_addr);
    
    /* Bind to local address (random port) */
    struct sockaddr_in local_addr;
    uv_ip4_addr("0.0.0.0", 0, &local_addr);
    if (uv_udp_bind(&client->udp_handle, (const struct sockaddr*)&local_addr, 0) != 0) {
        uv_close((uv_handle_t*)&client->udp_handle, NULL);
        uvrpc_free(client->host);
        uvrpc_free(client);
        return UVBUS_ERROR_IO;
    }
    
    /* Start receiving */
    if (uv_udp_recv_start(&client->udp_handle, on_client_alloc, on_client_recv) != 0) {
        uv_close((uv_handle_t*)&client->udp_handle, NULL);
        uvrpc_free(client->host);
        uvrpc_free(client);
        return UVBUS_ERROR_IO;
    }
    
    client->is_connected = 1;
    transport->parent_bus->is_active = 1;
    transport->is_connected = 1;
    transport->impl.udp_client = (void*)client;
    
    if (transport->connect_cb) {
        transport->connect_cb(UVBUS_OK, transport->callback_ctx);
    }
    
    return UVBUS_OK;
}
References uvbus_transport::callback_ctx, uvbus_transport::connect_cb, uvbus_udp_client::host, uvbus_transport::impl, uvbus::is_active, uvbus_transport::is_connected, uvbus_udp_client::is_connected, uvbus_transport::is_server, uvbus_transport::loop, on_client_alloc(), on_client_recv(), uvbus_transport::parent_bus, uvbus_udp_client::parent_transport, parse_udp_address(), uvbus_udp_client::port, uvbus_udp_client::server_addr, uvbus_transport::udp_client, uvbus_udp_client::udp_handle, UVBUS_ERROR_INVALID_PARAM, UVBUS_ERROR_IO, UVBUS_ERROR_NO_MEMORY, UVBUS_OK, uvrpc_alloc(), and uvrpc_free().
udp_disconnect()
static void udp_disconnect (void * impl_ptr) [static]
Definition at line 302 of file uvbus_transport_udp.c.
                                           {
    uvbus_transport_t* transport = (uvbus_transport_t*)impl_ptr;
    if (!transport) {
        return;
    }
    
    if (transport->is_server && transport->impl.udp_server) {
        uvbus_udp_server_t* server = (uvbus_udp_server_t*)transport->impl.udp_server;
        /* Close UDP handle */
        uv_close((uv_handle_t*)&server->udp_handle, NULL);
        
        uvrpc_free(server->host);
        uvrpc_free(server);
        transport->impl.udp_server = NULL;
    } else if (!transport->is_server && transport->impl.udp_client) {
        uvbus_udp_client_t* client = (uvbus_udp_client_t*)transport->impl.udp_client;
        /* Close UDP handle */
        uv_close((uv_handle_t*)&client->udp_handle, NULL);
        
        uvrpc_free(client->host);
        uvrpc_free(client);
        transport->impl.udp_client = NULL;
    }
    
    transport->is_connected = 0;
}
References uvbus_udp_client::host, uvbus_udp_server::host, uvbus_transport::impl, uvbus_transport::is_connected, uvbus_transport::is_server, uvbus_transport::udp_client, uvbus_udp_client::udp_handle, uvbus_udp_server::udp_handle, uvbus_transport::udp_server, and uvrpc_free().
Referenced by udp_free().
udp_free()
static void udp_free (void * impl_ptr) [static]
Definition at line 415 of file uvbus_transport_udp.c.
                                     {
    uvbus_transport_t* transport = (uvbus_transport_t*)impl_ptr;
    if (!transport) {
        return;
    }
    
    udp_disconnect(transport);
    
    if (transport->address) {
        uvrpc_free(transport->address);
    }
    
    uvrpc_free(transport);
}
References uvbus_transport::address, udp_disconnect(), and uvrpc_free().
udp_listen()
static int udp_listen (void * impl_ptr, const char * address) [static]
Definition at line 174 of file uvbus_transport_udp.c.
                                                           {
    uvbus_transport_t* transport = (uvbus_transport_t*)impl_ptr;
    if (!transport) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    if (!transport->is_server) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    /* Parse address */
    char* host = NULL;
    int port = 0;
    if (parse_udp_address(address, &host, &port) != 0) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    /* Create server */
    uvbus_udp_server_t* server = (uvbus_udp_server_t*)uvrpc_alloc(sizeof(uvbus_udp_server_t));
    if (!server) {
        uvrpc_free(host);
        return UVBUS_ERROR_NO_MEMORY;
    }
    
    memset(server, 0, sizeof(uvbus_udp_server_t));
    server->host = host;
    server->port = port;
    server->parent_transport = transport;
    
    /* Initialize UDP handle */
    uv_udp_init(transport->loop, &server->udp_handle);
    server->udp_handle.data = transport;
    
    /* Bind to address */
    struct sockaddr_in addr;
    uv_ip4_addr(host, port, &addr);
    
    if (uv_udp_bind(&server->udp_handle, (const struct sockaddr*)&addr, 0) != 0) {
        uv_close((uv_handle_t*)&server->udp_handle, NULL);
        uvrpc_free(server->host);
        uvrpc_free(server);
        return UVBUS_ERROR_IO;
    }
    
    /* Start receiving */
    if (uv_udp_recv_start(&server->udp_handle, on_server_alloc, on_server_recv) != 0) {
        uv_close((uv_handle_t*)&server->udp_handle, NULL);
        uvrpc_free(server->host);
        uvrpc_free(server);
        return UVBUS_ERROR_IO;
    }
    
    server->is_listening = 1;
    transport->is_connected = 1;
    transport->parent_bus->is_active = 1;
    transport->impl.udp_server = (void*)server;
    
    return UVBUS_OK;
}
References uvbus_udp_server::host, uvbus_transport::impl, uvbus::is_active, uvbus_transport::is_connected, uvbus_udp_server::is_listening, uvbus_transport::is_server, uvbus_transport::loop, on_server_alloc(), on_server_recv(), uvbus_transport::parent_bus, uvbus_udp_server::parent_transport, parse_udp_address(), uvbus_udp_server::port, uvbus_udp_server::udp_handle, uvbus_transport::udp_server, UVBUS_ERROR_INVALID_PARAM, UVBUS_ERROR_IO, UVBUS_ERROR_NO_MEMORY, UVBUS_OK, uvrpc_alloc(), and uvrpc_free().
udp_send()
static int udp_send (void * impl_ptr, const uint8_t * data, size_t size) [static]
Definition at line 330 of file uvbus_transport_udp.c.
                                                                      {
    uvbus_transport_t* transport = (uvbus_transport_t*)impl_ptr;
    if (!transport) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    if (!transport->is_connected) {
        return UVBUS_ERROR_NOT_CONNECTED;
    }
    
    if (transport->is_server) {
        /* UDP server doesn't broadcast like TCP - needs target */
        return UVBUS_ERROR_INVALID_PARAM;
    } else {
        uvbus_udp_client_t* client = (uvbus_udp_client_t*)transport->impl.udp_client;
        /* Client send to server */
        uv_udp_send_t* req = (uv_udp_send_t*)uvrpc_alloc(sizeof(uv_udp_send_t));
        if (!req) {
            return UVBUS_ERROR_NO_MEMORY;
        }
        
        uint8_t* data_copy = (uint8_t*)uvrpc_alloc(size);
        if (!data_copy) {
            uvrpc_free(req);
            return UVBUS_ERROR_NO_MEMORY;
        }
        memcpy(data_copy, data, size);
        
        uv_buf_t buf = uv_buf_init((char*)data_copy, size);
        req->data = data_copy;
        
        if (uv_udp_send(req, &client->udp_handle, &buf, 1,
                        (const struct sockaddr*)&client->server_addr, on_send) != 0) {
            uvrpc_free(data_copy);
            uvrpc_free(req);
            return UVBUS_ERROR_IO;
        }
    }
    
    return UVBUS_OK;
}
References uvbus_transport::impl, uvbus_transport::is_connected, uvbus_transport::is_server, on_send(), uvbus_udp_client::server_addr, uvbus_transport::udp_client, uvbus_udp_client::udp_handle, UVBUS_ERROR_INVALID_PARAM, UVBUS_ERROR_IO, UVBUS_ERROR_NO_MEMORY, UVBUS_ERROR_NOT_CONNECTED, UVBUS_OK, uvrpc_alloc(), and uvrpc_free().
udp_send_to()
static int udp_send_to (void * impl_ptr, const uint8_t * data, size_t size, void * target) [static]
Definition at line 373 of file uvbus_transport_udp.c.
                                                                                       {
    uvbus_transport_t* transport = (uvbus_transport_t*)impl_ptr;
    if (!transport) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    if (!transport->is_server) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    uvbus_udp_server_t* server = (uvbus_udp_server_t*)transport->impl.udp_server;
    struct sockaddr_in* addr = (struct sockaddr_in*)target;
    if (!addr) {
        return UVBUS_ERROR_INVALID_PARAM;
    }
    
    uv_udp_send_t* req = (uv_udp_send_t*)uvrpc_alloc(sizeof(uv_udp_send_t));
    if (!req) {
        return UVBUS_ERROR_NO_MEMORY;
    }
    
    uint8_t* data_copy = (uint8_t*)uvrpc_alloc(size);
    if (!data_copy) {
        uvrpc_free(req);
        return UVBUS_ERROR_NO_MEMORY;
    }
    memcpy(data_copy, data, size);
    
    uv_buf_t buf = uv_buf_init((char*)data_copy, size);
    req->data = data_copy;
    
    if (uv_udp_send(req, &server->udp_handle, &buf, 1,
                    (const struct sockaddr*)addr, on_send) != 0) {
        uvrpc_free(data_copy);
        uvrpc_free(req);
        return UVBUS_ERROR_IO;
    }
    
    return UVBUS_OK;
}
References uvbus_transport::impl, uvbus_transport::is_server, on_send(), uvbus_udp_server::udp_handle, uvbus_transport::udp_server, UVBUS_ERROR_INVALID_PARAM, UVBUS_ERROR_IO, UVBUS_ERROR_NO_MEMORY, UVBUS_OK, uvrpc_alloc(), and uvrpc_free().
Variable Documentation
udp_vtable
const uvbus_transport_vtable_t udp_vtable [static]
Initial value:
= {
    .listen = udp_listen,
    .connect = udp_connect,
    .disconnect = udp_disconnect,
    .send = udp_send,
    .send_to = udp_send_to,
    .free = udp_free
}
Definition at line 164 of file uvbus_transport_udp.c.
Referenced by create_udp_transport().