src/uvrpc_allocator.c File Reference
UVRPC Memory Allocator Implementation.
Functions
static void * mimalloc_alloc (size_t size)
static void * mimalloc_calloc (size_t count, size_t size)
static void mimalloc_free (void *ptr)
static void * mimalloc_realloc (void *ptr, size_t size)
static void * system_alloc (size_t size)
static void * system_calloc (size_t count, size_t size)
static void system_free (void *ptr)
static void * system_realloc (void *ptr, size_t size)
void * uvrpc_alloc (size_t size)
Allocate memory.
void uvrpc_allocator_cleanup (void)
Cleanup allocator resources.
const char * uvrpc_allocator_get_name (void)
Get current allocator name.
uvrpc_allocator_type_t uvrpc_allocator_get_type (void)
Get current allocator type.
void uvrpc_allocator_init (uvrpc_allocator_type_t type, const uvrpc_custom_allocator_t *custom)
Initialize allocator (runtime selection)
void * uvrpc_calloc (size_t count, size_t size)
Allocate zero-initialized memory.
void uvrpc_free (void *ptr)
Free memory.
void * uvrpc_realloc (void *ptr, size_t size)
Reallocate memory.
char * uvrpc_strdup (const char *s)
Duplicate a string.
Variables
static uvrpc_allocator_type_t g_allocator_type = UVRPC_DEFAULT_ALLOCATOR
static uvrpc_custom_allocator_t g_custom_allocator = {0}
Detailed Description
UVRPC Memory Allocator Implementation.
Supports runtime allocator type selection:
system: Standard malloc/free
mimalloc: High-performance mimalloc
custom: User-defined allocator
Author
UVRPC Team
Date
2026
Version
1.0
Definition in file uvrpc_allocator.c.
Function Documentation
mimalloc_alloc()
static void * mimalloc_alloc (size_t size) [static]
Definition at line 58 of file uvrpc_allocator.c.
                                         {
    return mi_malloc(size);
}
Referenced by uvrpc_alloc().
mimalloc_calloc()
static void * mimalloc_calloc (size_t count, size_t size) [static]
Definition at line 62 of file uvrpc_allocator.c.
                                                        {
    return mi_calloc(count, size);
}
Referenced by uvrpc_calloc().
mimalloc_free()
static void mimalloc_free (void * ptr) [static]
Definition at line 70 of file uvrpc_allocator.c.
                                     {
    mi_free(ptr);
}
Referenced by uvrpc_free().
mimalloc_realloc()
static void * mimalloc_realloc (void * ptr, size_t size) [static]
Definition at line 66 of file uvrpc_allocator.c.
                                                      {
    return mi_realloc(ptr, size);
}
Referenced by uvrpc_realloc().
system_alloc()
static void * system_alloc (size_t size) [static]
Definition at line 40 of file uvrpc_allocator.c.
                                       {
    return malloc(size);
}
Referenced by uvrpc_alloc().
system_calloc()
static void * system_calloc (size_t count, size_t size) [static]
Definition at line 44 of file uvrpc_allocator.c.
                                                      {
    return calloc(count, size);
}
Referenced by uvrpc_calloc().
system_free()
static void system_free (void * ptr) [static]
Definition at line 52 of file uvrpc_allocator.c.
                                   {
    free(ptr);
}
Referenced by uvrpc_free().
system_realloc()
static void * system_realloc (void * ptr, size_t size) [static]
Definition at line 48 of file uvrpc_allocator.c.
                                                    {
    return realloc(ptr, size);
}
Referenced by uvrpc_realloc().
Variable Documentation
g_allocator_type
uvrpc_allocator_type_t g_allocator_type = UVRPC_DEFAULT_ALLOCATOR [static]
Definition at line 36 of file uvrpc_allocator.c.
Referenced by uvrpc_alloc(), uvrpc_allocator_cleanup(), uvrpc_allocator_get_name(), uvrpc_allocator_get_type(), uvrpc_allocator_init(), uvrpc_calloc(), uvrpc_free(), and uvrpc_realloc().
g_custom_allocator
uvrpc_custom_allocator_t g_custom_allocator = {0} [static]
Definition at line 37 of file uvrpc_allocator.c.
Referenced by uvrpc_alloc(), uvrpc_allocator_cleanup(), uvrpc_allocator_get_name(), uvrpc_allocator_init(), uvrpc_calloc(), uvrpc_free(), and uvrpc_realloc().