src/uvrpc_idmap.h File Reference
Classes
struct uvrpc_idmap_ctx_t
struct uvrpc_idmap_entry_t
Functions
void uvrpc_idmap_ctx_free (uvrpc_idmap_ctx_t *ctx)
uvrpc_idmap_ctx_t * uvrpc_idmap_ctx_new (void)
void uvrpc_idmap_remove (uvrpc_idmap_ctx_t *ctx, uint32_t msgid_gateway)
uint32_t uvrpc_idmap_to_gateway (uvrpc_idmap_ctx_t *ctx, uint32_t msgid_raw, void *client_handle)
int uvrpc_idmap_to_raw (uvrpc_idmap_ctx_t *ctx, uint32_t msgid_gateway, uint32_t *out_msgid_raw, void **out_client_handle)
Function Documentation
uvrpc_idmap_ctx_free()
void uvrpc_idmap_ctx_free (uvrpc_idmap_ctx_t * ctx)
Definition at line 23 of file uvrpc_idmap.c.
                                                  {
    if (!ctx) return;
    /* Free all entries in hash table */
    uvrpc_idmap_entry_t* entry, *tmp;
    HASH_ITER(hh, ctx->map, entry, tmp) {
        HASH_DEL(ctx->map, entry);
        uvrpc_free(entry);
    }
    uvrpc_free(ctx);
}
References uvrpc_idmap_ctx_t::map, and uvrpc_free().
uvrpc_idmap_ctx_new()
uvrpc_idmap_ctx_t * uvrpc_idmap_ctx_new (void)
UVRPC ID Mapping Implementation
Definition at line 12 of file uvrpc_idmap.c.
                                             {
    uvrpc_idmap_ctx_t* ctx = uvrpc_calloc(1, sizeof(uvrpc_idmap_ctx_t));
    if (!ctx) return NULL;
    ctx->map = NULL;
    ctx->next_gateway_id = 1;
    return ctx;
}
References uvrpc_idmap_ctx_t::map, uvrpc_idmap_ctx_t::next_gateway_id, and uvrpc_calloc().
uvrpc_idmap_remove()
void uvrpc_idmap_remove (uvrpc_idmap_ctx_t * ctx, uint32_t msgid_gateway)
Definition at line 76 of file uvrpc_idmap.c.
                                                                        {
    if (!ctx) return;
    /* Find and delete entry */
    uvrpc_idmap_entry_t* entry = NULL;
    HASH_FIND_INT(ctx->map, &msgid_gateway, entry);
    if (entry) {
        HASH_DEL(ctx->map, entry);
        uvrpc_free(entry);
    }
}
References uvrpc_idmap_ctx_t::map, and uvrpc_free().
uvrpc_idmap_to_gateway()
uint32_t uvrpc_idmap_to_gateway (uvrpc_idmap_ctx_t * ctx, uint32_t msgid_raw, void * client_handle)
Definition at line 37 of file uvrpc_idmap.c.
                                                                                                 {
    if (!ctx) return 0;
    /* Generate new gateway msgid */
    uint32_t msgid_gateway = ctx->next_gateway_id++;
    /* Create mapping entry */
    uvrpc_idmap_entry_t* entry = uvrpc_calloc(1, sizeof(uvrpc_idmap_entry_t));
    if (!entry) return 0;
    entry->msgid_raw = msgid_raw;
    entry->msgid_gateway = msgid_gateway;
    entry->client_handle = client_handle;
    /* Store in hash table */
    HASH_ADD_INT(ctx->map, msgid_gateway, entry);
    return msgid_gateway;
}
References uvrpc_idmap_entry_t::client_handle, uvrpc_idmap_ctx_t::map, uvrpc_idmap_entry_t::msgid_gateway, uvrpc_idmap_entry_t::msgid_raw, uvrpc_idmap_ctx_t::next_gateway_id, and uvrpc_calloc().
uvrpc_idmap_to_raw()
int uvrpc_idmap_to_raw (uvrpc_idmap_ctx_t * ctx, uint32_t msgid_gateway, uint32_t * out_msgid_raw, void ** out_client_handle)
Definition at line 58 of file uvrpc_idmap.c.
                                                                          {
    if (!ctx || !out_msgid_raw || !out_client_handle) return -1;
    /* Find mapping entry */
    uvrpc_idmap_entry_t* entry = NULL;
    HASH_FIND_INT(ctx->map, &msgid_gateway, entry);
    if (!entry) return -1;
    /* Return original information */
    *out_msgid_raw = entry->msgid_raw;
    *out_client_handle = entry->client_handle;
    return 0;
}
References uvrpc_idmap_entry_t::client_handle, uvrpc_idmap_ctx_t::map, and uvrpc_idmap_entry_t::msgid_raw.