src/uvrpc_server.c File Reference
UVRPC Async Server Implementation.
Classes
struct handler_entry
struct pending_request
struct uvrpc_server
Typedefs
typedef struct handler_entry handler_entry_t
typedef struct pending_request pending_request_t
Functions
static void server_recv_callback (const uint8_t *data, size_t size, void *client_ctx, void *server_ctx)
void uvrpc_request_free (uvrpc_request_t *req)
Free a request object.
void uvrpc_request_send_response (uvrpc_request_t *req, int status, const uint8_t *result, size_t result_size)
Send a response to a request (deprecated, use uvrpc_response_send)
int uvrpc_response_send (uvrpc_request_t *req, const uint8_t *result, size_t result_size)
Send a response to a request.
int uvrpc_response_send_error (uvrpc_request_t *req, int32_t error_code, const char *error_message)
Send an error response to a request.
uvrpc_server_t * uvrpc_server_create (uvrpc_config_t *config)
Create a new RPC server.
void uvrpc_server_free (uvrpc_server_t *server)
Free the server.
uvrpc_context_t * uvrpc_server_get_context (uvrpc_server_t *server)
Get server context.
uint64_t uvrpc_server_get_total_requests (uvrpc_server_t *server)
Get total requests received.
uint64_t uvrpc_server_get_total_responses (uvrpc_server_t *server)
Get total responses sent.
int uvrpc_server_register (uvrpc_server_t *server, const char *method, uvrpc_handler_t handler, void *ctx)
Register a method handler.
void uvrpc_server_set_context (uvrpc_server_t *server, uvrpc_context_t *ctx)
Set server context.
int uvrpc_server_start (uvrpc_server_t *server)
Start the server.
void uvrpc_server_stop (uvrpc_server_t *server)
Stop the server.
static void write_callback (uv_write_t *req, int status)
Detailed Description
UVRPC Async Server Implementation.
Zero threads, Zero locks, Zero global variables All I/O managed by libuv event loop
Author
UVRPC Team
Date
2026
Version
1.0
Definition in file uvrpc_server.c.
Typedef Documentation
handler_entry_t
typedef struct handler_entry handler_entry_t
pending_request_t
typedef struct pending_request pending_request_t
Function Documentation
server_recv_callback()
static void server_recv_callback (const uint8_t * data, size_t size, void * client_ctx, void * server_ctx) [static]
Definition at line 71 of file uvrpc_server.c.
                                                                                                       {
    uvrpc_server_t* server = (uvrpc_server_t*)server_ctx;
    if (!server) return;
    /* Decode request */
    uint32_t msgid = 0;
    char* method = NULL;
    const uint8_t* params = NULL;
    size_t params_size = 0;
    if (uvrpc_decode_request(data, size, &msgid, &method, &params, &params_size) != UVRPC_OK) {
        UVRPC_LOG("Failed to decode request (size=%zu)", size);
        return;
    }
    /* Create lowercase copy for case-insensitive matching */
    char* method_lower = NULL;
    if (method) {
        method_lower = uvrpc_strdup(method);
        if (method_lower) {
            for (char* p = method_lower; *p; p++) {
                *p = tolower((unsigned char)*p);
            }
        }
    }
    
    /* Find handler using lowercase method name */
    handler_entry_t* entry = NULL;
    HASH_FIND_STR(server->handlers, method_lower, entry);
    
    /* Free the lowercase copy */
    if (method_lower) {
        uvrpc_free(method_lower);
    }
    
    if (entry && entry->handler) {
        /* Increment request counter */
        server->total_requests++;
        
        /* Create request structure */
        uvrpc_request_t req;
        req.server = server;
        req.msgid = msgid;
        req.method = method;
        req.params = (uint8_t*)params;
        req.params_size = params_size;
        req.client_ctx = client_ctx;
        req.user_data = NULL;
        
        /* Call handler */
        entry->handler(&req, entry->ctx);
        /* Free decoded method */
        if (method) uvrpc_free(method);
    } else {
        /* Handler not found, send error response */
        fprintf(stderr, "Handler not found: '%s'\n", method);
        uint8_t* resp_data = NULL;
        size_t resp_size = 0;
        uvrpc_encode_error(msgid, 2, "Method not found", &resp_data, &resp_size);
        if (resp_data) {
            uvrpc_free(resp_data);
        }
        if (method) uvrpc_free(method);
    }
}
References uvrpc_request::client_ctx, handler_entry::ctx, handler_entry::handler, uvrpc_server::handlers, uvrpc_request::method, uvrpc_request::msgid, uvrpc_request::params, uvrpc_request::params_size, uvrpc_request::server, uvrpc_server::total_requests, uvrpc_request::user_data, uvrpc_decode_request(), uvrpc_encode_error(), uvrpc_free(), UVRPC_OK, and uvrpc_strdup().
Referenced by uvrpc_server_create().
write_callback()
static void write_callback (uv_write_t * req, int status) [static]
Definition at line 23 of file uvrpc_server.c.
                                                        {
    (void)status;
    if (req) {
        if (req->data) {
            uvrpc_free(req->data);
        }
        uvrpc_free(req);
    }
}
References uvrpc_free().