src/uvrpc_subscriber.c File Reference
UVRPC Subscriber (Broadcast) Implementation.
Classes
struct subscription_entry
struct uvrpc_subscriber
Typedefs
typedef struct subscription_entry subscription_entry_t
Functions
static void subscriber_connect_callback (int status, void *ctx)
static void subscriber_recv_callback (const uint8_t *data, size_t size, void *client_ctx, void *server_ctx)
int uvrpc_subscriber_connect (uvrpc_subscriber_t *subscriber)
Connect subscriber to publisher.
uvrpc_subscriber_t * uvrpc_subscriber_create (uvrpc_config_t *config)
Create a new subscriber.
void uvrpc_subscriber_disconnect (uvrpc_subscriber_t *subscriber)
Disconnect subscriber.
void uvrpc_subscriber_free (uvrpc_subscriber_t *subscriber)
Free the subscriber.
int uvrpc_subscriber_subscribe (uvrpc_subscriber_t *subscriber, const char *topic, uvrpc_subscribe_callback_t callback, void *ctx)
Subscribe to a topic.
int uvrpc_subscriber_unsubscribe (uvrpc_subscriber_t *subscriber, const char *topic)
Unsubscribe from a topic.
Detailed Description
UVRPC Subscriber (Broadcast) Implementation.
Zero threads, Zero locks, Zero global variables All I/O managed by libuv event loop
Author
UVRPC Team
Date
2026
Version
1.0
Definition in file uvrpc_subscriber.c.
Typedef Documentation
subscription_entry_t
typedef struct subscription_entry subscription_entry_t
Function Documentation
subscriber_connect_callback()
static void subscriber_connect_callback (int status, void * ctx) [static]
Definition at line 98 of file uvrpc_subscriber.c.
                                                               {
    uvrpc_subscriber_t* subscriber = (uvrpc_subscriber_t*)ctx;
    subscriber->is_connected = (status == 0);
    if (status != 0) {
        fprintf(stderr, "Subscriber connection failed: %d\n", status);
    }
}
References uvrpc_subscriber::is_connected.
Referenced by uvrpc_subscriber_create().
subscriber_recv_callback()
static void subscriber_recv_callback (const uint8_t * data, size_t size, void * client_ctx, void * server_ctx) [static]
Definition at line 40 of file uvrpc_subscriber.c.
                                                                                                           {
    uvrpc_subscriber_t* subscriber = (uvrpc_subscriber_t*)server_ctx;
    if (size < 8) {
        return;
    }
    uint8_t* p = (uint8_t*)data;
    /* Parse topic length (little-endian for consistency with FlatBuffers) */
    uint32_t topic_len = *(uint32_t*)p;
    p += 4;
    if (size < 8 + topic_len) {
        return;
    }
    /* Extract topic */
    char* topic = (char*)uvrpc_alloc(topic_len + 1);
    if (!topic) {
        return;
    }
    memcpy(topic, p, topic_len);
    topic[topic_len] = '\0';
    p += topic_len;
    /* Parse data length (little-endian) */
    uint32_t data_size = *(uint32_t*)p;
    p += 4;
    if (size < 8 + topic_len + data_size) {
        uvrpc_free(topic);
        return;
    }
    /* Find subscription for this topic */
    subscription_entry_t* entry = NULL;
    HASH_FIND_STR(subscriber->subscriptions, topic, entry);
    if (entry && entry->callback) {
        /* Call callback with the data */
        uint8_t* data_copy = NULL;
        if (data_size > 0) {
            data_copy = (uint8_t*)uvrpc_alloc(data_size);
            if (data_copy) {
                memcpy(data_copy, p, data_size);
            }
        }
        entry->callback(topic, data_copy, data_size, entry->ctx);
        if (data_copy) uvrpc_free(data_copy);
    }
    uvrpc_free(topic);
}
References subscription_entry::callback, subscription_entry::ctx, uvrpc_subscriber::subscriptions, uvrpc_alloc(), and uvrpc_free().
Referenced by uvrpc_subscriber_create().