src/uvrpc_msgid.h File Reference
Classes
struct uvrpc_msgid_ctx_t
Functions
void uvrpc_msgid_ctx_free (uvrpc_msgid_ctx_t *ctx)
uvrpc_msgid_ctx_t * uvrpc_msgid_ctx_new (void)
void uvrpc_msgid_ctx_set_start (uvrpc_msgid_ctx_t *ctx, uint32_t start_seq)
uint32_t uvrpc_msgid_next (uvrpc_msgid_ctx_t *ctx)
Function Documentation
uvrpc_msgid_ctx_free()
void uvrpc_msgid_ctx_free (uvrpc_msgid_ctx_t * ctx)
Definition at line 20 of file uvrpc_msgid.c.
                                                  {
    if (ctx) {
        uvrpc_free(ctx);
    }
}
References uvrpc_free().
Referenced by uvrpc_client_create(), and uvrpc_client_free().
uvrpc_msgid_ctx_new()
uvrpc_msgid_ctx_t * uvrpc_msgid_ctx_new (void)
UVRPC Message ID Encoding Implementation
Definition at line 10 of file uvrpc_msgid.c.
                                             {
    uvrpc_msgid_ctx_t* ctx = (uvrpc_msgid_ctx_t*)uvrpc_calloc(1, sizeof(uvrpc_msgid_ctx_t));
    if (!ctx) return NULL;
    ctx->next_seq = 1;
    return ctx;
}
References uvrpc_msgid_ctx_t::next_seq, and uvrpc_calloc().
Referenced by uvrpc_client_create().
uvrpc_msgid_ctx_set_start()
void uvrpc_msgid_ctx_set_start (uvrpc_msgid_ctx_t * ctx, uint32_t start_seq)
Definition at line 27 of file uvrpc_msgid.c.
                                                                           {
    if (ctx) {
        ctx->next_seq = start_seq;
    }
}
References uvrpc_msgid_ctx_t::next_seq.
Referenced by uvrpc_client_create().
uvrpc_msgid_next()
uint32_t uvrpc_msgid_next (uvrpc_msgid_ctx_t * ctx)
Definition at line 34 of file uvrpc_msgid.c.
                                                  {
    if (!ctx) return 0;
    uint32_t msgid = ctx->next_seq++;
    
    /* Wrap around on overflow (32-bit) */
    if (ctx->next_seq == 0) {
        ctx->next_seq = 1; /* Skip 0, start from 1 */
    }
    
    return msgid;
}
References uvrpc_msgid_ctx_t::next_seq.
Referenced by uvrpc_client_call_batch(), and uvrpc_client_call_no_retry_internal().