src/uvrpc_client.c File Reference
UVRPC Async Client Implementation.
Classes
struct pending_callback
struct uvrpc_client
Typedefs
typedef struct pending_callback pending_callback_t
Functions
static void client_connect_callback (int status, void *ctx)
static void client_recv_callback (const uint8_t *data, size_t size, void *client_ctx, void *server_ctx)
int uvrpc_client_call (uvrpc_client_t *client, const char *method, const uint8_t *params, size_t params_size, uvrpc_callback_t callback, void *ctx)
Call RPC method with automatic retry.
int uvrpc_client_call_batch (uvrpc_client_t *client, const char **methods, const uint8_t **params_array, size_t *params_sizes, uvrpc_callback_t *callbacks, void **contexts, int count)
Call multiple RPC methods in batch.
int uvrpc_client_call_no_retry (uvrpc_client_t *client, const char *method, const uint8_t *params, size_t params_size, uvrpc_callback_t callback, void *ctx)
Call RPC method without retry.
static int uvrpc_client_call_no_retry_internal (uvrpc_client_t *client, const char *method, const uint8_t *params, size_t params_size, uvrpc_callback_t callback, void *ctx)
int uvrpc_client_connect (uvrpc_client_t *client)
Connect to server synchronously.
int uvrpc_client_connect_with_callback (uvrpc_client_t *client, uvrpc_connect_callback_t callback, void *ctx)
Connect to server asynchronously.
uvrpc_client_t * uvrpc_client_create (uvrpc_config_t *config)
Create a new RPC client.
void uvrpc_client_disconnect (uvrpc_client_t *client)
Disconnect from server.
void uvrpc_client_free (uvrpc_client_t *client)
Free the client.
uvrpc_context_t * uvrpc_client_get_context (uvrpc_client_t *client)
Get client context.
uv_loop_t * uvrpc_client_get_loop (uvrpc_client_t *client)
Get the event loop.
int uvrpc_client_get_max_retries (uvrpc_client_t *client)
Get maximum retry count.
int uvrpc_client_get_pending_count (uvrpc_client_t *client)
Get pending request count.
void uvrpc_client_set_context (uvrpc_client_t *client, uvrpc_context_t *ctx)
Set client context.
int uvrpc_client_set_max_concurrent (uvrpc_client_t *client, int max_concurrent)
Set maximum concurrent requests.
int uvrpc_client_set_max_retries (uvrpc_client_t *client, int max_retries)
Set maximum retry count.
void uvrpc_response_free (uvrpc_response_t *resp)
Free a response object.
Detailed Description
UVRPC Async Client Implementation.
Zero threads, Zero locks, Zero global variables All I/O managed by libuv event loop
Author
UVRPC Team
Date
2026
Version
1.0
Definition in file uvrpc_client.c.
Typedef Documentation
pending_callback_t
typedef struct pending_callback pending_callback_t
Function Documentation
client_connect_callback()
static void client_connect_callback (int status, void * ctx) [static]
Definition at line 65 of file uvrpc_client.c.
                                                           {
    uvrpc_client_t* client = (uvrpc_client_t*)ctx;
    client->is_connected = (status == 0);
    
    /* Call user's connect callback if provided */
    if (client->user_connect_callback) {
        uvrpc_connect_callback_t cb = client->user_connect_callback;
        client->user_connect_callback = NULL;
        cb(status, client->user_connect_ctx);
    }
    
    if (status != 0) {
        fprintf(stderr, "Client connection failed: %d\n", status);
    }
}
References uvrpc_client::is_connected, uvrpc_client::user_connect_callback, and uvrpc_client::user_connect_ctx.
Referenced by uvrpc_client_connect_with_callback(), and uvrpc_client_create().
client_recv_callback()
static void client_recv_callback (const uint8_t * data, size_t size, void * client_ctx, void * server_ctx) [static]
Definition at line 82 of file uvrpc_client.c.
                                                                                                       {
    (void)client_ctx; /* Not used for client mode */
    uvrpc_client_t* client = (uvrpc_client_t*)server_ctx;
    if (!client || !client->uvbus) {
        uvrpc_free(data);
        return;
    }
    /* Get frame type */
    int frame_type = uvrpc_get_frame_type(data, size);
    
    if (frame_type < 0) {
        uvrpc_free(data);
        return;
    }
    uint32_t msgid;
    if (frame_type == 3) {
        /* Decode error frame */
        int32_t error_code = 0;
        char* error_message = NULL;
        if (uvrpc_decode_error(data, size, &msgid, &error_code, &error_message) != UVRPC_OK) {
            uvrpc_free(data);
            return;
        }
        /* Find pending callback using direct indexing with bitmask */
        uint32_t idx = msgid & (client->max_pending_callbacks - 1);
        pending_callback_t* pending = client->pending_callbacks[idx];
        /* Check if callback exists and matches msgid and generation */
        if (pending && pending->msgid == msgid && pending->generation == client->generation) {
            /* Create error response structure */
            uvrpc_response_t resp;
            resp.status = UVRPC_ERROR;
            resp.msgid = msgid;
            resp.error_code = error_code;
            resp.error_message = error_message;
            resp.result = NULL;
            resp.result_size = 0;
            resp.user_data = NULL;
            /* Remove from ring buffer before calling callback (to avoid re-entry) */
            client->pending_callbacks[idx] = NULL;
            /* Call callback */
            if (pending->callback) {
                pending->callback(&resp, pending->ctx);
            }
            /* Free error message */
            if (error_message) {
                uvrpc_free(error_message);
            }
            /* Free pending callback structure */
            uvrpc_free(pending);
        }
        uvrpc_free(data);
        return;
    }
    /* Decode response frame */
    const uint8_t* result = NULL;
    size_t result_size = 0;
    if (uvrpc_decode_response(data, size, &msgid, &result, &result_size) != UVRPC_OK) {
        uvrpc_free(data);
        return;
    }
    /* Find pending callback using direct indexing with bitmask */
    uint32_t idx = msgid & (client->max_pending_callbacks - 1);
    pending_callback_t* pending = client->pending_callbacks[idx];
    
    /* Check if callback exists and matches msgid and generation */
    if (pending && pending->msgid == msgid && pending->generation == client->generation) {
        /* Create response structure */
        uvrpc_response_t resp;
        resp.status = UVRPC_OK;
        resp.msgid = msgid;
        resp.error_code = 0;
        resp.error_message = NULL;
        /* Copy result data to avoid use-after-free */
        uint8_t* result_copy = NULL;
        if (result && result_size > 0) {
            result_copy = uvrpc_alloc(result_size);
            if (result_copy) {
                memcpy(result_copy, result, result_size);
            }
        }
        resp.result = result_copy;
        resp.result_size = result_size;
        resp.user_data = NULL;
        /* Remove from ring buffer before calling callback (to avoid re-entry) */
        client->pending_callbacks[idx] = NULL;
        /* Call callback */
        if (pending->callback) {
            pending->callback(&resp, pending->ctx);
        }
        /* Free copied result AFTER callback returns */
        if (result_copy) {
            uvrpc_free(result_copy);
        }
        /* Free pending callback structure */
        uvrpc_free(pending);
        /* Decrease concurrent count */
            client->current_concurrent--;
            }
        
            /* NOTE: data is freed by the transport layer (uvbus_transport_tcp.c:181)
             * after the callback returns. Do NOT free it here to avoid double free. */}
References pending_callback::callback, uvrpc_client::current_concurrent, uvrpc_response::error_code, uvrpc_response::error_message, uvrpc_client::generation, uvrpc_client::max_pending_callbacks, uvrpc_response::msgid, uvrpc_client::pending_callbacks, uvrpc_response::result, uvrpc_response::result_size, uvrpc_response::status, uvrpc_response::user_data, uvrpc_client::uvbus, uvrpc_alloc(), uvrpc_decode_error(), uvrpc_decode_response(), UVRPC_ERROR, uvrpc_free(), uvrpc_get_frame_type(), and UVRPC_OK.
Referenced by uvrpc_client_create().
uvrpc_client_call_no_retry_internal()
static int uvrpc_client_call_no_retry_internal (uvrpc_client_t * client, const char * method, const uint8_t * params, size_t params_size, uvrpc_callback_t callback, void * ctx) [static]
Definition at line 437 of file uvrpc_client.c.
                                                                                      {
    if (!client || !method) return UVRPC_ERROR_INVALID_PARAM;
    
    if (!client->is_connected) {
        return UVRPC_ERROR_NOT_CONNECTED;
    }
    
    /* Generate message ID using context */
    uint32_t msgid = uvrpc_msgid_next(client->msgid_ctx);
    
    /* Encode request */
    uint8_t* req_data = NULL;
    size_t req_size = 0;
    
    if (uvrpc_encode_request(msgid, method, params, params_size,
                              &req_data, &req_size) != UVRPC_OK) {
        return UVRPC_ERROR;
    }
    
    /* Register callback using direct indexing */
    if (callback) {
        pending_callback_t* pending = uvrpc_calloc(1, sizeof(pending_callback_t));
        if (!pending) {
            uvrpc_free(req_data);
            return UVRPC_ERROR_NO_MEMORY;
        }
        pending->msgid = msgid;
        pending->generation = client->generation;
        pending->callback = callback;
        pending->ctx = ctx;
        /* Direct indexing with bitmask - O(1) */
        uint32_t idx = msgid & (client->max_pending_callbacks - 1);
        pending_callback_t* existing = client->pending_callbacks[idx];
        if (existing == NULL) {
            /* Slot is empty - insert directly */
            client->pending_callbacks[idx] = pending;
        } else if (existing->generation != client->generation) {
            /* Stale entry from previous generation - replace it */
            uvrpc_free(existing);
            client->pending_callbacks[idx] = pending;
        } else {
            /* Slot is occupied by a valid entry - ring buffer is effectively full */
            /* Do NOT block the event loop - return error and let caller handle it */
            uvrpc_free(pending);
            uvrpc_free(req_data);
            return UVRPC_ERROR_CALLBACK_LIMIT;
        }
    }
    /* Send request (must be after callback registration to avoid race conditions) */
    if (client->uvbus) {
        uvbus_send(client->uvbus, req_data, req_size);
    }
    uvrpc_free(req_data);
    return UVRPC_OK;
}
References pending_callback::callback, pending_callback::ctx, pending_callback::generation, uvrpc_client::generation, uvrpc_client::is_connected, uvrpc_client::max_pending_callbacks, pending_callback::msgid, uvrpc_client::msgid_ctx, uvrpc_client::pending_callbacks, uvrpc_client::uvbus, uvbus_send(), uvrpc_calloc(), uvrpc_encode_request(), UVRPC_ERROR, UVRPC_ERROR_CALLBACK_LIMIT, UVRPC_ERROR_INVALID_PARAM, UVRPC_ERROR_NO_MEMORY, UVRPC_ERROR_NOT_CONNECTED, uvrpc_free(), uvrpc_msgid_next(), and UVRPC_OK.
Referenced by uvrpc_client_call(), and uvrpc_client_call_no_retry().