src/uvrpc_async.c File Reference
UVRPC Async/Await Implementation.
Classes
struct retry_context
struct uvrpc_async_ctx
Typedefs
typedef struct retry_context retry_context_t
Functions
static void all_timeout_callback (uv_timer_t *handle)
static void any_timeout_callback (uv_timer_t *handle)
static void async_response_callback (uvrpc_response_t *resp, void *ctx)
static void concurrent_callback (uvrpc_response_t *resp, void *ctx)
static void retry_delay_callback (uv_timer_t *handle)
static void timeout_callback (uv_timer_t *handle)
int uvrpc_async_all (uvrpc_async_ctx_t *ctx, uvrpc_client_t **clients, const char **methods, const uint8_t **params_array, size_t *params_sizes, uvrpc_async_result_t ***results, int count, uint64_t timeout_ms)
int uvrpc_async_any (uvrpc_async_ctx_t *ctx, uvrpc_client_t **clients, const char **methods, const uint8_t **params_array, size_t *params_sizes, uvrpc_async_result_t **result, int *completed_index, int count, uint64_t timeout_ms)
int uvrpc_async_cancel_all (uvrpc_async_ctx_t *ctx)
void uvrpc_async_ctx_free (uvrpc_async_ctx_t *ctx)
uvrpc_async_ctx_t * uvrpc_async_ctx_new (uv_loop_t *loop)
int uvrpc_async_exec (uvrpc_async_ctx_t *ctx, uint64_t timeout_ms)
int uvrpc_async_get_pending_count (uvrpc_async_ctx_t *ctx)
void uvrpc_async_result_free (uvrpc_async_result_t *result)
int uvrpc_async_retry (uvrpc_async_ctx_t *ctx, uvrpc_client_t *client, const char *method, const uint8_t *params, size_t params_size, uvrpc_async_result_t **result, int max_retries, uint64_t retry_delay_ms)
int uvrpc_async_retry_with_backoff (uvrpc_async_ctx_t *ctx, uvrpc_client_t *client, const char *method, const uint8_t *params, size_t params_size, uvrpc_async_result_t **result, int max_retries, uint64_t initial_delay_ms, double backoff_multiplier)
int uvrpc_async_timeout (uvrpc_async_ctx_t *ctx, uvrpc_client_t *client, const char *method, const uint8_t *params, size_t params_size, uvrpc_async_result_t **result, uint64_t timeout_ms)
int uvrpc_client_call_async (uvrpc_async_ctx_t *ctx, uvrpc_client_t *client, const char *method, const uint8_t *params, size_t params_size, uvrpc_async_result_t **result)
Detailed Description
UVRPC Async/Await Implementation.
Provides coroutine-like async/await syntax using libuv and setjmp/longjmp.
Author
UVRPC Team
Date
2026
Version
1.0
Definition in file uvrpc_async.c.
Typedef Documentation
retry_context_t
typedef struct retry_context retry_context_t
Function Documentation
all_timeout_callback()
static void all_timeout_callback (uv_timer_t * handle) [static]
Definition at line 286 of file uvrpc_async.c.
                                                     {
    int* timed_out = (int*)handle->data;
    *timed_out = 1;
}
Referenced by uvrpc_async_all().
any_timeout_callback()
static void any_timeout_callback (uv_timer_t * handle) [static]
Definition at line 364 of file uvrpc_async.c.
                                                     {
    int* timed_out = (int*)handle->data;
    *timed_out = 1;
}
Referenced by uvrpc_async_any().
async_response_callback()
static void async_response_callback (uvrpc_response_t * resp, void * ctx) [static]
Definition at line 74 of file uvrpc_async.c.
                                                                       {
    uvrpc_async_ctx_t* async_ctx = (uvrpc_async_ctx_t*)ctx;
    
    if (async_ctx->current_call < 0 || async_ctx->current_call >= UVRPC_MAX_ASYNC_CALLS) {
        return;
    }
    
    /* Store result */
    uvrpc_async_result_t* result = uvrpc_alloc(sizeof(uvrpc_async_result_t));
    if (!result) {
        longjmp(async_ctx->jmp_buf, UVRPC_ERROR_NO_MEMORY);
    }
    
    result->status = resp->status;
    result->msgid = resp->msgid;
    result->error_code = resp->error_code;
    result->user_data = resp->user_data;
    
    if (resp->result && resp->result_size > 0) {
        result->result = uvrpc_alloc(resp->result_size);
        if (result->result) {
            memcpy(result->result, resp->result, resp->result_size);
            result->result_size = resp->result_size;
        } else {
            result->result_size = 0;
        }
    } else {
        result->result = NULL;
        result->result_size = 0;
    }
    
    async_ctx->pending_results[async_ctx->current_call] = result;
    
    /* Jump back to continue execution */
    longjmp(async_ctx->jmp_buf, UVRPC_OK);
}
References uvrpc_async_ctx::current_call, uvrpc_response::error_code, uvrpc_async_result::error_code, uvrpc_async_ctx::jmp_buf, uvrpc_response::msgid, uvrpc_async_result::msgid, uvrpc_async_ctx::pending_results, uvrpc_response::result, uvrpc_async_result::result, uvrpc_response::result_size, uvrpc_async_result::result_size, uvrpc_response::status, uvrpc_async_result::status, uvrpc_response::user_data, uvrpc_async_result::user_data, uvrpc_alloc(), UVRPC_ERROR_NO_MEMORY, and UVRPC_OK.
Referenced by uvrpc_client_call_async().
concurrent_callback()
static void concurrent_callback (uvrpc_response_t * resp, void * ctx) [static]
Definition at line 250 of file uvrpc_async.c.
                                                                   {
    uvrpc_async_ctx_t* async_ctx = (uvrpc_async_ctx_t*)ctx;
    int index = (int)(intptr_t)resp->user_data;
    
    /* Store result */
    uvrpc_async_result_t* result = uvrpc_alloc(sizeof(uvrpc_async_result_t));
    if (!result) return;
    
    result->status = resp->status;
    result->msgid = resp->msgid;
    result->error_code = resp->error_code;
    
    if (resp->result && resp->result_size > 0) {
        result->result = uvrpc_alloc(resp->result_size);
        if (result->result) {
            memcpy(result->result, resp->result, resp->result_size);
            result->result_size = resp->result_size;
        } else {
            result->result_size = 0;
        }
    } else {
        result->result = NULL;
        result->result_size = 0;
    }
    
    async_ctx->concurrent_results[index] = result;
    async_ctx->completed_count++;
    
    /* For any() - jump back immediately */
    if (!async_ctx->any_completed && async_ctx->completed_count >= 1) {
        async_ctx->any_completed = 1;
        longjmp(async_ctx->any_jmp_buf, UVRPC_OK);
    }
}
References uvrpc_async_ctx::any_completed, uvrpc_async_ctx::any_jmp_buf, uvrpc_async_ctx::completed_count, uvrpc_async_ctx::concurrent_results, uvrpc_response::error_code, uvrpc_async_result::error_code, uvrpc_response::msgid, uvrpc_async_result::msgid, uvrpc_response::result, uvrpc_async_result::result, uvrpc_response::result_size, uvrpc_async_result::result_size, uvrpc_response::status, uvrpc_async_result::status, uvrpc_response::user_data, uvrpc_alloc(), and UVRPC_OK.
Referenced by uvrpc_async_all(), and uvrpc_async_any().
retry_delay_callback()
static void retry_delay_callback (uv_timer_t * handle) [static]
Definition at line 39 of file uvrpc_async.c.
                                                     {
    retry_context_t* retry_ctx = (retry_context_t*)handle->data;
    /* Retry the call */
    uvrpc_client_call_async(retry_ctx->ctx, retry_ctx->client, retry_ctx->method,
                           retry_ctx->params, retry_ctx->params_size, retry_ctx->result);
    /* Cleanup retry context */
    uvrpc_free(retry_ctx->method);
    uvrpc_free(retry_ctx->params);
    uvrpc_free(retry_ctx);
}
References retry_context::client, retry_context::ctx, retry_context::method, retry_context::params, retry_context::params_size, retry_context::result, uvrpc_client_call_async(), and uvrpc_free().
Referenced by uvrpc_async_retry(), and uvrpc_async_retry_with_backoff().
timeout_callback()
static void timeout_callback (uv_timer_t * handle) [static]
Definition at line 112 of file uvrpc_async.c.
                                                 {
    uvrpc_async_ctx_t* async_ctx = (uvrpc_async_ctx_t*)handle->data;
    async_ctx->timed_out = 1;
    longjmp(async_ctx->jmp_buf, UVRPC_ERROR_TIMEOUT);
}
References uvrpc_async_ctx::jmp_buf, uvrpc_async_ctx::timed_out, and UVRPC_ERROR_TIMEOUT.
Referenced by uvrpc_async_exec(), and uvrpc_async_timeout().
uvrpc_async_all()
int uvrpc_async_all (uvrpc_async_ctx_t * ctx, uvrpc_client_t ** clients, const char ** methods, const uint8_t ** params_array, size_t * params_sizes, uvrpc_async_result_t *** results, int count, uint64_t timeout_ms)
Execute multiple async calls concurrently and wait for all to complete (Promise.all)
Parameters
ctx async context
clients array of RPC clients
methods array of method names
params_array array of parameters
params_sizes array of parameter sizes
results output array of results (caller must free each result)
count number of calls
timeout_ms timeout in milliseconds (0 for no timeout)
Returns
UVRPC_OK on success, UVRPC_ERROR_TIMEOUT on timeout
Definition at line 292 of file uvrpc_async.c.
                                          {
    if (!ctx || !clients || !methods || !params_array || !params_sizes || !results) {
        return UVRPC_ERROR_INVALID_PARAM;
    }
    
    if (count <= 0 || count > UVRPC_MAX_CONCURRENT_CALLS) {
        return UVRPC_ERROR_INVALID_PARAM;
    }
    
    /* Initialize concurrent state */
    ctx->concurrent_count = count;
    ctx->completed_count = 0;
    ctx->any_completed = 0;
    for (int i = 0; i < count; i++) {
        ctx->concurrent_results[i] = NULL;
    }
    
    /* Setup timeout */
    uv_timer_t timeout_timer;
    int timed_out = 0;
    if (timeout_ms > 0) {
        uv_timer_init(ctx->loop, &timeout_timer);
        timeout_timer.data = &timed_out;
        uv_timer_start(&timeout_timer, all_timeout_callback, timeout_ms, 0);
    }
    
    /* Start all concurrent calls */
    for (int i = 0; i < count; i++) {
        uvrpc_response_t* resp_wrapper = uvrpc_alloc(sizeof(uvrpc_response_t));
        resp_wrapper->user_data = (void*)(intptr_t)i;
        
        uvrpc_client_call(clients[i], methods[i], params_array[i], params_sizes[i],
                          concurrent_callback, ctx);
    }
    
    /* Wait for all to complete */
    while (ctx->completed_count < count && !timed_out) {
        uv_run(ctx->loop, UV_RUN_ONCE);
    }
    
    /* Stop timeout */
    if (timeout_ms > 0) {
        uv_timer_stop(&timeout_timer);
        uv_close((uv_handle_t*)&timeout_timer, NULL);
    }
    
    if (timed_out) {
        return UVRPC_ERROR_TIMEOUT;
    }
    
    /* Allocate results array */
    *results = uvrpc_alloc(sizeof(uvrpc_async_result_t*) * count);
    if (!*results) {
        return UVRPC_ERROR_NO_MEMORY;
    }
    
    for (int i = 0; i < count; i++) {
        (*results)[i] = ctx->concurrent_results[i];
        ctx->concurrent_results[i] = NULL;
    }
    
    return UVRPC_OK;
}
References all_timeout_callback(), uvrpc_async_ctx::any_completed, uvrpc_async_ctx::completed_count, concurrent_callback(), uvrpc_async_ctx::concurrent_count, uvrpc_async_ctx::concurrent_results, uvrpc_async_ctx::loop, uvrpc_response::user_data, uvrpc_alloc(), uvrpc_client_call(), UVRPC_ERROR_INVALID_PARAM, UVRPC_ERROR_NO_MEMORY, UVRPC_ERROR_TIMEOUT, and UVRPC_OK.
uvrpc_async_any()
int uvrpc_async_any (uvrpc_async_ctx_t * ctx, uvrpc_client_t ** clients, const char ** methods, const uint8_t ** params_array, size_t * params_sizes, uvrpc_async_result_t ** result, int * completed_index, int count, uint64_t timeout_ms)
Execute multiple async calls concurrently and wait for any to complete (Promise.any)
Parameters
ctx async context
clients array of RPC clients
methods array of method names
params_array array of parameters
params_sizes array of parameter sizes
result output result (caller must free)
completed_index index of the completed call
count number of calls
timeout_ms timeout in milliseconds (0 for no timeout)
Returns
UVRPC_OK on success, UVRPC_ERROR_TIMEOUT on timeout
Definition at line 370 of file uvrpc_async.c.
                                          {
    if (!ctx || !clients || !methods || !params_array || !params_sizes || !result) {
        return UVRPC_ERROR_INVALID_PARAM;
    }
    
    if (count <= 0 || count > UVRPC_MAX_CONCURRENT_CALLS) {
        return UVRPC_ERROR_INVALID_PARAM;
    }
    
    /* Initialize concurrent state */
    ctx->concurrent_count = count;
    ctx->completed_count = 0;
    ctx->any_completed = 0;
    for (int i = 0; i < count; i++) {
        ctx->concurrent_results[i] = NULL;
    }
    
    /* Setup timeout */
    uv_timer_t timeout_timer;
    int timed_out = 0;
    if (timeout_ms > 0) {
        uv_timer_init(ctx->loop, &timeout_timer);
        timeout_timer.data = &timed_out;
        uv_timer_start(&timeout_timer, any_timeout_callback, timeout_ms, 0);
    }
    
    /* Set jump point */
    int jump_status = setjmp(ctx->any_jmp_buf);
    
    if (jump_status == 0) {
        /* Start all concurrent calls */
        for (int i = 0; i < count; i++) {
            uvrpc_client_call(clients[i], methods[i], params_array[i], params_sizes[i],
                              concurrent_callback, ctx);
        }
        
        /* Wait for any to complete */
        while (!ctx->any_completed && !timed_out) {
            uv_run(ctx->loop, UV_RUN_ONCE);
        }
        
        /* Check if timeout occurred */
        if (timed_out) {
            if (timeout_ms > 0) {
                uv_timer_stop(&timeout_timer);
                uv_close((uv_handle_t*)&timeout_timer, NULL);
            }
            return UVRPC_ERROR_TIMEOUT;
        }
        
        /* Shouldn't reach here normally */
        return UVRPC_ERROR_TIMEOUT;
    } else {
        /* Jumped back from callback or timeout */
        
        if (timeout_ms > 0) {
            uv_timer_stop(&timeout_timer);
            uv_close((uv_handle_t*)&timeout_timer, NULL);
        }
        
        if (jump_status == UVRPC_ERROR_TIMEOUT) {
            return UVRPC_ERROR_TIMEOUT;
        }
        
        /* Find completed result */
        for (int i = 0; i < count; i++) {
            if (ctx->concurrent_results[i]) {
                *result = ctx->concurrent_results[i];
                *completed_index = i;
                ctx->concurrent_results[i] = NULL;
                break;
            }
        }
        
        return UVRPC_OK;
    }
}
References uvrpc_async_ctx::any_completed, uvrpc_async_ctx::any_jmp_buf, any_timeout_callback(), uvrpc_async_ctx::completed_count, concurrent_callback(), uvrpc_async_ctx::concurrent_count, uvrpc_async_ctx::concurrent_results, uvrpc_async_ctx::loop, uvrpc_client_call(), UVRPC_ERROR_INVALID_PARAM, UVRPC_ERROR_TIMEOUT, and UVRPC_OK.
uvrpc_async_cancel_all()
int uvrpc_async_cancel_all (uvrpc_async_ctx_t * ctx)
Cancel pending async operations
Parameters
ctx async context
Returns
UVRPC_OK on success
Definition at line 611 of file uvrpc_async.c.
                                                   {
    if (!ctx) return UVRPC_ERROR_INVALID_PARAM;
    /* Stop timeout timer if running */
    if (ctx->timeout_ms > 0 && !uv_is_closing((uv_handle_t*)&ctx->timeout_timer)) {
        uv_timer_stop(&ctx->timeout_timer);
        uv_close((uv_handle_t*)&ctx->timeout_timer, NULL);
    }
    /* Free all pending results */
    for (int i = 0; i < UVRPC_MAX_ASYNC_CALLS; i++) {
        if (ctx->pending_results[i]) {
            uvrpc_async_result_free(ctx->pending_results[i]);
            ctx->pending_results[i] = NULL;
        }
    }
    /* Reset state */
    ctx->call_count = 0;
    ctx->current_call = -1;
    ctx->is_running = 0;
    return UVRPC_OK;
}
References uvrpc_async_ctx::call_count, uvrpc_async_ctx::current_call, uvrpc_async_ctx::is_running, uvrpc_async_ctx::pending_results, uvrpc_async_ctx::timeout_ms, uvrpc_async_ctx::timeout_timer, uvrpc_async_result_free(), UVRPC_ERROR_INVALID_PARAM, and UVRPC_OK.
uvrpc_async_ctx_free()
void uvrpc_async_ctx_free (uvrpc_async_ctx_t * ctx)
Free async context
Parameters
ctx async context
Definition at line 137 of file uvrpc_async.c.
                                                  {
    if (!ctx) return;
    
    /* Free pending results */
    for (int i = 0; i < UVRPC_MAX_ASYNC_CALLS; i++) {
        if (ctx->pending_results[i]) {
            uvrpc_async_result_free(ctx->pending_results[i]);
            ctx->pending_results[i] = NULL;
        }
    }
    
    uvrpc_free(ctx);
}
References uvrpc_async_ctx::pending_results, uvrpc_async_result_free(), and uvrpc_free().
uvrpc_async_ctx_new()
uvrpc_async_ctx_t * uvrpc_async_ctx_new (uv_loop_t * loop)
Create async context
Parameters
loop libuv event loop
Returns
async context
Definition at line 119 of file uvrpc_async.c.
                                                        {
    if (!loop) return NULL;
    
    uvrpc_async_ctx_t* ctx = uvrpc_alloc(sizeof(uvrpc_async_ctx_t));
    if (!ctx) return NULL;
    
    memset(ctx, 0, sizeof(uvrpc_async_ctx_t));
    ctx->loop = loop;
    ctx->is_running = 0;
    ctx->call_count = 0;
    ctx->current_call = -1;
    ctx->timeout_ms = 0;
    ctx->timed_out = 0;
    
    return ctx;
}
References uvrpc_async_ctx::call_count, uvrpc_async_ctx::current_call, uvrpc_async_ctx::is_running, uvrpc_async_ctx::loop, uvrpc_async_ctx::timed_out, uvrpc_async_ctx::timeout_ms, and uvrpc_alloc().
uvrpc_async_exec()
int uvrpc_async_exec (uvrpc_async_ctx_t * ctx, uint64_t timeout_ms)
Execute async block
Parameters
ctx async context
timeout_ms timeout in milliseconds (0 for no timeout)
Returns
UVRPC_OK on success, error code on failure
Definition at line 152 of file uvrpc_async.c.
                                                                  {
    if (!ctx || ctx->is_running) return UVRPC_ERROR_INVALID_PARAM;
    
    ctx->is_running = 1;
    ctx->timeout_ms = timeout_ms;
    ctx->timed_out = 0;
    
    /* Start timeout timer if specified */
    if (timeout_ms > 0) {
        uv_timer_init(ctx->loop, &ctx->timeout_timer);
        ctx->timeout_timer.data = ctx;
        uv_timer_start(&ctx->timeout_timer, timeout_callback, timeout_ms, 0);
    }
    
    return UVRPC_OK;
}
References uvrpc_async_ctx::is_running, uvrpc_async_ctx::loop, uvrpc_async_ctx::timed_out, timeout_callback(), uvrpc_async_ctx::timeout_ms, uvrpc_async_ctx::timeout_timer, UVRPC_ERROR_INVALID_PARAM, and UVRPC_OK.
uvrpc_async_get_pending_count()
int uvrpc_async_get_pending_count (uvrpc_async_ctx_t * ctx)
Get number of pending async operations
Parameters
ctx async context
Returns
number of pending operations
Definition at line 637 of file uvrpc_async.c.
                                                          {
    if (!ctx) return 0;
    int count = 0;
    for (int i = 0; i < UVRPC_MAX_ASYNC_CALLS; i++) {
        if (ctx->pending_results[i] != NULL) {
            count++;
        }
    }
    return count;
}
References uvrpc_async_ctx::pending_results.
uvrpc_async_result_free()
void uvrpc_async_result_free (uvrpc_async_result_t * result)
Free async result
Parameters
result result to free
Definition at line 239 of file uvrpc_async.c.
                                                           {
    if (!result) return;
    
    if (result->result) {
        uvrpc_free(result->result);
    }
    
    uvrpc_free(result);
}
References uvrpc_async_result::result, and uvrpc_free().
Referenced by uvrpc_async_cancel_all(), uvrpc_async_ctx_free(), uvrpc_async_retry(), and uvrpc_async_retry_with_backoff().
uvrpc_async_retry()
int uvrpc_async_retry (uvrpc_async_ctx_t * ctx, uvrpc_client_t * client, const char * method, const uint8_t * params, size_t params_size, uvrpc_async_result_t ** result, int max_retries, uint64_t retry_delay_ms)
Definition at line 457 of file uvrpc_async.c.
                                                                 {
    if (!ctx || !client || !method || !result) {
        return UVRPC_ERROR_INVALID_PARAM;
    }
    
    if (max_retries < 0) max_retries = 3;
    
    for (int attempt = 0; attempt <= max_retries; attempt++) {
        int status = uvrpc_client_call_async(ctx, client, method, params, params_size, result);
        
        if (status == UVRPC_OK && *result && (*result)->error_code == 0) {
            return UVRPC_OK;
        }
        
        if (*result) {
            uvrpc_async_result_free(*result);
            *result = NULL;
        }
        
        if (attempt < max_retries && retry_delay_ms > 0) {
            /* Non-blocking delay using timer - return to caller, retry will be triggered by timer */
            /* Store retry context for timer callback */
            retry_context_t* retry_ctx = uvrpc_alloc(sizeof(retry_context_t));
            if (!retry_ctx) {
                return UVRPC_ERROR;
            }
            retry_ctx->client = client;
            retry_ctx->method = uvrpc_strdup(method);
            retry_ctx->params = uvrpc_alloc(params_size);
            if (!retry_ctx->method || !retry_ctx->params) {
                uvrpc_free(retry_ctx->method);
                uvrpc_free(retry_ctx->params);
                uvrpc_free(retry_ctx);
                return UVRPC_ERROR;
            }
            memcpy(retry_ctx->params, params, params_size);
            retry_ctx->params_size = params_size;
            retry_ctx->result = result;
            retry_ctx->attempt = attempt;
            retry_ctx->max_retries = max_retries;
            retry_ctx->retry_delay_ms = retry_delay_ms;
            retry_ctx->ctx = ctx;
            
            uv_timer_init(ctx->loop, &retry_ctx->timer);
            retry_ctx->timer.data = retry_ctx;
            uv_timer_start(&retry_ctx->timer, retry_delay_callback, retry_delay_ms, 0);
            
            return UVRPC_ERROR; /* Will retry via timer */
        }
    }
    
    return UVRPC_ERROR;
}
References retry_context::attempt, retry_context::client, retry_context::ctx, uvrpc_async_result::error_code, uvrpc_async_ctx::loop, retry_context::max_retries, retry_context::method, retry_context::params, retry_context::params_size, retry_context::result, retry_delay_callback(), retry_context::retry_delay_ms, retry_context::timer, uvrpc_alloc(), uvrpc_async_result_free(), uvrpc_client_call_async(), UVRPC_ERROR, UVRPC_ERROR_INVALID_PARAM, uvrpc_free(), UVRPC_OK, and uvrpc_strdup().
uvrpc_async_retry_with_backoff()
int uvrpc_async_retry_with_backoff (uvrpc_async_ctx_t * ctx, uvrpc_client_t * client, const char * method, const uint8_t * params, size_t params_size, uvrpc_async_result_t ** result, int max_retries, uint64_t initial_delay_ms, double backoff_multiplier)
Execute async call with retry and exponential backoff (Promise.retry)
Parameters
ctx async context
client RPC client
method method name
params request parameters
params_size parameter size
result output result pointer
max_retries maximum number of retries
initial_delay_ms initial delay between retries in milliseconds
backoff_multiplier multiplier for exponential backoff (e.g., 2.0)
Returns
UVRPC_OK on success, error code on failure
Definition at line 548 of file uvrpc_async.c.
                                                              {
    if (!ctx || !client || !method || !result) {
        return UVRPC_ERROR_INVALID_PARAM;
    }
    if (max_retries < 0) max_retries = 3;
    if (initial_delay_ms == 0) initial_delay_ms = 100;
    if (backoff_multiplier < 1.0) backoff_multiplier = 2.0;
    for (int attempt = 0; attempt <= max_retries; attempt++) {
        int status = uvrpc_client_call_async(ctx, client, method, params, params_size, result);
        if (status == UVRPC_OK && *result && (*result)->error_code == 0) {
            return UVRPC_OK;
        }
        if (*result) {
            uvrpc_async_result_free(*result);
            *result = NULL;
        }
        if (attempt < max_retries) {
            /* Calculate delay with exponential backoff */
            uint64_t delay_ms = (uint64_t)(initial_delay_ms * pow(backoff_multiplier, attempt));
            /* Non-blocking delay using timer */
            retry_context_t* retry_ctx = uvrpc_alloc(sizeof(retry_context_t));
            if (!retry_ctx) {
                return UVRPC_ERROR;
            }
            retry_ctx->client = client;
            retry_ctx->method = uvrpc_strdup(method);
            retry_ctx->params = uvrpc_alloc(params_size);
            if (!retry_ctx->method || !retry_ctx->params) {
                uvrpc_free(retry_ctx->method);
                uvrpc_free(retry_ctx->params);
                uvrpc_free(retry_ctx);
                return UVRPC_ERROR;
            }
            memcpy(retry_ctx->params, params, params_size);
            retry_ctx->params_size = params_size;
            retry_ctx->result = result;
            retry_ctx->attempt = attempt;
            retry_ctx->max_retries = max_retries;
            retry_ctx->retry_delay_ms = delay_ms;
            retry_ctx->ctx = ctx;
            uv_timer_init(ctx->loop, &retry_ctx->timer);
            retry_ctx->timer.data = retry_ctx;
            uv_timer_start(&retry_ctx->timer, retry_delay_callback, delay_ms, 0);
            return UVRPC_ERROR; /* Will retry via timer */
        }
    }
    return UVRPC_ERROR;
}
References retry_context::attempt, retry_context::client, retry_context::ctx, uvrpc_async_result::error_code, uvrpc_async_ctx::loop, retry_context::max_retries, retry_context::method, retry_context::params, retry_context::params_size, retry_context::result, retry_delay_callback(), retry_context::retry_delay_ms, retry_context::timer, uvrpc_alloc(), uvrpc_async_result_free(), uvrpc_client_call_async(), UVRPC_ERROR, UVRPC_ERROR_INVALID_PARAM, uvrpc_free(), UVRPC_OK, and uvrpc_strdup().
uvrpc_async_timeout()
int uvrpc_async_timeout (uvrpc_async_ctx_t * ctx, uvrpc_client_t * client, const char * method, const uint8_t * params, size_t params_size, uvrpc_async_result_t ** result, uint64_t timeout_ms)
Execute async call with timeout (Promise.timeout)
Parameters
ctx async context
client RPC client
method method name
params request parameters
params_size parameter size
result output result pointer
timeout_ms timeout in milliseconds
Returns
UVRPC_OK on success, UVRPC_ERROR_TIMEOUT on timeout
Definition at line 515 of file uvrpc_async.c.
                                              {
    if (!ctx || !client || !method || !result) {
        return UVRPC_ERROR_INVALID_PARAM;
    }
    
    /* Start the call */
    int started = setjmp(ctx->jmp_buf);
    
    if (started == 0) {
        /* Setup timeout */
        if (timeout_ms > 0) {
            uv_timer_init(ctx->loop, &ctx->timeout_timer);
            ctx->timeout_timer.data = ctx;
            ctx->timed_out = 0;
            uv_timer_start(&ctx->timeout_timer, timeout_callback, timeout_ms, 0);
        }
        /* Make the call */
        return uvrpc_client_call_async(ctx, client, method, params, params_size, result);
    } else {
        /* Jumped from timeout */
        if (ctx->timeout_ms > 0) {
            uv_timer_stop(&ctx->timeout_timer);
            uv_close((uv_handle_t*)&ctx->timeout_timer, NULL);
        }
        return UVRPC_ERROR_TIMEOUT;
    }
}
References uvrpc_async_ctx::jmp_buf, uvrpc_async_ctx::loop, uvrpc_async_ctx::timed_out, timeout_callback(), uvrpc_async_ctx::timeout_ms, uvrpc_async_ctx::timeout_timer, uvrpc_client_call_async(), UVRPC_ERROR_INVALID_PARAM, and UVRPC_ERROR_TIMEOUT.
uvrpc_client_call_async()
int uvrpc_client_call_async (uvrpc_async_ctx_t * ctx, uvrpc_client_t * client, const char * method, const uint8_t * params, size_t params_size, uvrpc_async_result_t ** result)
Client call with async/await This function should be called within UVRPC_ASYNC block
Parameters
client RPC client
method method name
params request parameters
params_size parameter size
result output result pointer
Returns
UVRPC_OK on success
Definition at line 170 of file uvrpc_async.c.
                                                                                {
    if (!ctx || !client || !method || !result) {
        return UVRPC_ERROR_INVALID_PARAM;
    }
    
    if (!ctx->is_running) {
        return UVRPC_ERROR;
    }
    
    /* Find free slot for result */
    int slot = -1;
    for (int i = 0; i < UVRPC_MAX_ASYNC_CALLS; i++) {
        if (ctx->pending_results[i] == NULL) {
            slot = i;
            break;
        }
    }
    
    if (slot < 0) {
        return UVRPC_ERROR_NO_MEMORY;
    }
    
    /* Set current call index */
    ctx->current_call = slot;
    
    /* Save jump point */
    int jump_status = setjmp(ctx->jmp_buf);
    
    if (jump_status == 0) {
        /* First call: make RPC request */
        int call_status = uvrpc_client_call(client, method, params, params_size,
                                             async_response_callback, ctx);
        if (call_status != UVRPC_OK) {
            ctx->current_call = -1;
            return call_status;
        }
        
        /* Run event loop to wait for response */
        while (ctx->pending_results[slot] == NULL && !ctx->timed_out) {
            uv_run(ctx->loop, UV_RUN_ONCE);
        }
        
        /* This shouldn't happen, but handle it */
        ctx->current_call = -1;
        return UVRPC_ERROR_TIMEOUT;
    } else {
        /* Jump back from callback */
        ctx->current_call = -1;
        
        if (jump_status == UVRPC_ERROR_TIMEOUT) {
            /* Handle timeout */
            if (ctx->timeout_ms > 0) {
                uv_timer_stop(&ctx->timeout_timer);
                uv_close((uv_handle_t*)&ctx->timeout_timer, NULL);
            }
            return UVRPC_ERROR_TIMEOUT;
        }
        
        /* Return result */
        *result = ctx->pending_results[slot];
        ctx->pending_results[slot] = NULL;
        
        return UVRPC_OK;
    }
}
References async_response_callback(), uvrpc_async_ctx::current_call, uvrpc_async_ctx::is_running, uvrpc_async_ctx::jmp_buf, uvrpc_async_ctx::loop, uvrpc_async_ctx::pending_results, uvrpc_async_ctx::timed_out, uvrpc_async_ctx::timeout_ms, uvrpc_async_ctx::timeout_timer, uvrpc_client_call(), UVRPC_ERROR, UVRPC_ERROR_INVALID_PARAM, UVRPC_ERROR_NO_MEMORY, UVRPC_ERROR_TIMEOUT, and UVRPC_OK.
Referenced by retry_delay_callback(), uvrpc_async_retry(), uvrpc_async_retry_with_backoff(), and uvrpc_async_timeout().