# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zhaodi-chen/project/uvrpc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zhaodi-chen/project/uvrpc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zhaodi-chen/project/uvrpc/CMakeFiles /home/zhaodi-chen/project/uvrpc//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zhaodi-chen/project/uvrpc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named msgpackc

# Build rule for target.
msgpackc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 msgpackc
.PHONY : msgpackc

# fast build rule for target.
msgpackc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/build
.PHONY : msgpackc/fast

#=============================================================================
# Target rules for targets named test_server

# Build rule for target.
test_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_server
.PHONY : test_server

# fast build rule for target.
test_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/build
.PHONY : test_server/fast

#=============================================================================
# Target rules for targets named test_client

# Build rule for target.
test_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_client
.PHONY : test_client

# fast build rule for target.
test_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_client.dir/build.make CMakeFiles/test_client.dir/build
.PHONY : test_client/fast

deps/msgpack-c/src/mpack/mpack-common.o: deps/msgpack-c/src/mpack/mpack-common.c.o
.PHONY : deps/msgpack-c/src/mpack/mpack-common.o

# target to build an object file
deps/msgpack-c/src/mpack/mpack-common.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-common.c.o
.PHONY : deps/msgpack-c/src/mpack/mpack-common.c.o

deps/msgpack-c/src/mpack/mpack-common.i: deps/msgpack-c/src/mpack/mpack-common.c.i
.PHONY : deps/msgpack-c/src/mpack/mpack-common.i

# target to preprocess a source file
deps/msgpack-c/src/mpack/mpack-common.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-common.c.i
.PHONY : deps/msgpack-c/src/mpack/mpack-common.c.i

deps/msgpack-c/src/mpack/mpack-common.s: deps/msgpack-c/src/mpack/mpack-common.c.s
.PHONY : deps/msgpack-c/src/mpack/mpack-common.s

# target to generate assembly for a file
deps/msgpack-c/src/mpack/mpack-common.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-common.c.s
.PHONY : deps/msgpack-c/src/mpack/mpack-common.c.s

deps/msgpack-c/src/mpack/mpack-expect.o: deps/msgpack-c/src/mpack/mpack-expect.c.o
.PHONY : deps/msgpack-c/src/mpack/mpack-expect.o

# target to build an object file
deps/msgpack-c/src/mpack/mpack-expect.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-expect.c.o
.PHONY : deps/msgpack-c/src/mpack/mpack-expect.c.o

deps/msgpack-c/src/mpack/mpack-expect.i: deps/msgpack-c/src/mpack/mpack-expect.c.i
.PHONY : deps/msgpack-c/src/mpack/mpack-expect.i

# target to preprocess a source file
deps/msgpack-c/src/mpack/mpack-expect.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-expect.c.i
.PHONY : deps/msgpack-c/src/mpack/mpack-expect.c.i

deps/msgpack-c/src/mpack/mpack-expect.s: deps/msgpack-c/src/mpack/mpack-expect.c.s
.PHONY : deps/msgpack-c/src/mpack/mpack-expect.s

# target to generate assembly for a file
deps/msgpack-c/src/mpack/mpack-expect.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-expect.c.s
.PHONY : deps/msgpack-c/src/mpack/mpack-expect.c.s

deps/msgpack-c/src/mpack/mpack-node.o: deps/msgpack-c/src/mpack/mpack-node.c.o
.PHONY : deps/msgpack-c/src/mpack/mpack-node.o

# target to build an object file
deps/msgpack-c/src/mpack/mpack-node.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-node.c.o
.PHONY : deps/msgpack-c/src/mpack/mpack-node.c.o

deps/msgpack-c/src/mpack/mpack-node.i: deps/msgpack-c/src/mpack/mpack-node.c.i
.PHONY : deps/msgpack-c/src/mpack/mpack-node.i

# target to preprocess a source file
deps/msgpack-c/src/mpack/mpack-node.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-node.c.i
.PHONY : deps/msgpack-c/src/mpack/mpack-node.c.i

deps/msgpack-c/src/mpack/mpack-node.s: deps/msgpack-c/src/mpack/mpack-node.c.s
.PHONY : deps/msgpack-c/src/mpack/mpack-node.s

# target to generate assembly for a file
deps/msgpack-c/src/mpack/mpack-node.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-node.c.s
.PHONY : deps/msgpack-c/src/mpack/mpack-node.c.s

deps/msgpack-c/src/mpack/mpack-platform.o: deps/msgpack-c/src/mpack/mpack-platform.c.o
.PHONY : deps/msgpack-c/src/mpack/mpack-platform.o

# target to build an object file
deps/msgpack-c/src/mpack/mpack-platform.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-platform.c.o
.PHONY : deps/msgpack-c/src/mpack/mpack-platform.c.o

deps/msgpack-c/src/mpack/mpack-platform.i: deps/msgpack-c/src/mpack/mpack-platform.c.i
.PHONY : deps/msgpack-c/src/mpack/mpack-platform.i

# target to preprocess a source file
deps/msgpack-c/src/mpack/mpack-platform.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-platform.c.i
.PHONY : deps/msgpack-c/src/mpack/mpack-platform.c.i

deps/msgpack-c/src/mpack/mpack-platform.s: deps/msgpack-c/src/mpack/mpack-platform.c.s
.PHONY : deps/msgpack-c/src/mpack/mpack-platform.s

# target to generate assembly for a file
deps/msgpack-c/src/mpack/mpack-platform.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-platform.c.s
.PHONY : deps/msgpack-c/src/mpack/mpack-platform.c.s

deps/msgpack-c/src/mpack/mpack-reader.o: deps/msgpack-c/src/mpack/mpack-reader.c.o
.PHONY : deps/msgpack-c/src/mpack/mpack-reader.o

# target to build an object file
deps/msgpack-c/src/mpack/mpack-reader.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-reader.c.o
.PHONY : deps/msgpack-c/src/mpack/mpack-reader.c.o

deps/msgpack-c/src/mpack/mpack-reader.i: deps/msgpack-c/src/mpack/mpack-reader.c.i
.PHONY : deps/msgpack-c/src/mpack/mpack-reader.i

# target to preprocess a source file
deps/msgpack-c/src/mpack/mpack-reader.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-reader.c.i
.PHONY : deps/msgpack-c/src/mpack/mpack-reader.c.i

deps/msgpack-c/src/mpack/mpack-reader.s: deps/msgpack-c/src/mpack/mpack-reader.c.s
.PHONY : deps/msgpack-c/src/mpack/mpack-reader.s

# target to generate assembly for a file
deps/msgpack-c/src/mpack/mpack-reader.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-reader.c.s
.PHONY : deps/msgpack-c/src/mpack/mpack-reader.c.s

deps/msgpack-c/src/mpack/mpack-writer.o: deps/msgpack-c/src/mpack/mpack-writer.c.o
.PHONY : deps/msgpack-c/src/mpack/mpack-writer.o

# target to build an object file
deps/msgpack-c/src/mpack/mpack-writer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-writer.c.o
.PHONY : deps/msgpack-c/src/mpack/mpack-writer.c.o

deps/msgpack-c/src/mpack/mpack-writer.i: deps/msgpack-c/src/mpack/mpack-writer.c.i
.PHONY : deps/msgpack-c/src/mpack/mpack-writer.i

# target to preprocess a source file
deps/msgpack-c/src/mpack/mpack-writer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-writer.c.i
.PHONY : deps/msgpack-c/src/mpack/mpack-writer.c.i

deps/msgpack-c/src/mpack/mpack-writer.s: deps/msgpack-c/src/mpack/mpack-writer.c.s
.PHONY : deps/msgpack-c/src/mpack/mpack-writer.s

# target to generate assembly for a file
deps/msgpack-c/src/mpack/mpack-writer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-writer.c.s
.PHONY : deps/msgpack-c/src/mpack/mpack-writer.c.s

examples/test_client.o: examples/test_client.c.o
.PHONY : examples/test_client.o

# target to build an object file
examples/test_client.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_client.dir/build.make CMakeFiles/test_client.dir/examples/test_client.c.o
.PHONY : examples/test_client.c.o

examples/test_client.i: examples/test_client.c.i
.PHONY : examples/test_client.i

# target to preprocess a source file
examples/test_client.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_client.dir/build.make CMakeFiles/test_client.dir/examples/test_client.c.i
.PHONY : examples/test_client.c.i

examples/test_client.s: examples/test_client.c.s
.PHONY : examples/test_client.s

# target to generate assembly for a file
examples/test_client.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_client.dir/build.make CMakeFiles/test_client.dir/examples/test_client.c.s
.PHONY : examples/test_client.c.s

examples/test_server.o: examples/test_server.c.o
.PHONY : examples/test_server.o

# target to build an object file
examples/test_server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/examples/test_server.c.o
.PHONY : examples/test_server.c.o

examples/test_server.i: examples/test_server.c.i
.PHONY : examples/test_server.i

# target to preprocess a source file
examples/test_server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/examples/test_server.c.i
.PHONY : examples/test_server.c.i

examples/test_server.s: examples/test_server.c.s
.PHONY : examples/test_server.s

# target to generate assembly for a file
examples/test_server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/examples/test_server.c.s
.PHONY : examples/test_server.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... msgpackc"
	@echo "... test_client"
	@echo "... test_server"
	@echo "... deps/msgpack-c/src/mpack/mpack-common.o"
	@echo "... deps/msgpack-c/src/mpack/mpack-common.i"
	@echo "... deps/msgpack-c/src/mpack/mpack-common.s"
	@echo "... deps/msgpack-c/src/mpack/mpack-expect.o"
	@echo "... deps/msgpack-c/src/mpack/mpack-expect.i"
	@echo "... deps/msgpack-c/src/mpack/mpack-expect.s"
	@echo "... deps/msgpack-c/src/mpack/mpack-node.o"
	@echo "... deps/msgpack-c/src/mpack/mpack-node.i"
	@echo "... deps/msgpack-c/src/mpack/mpack-node.s"
	@echo "... deps/msgpack-c/src/mpack/mpack-platform.o"
	@echo "... deps/msgpack-c/src/mpack/mpack-platform.i"
	@echo "... deps/msgpack-c/src/mpack/mpack-platform.s"
	@echo "... deps/msgpack-c/src/mpack/mpack-reader.o"
	@echo "... deps/msgpack-c/src/mpack/mpack-reader.i"
	@echo "... deps/msgpack-c/src/mpack/mpack-reader.s"
	@echo "... deps/msgpack-c/src/mpack/mpack-writer.o"
	@echo "... deps/msgpack-c/src/mpack/mpack-writer.i"
	@echo "... deps/msgpack-c/src/mpack/mpack-writer.s"
	@echo "... examples/test_client.o"
	@echo "... examples/test_client.i"
	@echo "... examples/test_client.s"
	@echo "... examples/test_server.o"
	@echo "... examples/test_server.i"
	@echo "... examples/test_server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

