# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zhaodi-chen/project/uvrpc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zhaodi-chen/project/uvrpc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zhaodi-chen/project/uvrpc/CMakeFiles /home/zhaodi-chen/project/uvrpc//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zhaodi-chen/project/uvrpc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named msgpackc

# Build rule for target.
msgpackc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 msgpackc
.PHONY : msgpackc

# fast build rule for target.
msgpackc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/build
.PHONY : msgpackc/fast

#=============================================================================
# Target rules for targets named uvrpc

# Build rule for target.
uvrpc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uvrpc
.PHONY : uvrpc

# fast build rule for target.
uvrpc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uvrpc.dir/build.make CMakeFiles/uvrpc.dir/build
.PHONY : uvrpc/fast

#=============================================================================
# Target rules for targets named echoservice_async_client

# Build rule for target.
echoservice_async_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 echoservice_async_client
.PHONY : echoservice_async_client

# fast build rule for target.
echoservice_async_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/echoservice_async_client.dir/build.make CMakeFiles/echoservice_async_client.dir/build
.PHONY : echoservice_async_client/fast

#=============================================================================
# Target rules for targets named echoservice_server

# Build rule for target.
echoservice_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 echoservice_server
.PHONY : echoservice_server

# fast build rule for target.
echoservice_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/echoservice_server.dir/build.make CMakeFiles/echoservice_server.dir/build
.PHONY : echoservice_server/fast

#=============================================================================
# Target rules for targets named echo_server

# Build rule for target.
echo_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 echo_server
.PHONY : echo_server

# fast build rule for target.
echo_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/build
.PHONY : echo_server/fast

#=============================================================================
# Target rules for targets named test_new_api_perf

# Build rule for target.
test_new_api_perf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_new_api_perf
.PHONY : test_new_api_perf

# fast build rule for target.
test_new_api_perf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_new_api_perf.dir/build.make CMakeFiles/test_new_api_perf.dir/build
.PHONY : test_new_api_perf/fast

#=============================================================================
# Target rules for targets named test_generated_client

# Build rule for target.
test_generated_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_generated_client
.PHONY : test_generated_client

# fast build rule for target.
test_generated_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_generated_client.dir/build.make CMakeFiles/test_generated_client.dir/build
.PHONY : test_generated_client/fast

#=============================================================================
# Target rules for targets named gen_benchmark

# Build rule for target.
gen_benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gen_benchmark
.PHONY : gen_benchmark

# fast build rule for target.
gen_benchmark/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen_benchmark.dir/build.make CMakeFiles/gen_benchmark.dir/build
.PHONY : gen_benchmark/fast

#=============================================================================
# Target rules for targets named test_generated_code_perf

# Build rule for target.
test_generated_code_perf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_generated_code_perf
.PHONY : test_generated_code_perf

# fast build rule for target.
test_generated_code_perf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_generated_code_perf.dir/build.make CMakeFiles/test_generated_code_perf.dir/build
.PHONY : test_generated_code_perf/fast

#=============================================================================
# Target rules for targets named benchmark_server

# Build rule for target.
benchmark_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark_server
.PHONY : benchmark_server

# fast build rule for target.
benchmark_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_server.dir/build.make CMakeFiles/benchmark_server.dir/build
.PHONY : benchmark_server/fast

#=============================================================================
# Target rules for targets named benchmark_client

# Build rule for target.
benchmark_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 benchmark_client
.PHONY : benchmark_client

# fast build rule for target.
benchmark_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_client.dir/build.make CMakeFiles/benchmark_client.dir/build
.PHONY : benchmark_client/fast

#=============================================================================
# Target rules for targets named perf_test

# Build rule for target.
perf_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 perf_test
.PHONY : perf_test

# fast build rule for target.
perf_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perf_test.dir/build.make CMakeFiles/perf_test.dir/build
.PHONY : perf_test/fast

#=============================================================================
# Target rules for targets named unified_test

# Build rule for target.
unified_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unified_test
.PHONY : unified_test

# fast build rule for target.
unified_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unified_test.dir/build.make CMakeFiles/unified_test.dir/build
.PHONY : unified_test/fast

#=============================================================================
# Target rules for targets named mimalloc

# Build rule for target.
mimalloc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mimalloc
.PHONY : mimalloc

# fast build rule for target.
mimalloc/fast:
	$(MAKE) $(MAKESILENT) -f mimalloc/CMakeFiles/mimalloc.dir/build.make mimalloc/CMakeFiles/mimalloc.dir/build
.PHONY : mimalloc/fast

#=============================================================================
# Target rules for targets named mimalloc-static

# Build rule for target.
mimalloc-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mimalloc-static
.PHONY : mimalloc-static

# fast build rule for target.
mimalloc-static/fast:
	$(MAKE) $(MAKESILENT) -f mimalloc/CMakeFiles/mimalloc-static.dir/build.make mimalloc/CMakeFiles/mimalloc-static.dir/build
.PHONY : mimalloc-static/fast

#=============================================================================
# Target rules for targets named mimalloc-obj

# Build rule for target.
mimalloc-obj: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mimalloc-obj
.PHONY : mimalloc-obj

# fast build rule for target.
mimalloc-obj/fast:
	$(MAKE) $(MAKESILENT) -f mimalloc/CMakeFiles/mimalloc-obj.dir/build.make mimalloc/CMakeFiles/mimalloc-obj.dir/build
.PHONY : mimalloc-obj/fast

#=============================================================================
# Target rules for targets named mimalloc-obj-target

# Build rule for target.
mimalloc-obj-target: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mimalloc-obj-target
.PHONY : mimalloc-obj-target

# fast build rule for target.
mimalloc-obj-target/fast:
	$(MAKE) $(MAKESILENT) -f mimalloc/CMakeFiles/mimalloc-obj-target.dir/build.make mimalloc/CMakeFiles/mimalloc-obj-target.dir/build
.PHONY : mimalloc-obj-target/fast

#=============================================================================
# Target rules for targets named mimalloc-test-api

# Build rule for target.
mimalloc-test-api: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mimalloc-test-api
.PHONY : mimalloc-test-api

# fast build rule for target.
mimalloc-test-api/fast:
	$(MAKE) $(MAKESILENT) -f mimalloc/CMakeFiles/mimalloc-test-api.dir/build.make mimalloc/CMakeFiles/mimalloc-test-api.dir/build
.PHONY : mimalloc-test-api/fast

#=============================================================================
# Target rules for targets named mimalloc-test-api-fill

# Build rule for target.
mimalloc-test-api-fill: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mimalloc-test-api-fill
.PHONY : mimalloc-test-api-fill

# fast build rule for target.
mimalloc-test-api-fill/fast:
	$(MAKE) $(MAKESILENT) -f mimalloc/CMakeFiles/mimalloc-test-api-fill.dir/build.make mimalloc/CMakeFiles/mimalloc-test-api-fill.dir/build
.PHONY : mimalloc-test-api-fill/fast

#=============================================================================
# Target rules for targets named mimalloc-test-stress

# Build rule for target.
mimalloc-test-stress: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mimalloc-test-stress
.PHONY : mimalloc-test-stress

# fast build rule for target.
mimalloc-test-stress/fast:
	$(MAKE) $(MAKESILENT) -f mimalloc/CMakeFiles/mimalloc-test-stress.dir/build.make mimalloc/CMakeFiles/mimalloc-test-stress.dir/build
.PHONY : mimalloc-test-stress/fast

#=============================================================================
# Target rules for targets named mimalloc-test-stress-dynamic

# Build rule for target.
mimalloc-test-stress-dynamic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mimalloc-test-stress-dynamic
.PHONY : mimalloc-test-stress-dynamic

# fast build rule for target.
mimalloc-test-stress-dynamic/fast:
	$(MAKE) $(MAKESILENT) -f mimalloc/CMakeFiles/mimalloc-test-stress-dynamic.dir/build.make mimalloc/CMakeFiles/mimalloc-test-stress-dynamic.dir/build
.PHONY : mimalloc-test-stress-dynamic/fast

benchmark/benchmark_client.o: benchmark/benchmark_client.c.o
.PHONY : benchmark/benchmark_client.o

# target to build an object file
benchmark/benchmark_client.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_client.dir/build.make CMakeFiles/benchmark_client.dir/benchmark/benchmark_client.c.o
.PHONY : benchmark/benchmark_client.c.o

benchmark/benchmark_client.i: benchmark/benchmark_client.c.i
.PHONY : benchmark/benchmark_client.i

# target to preprocess a source file
benchmark/benchmark_client.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_client.dir/build.make CMakeFiles/benchmark_client.dir/benchmark/benchmark_client.c.i
.PHONY : benchmark/benchmark_client.c.i

benchmark/benchmark_client.s: benchmark/benchmark_client.c.s
.PHONY : benchmark/benchmark_client.s

# target to generate assembly for a file
benchmark/benchmark_client.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_client.dir/build.make CMakeFiles/benchmark_client.dir/benchmark/benchmark_client.c.s
.PHONY : benchmark/benchmark_client.c.s

benchmark/benchmark_server.o: benchmark/benchmark_server.c.o
.PHONY : benchmark/benchmark_server.o

# target to build an object file
benchmark/benchmark_server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_server.dir/build.make CMakeFiles/benchmark_server.dir/benchmark/benchmark_server.c.o
.PHONY : benchmark/benchmark_server.c.o

benchmark/benchmark_server.i: benchmark/benchmark_server.c.i
.PHONY : benchmark/benchmark_server.i

# target to preprocess a source file
benchmark/benchmark_server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_server.dir/build.make CMakeFiles/benchmark_server.dir/benchmark/benchmark_server.c.i
.PHONY : benchmark/benchmark_server.c.i

benchmark/benchmark_server.s: benchmark/benchmark_server.c.s
.PHONY : benchmark/benchmark_server.s

# target to generate assembly for a file
benchmark/benchmark_server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/benchmark_server.dir/build.make CMakeFiles/benchmark_server.dir/benchmark/benchmark_server.c.s
.PHONY : benchmark/benchmark_server.c.s

benchmark/gen_benchmark.o: benchmark/gen_benchmark.c.o
.PHONY : benchmark/gen_benchmark.o

# target to build an object file
benchmark/gen_benchmark.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen_benchmark.dir/build.make CMakeFiles/gen_benchmark.dir/benchmark/gen_benchmark.c.o
.PHONY : benchmark/gen_benchmark.c.o

benchmark/gen_benchmark.i: benchmark/gen_benchmark.c.i
.PHONY : benchmark/gen_benchmark.i

# target to preprocess a source file
benchmark/gen_benchmark.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen_benchmark.dir/build.make CMakeFiles/gen_benchmark.dir/benchmark/gen_benchmark.c.i
.PHONY : benchmark/gen_benchmark.c.i

benchmark/gen_benchmark.s: benchmark/gen_benchmark.c.s
.PHONY : benchmark/gen_benchmark.s

# target to generate assembly for a file
benchmark/gen_benchmark.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen_benchmark.dir/build.make CMakeFiles/gen_benchmark.dir/benchmark/gen_benchmark.c.s
.PHONY : benchmark/gen_benchmark.c.s

benchmark/perf_test.o: benchmark/perf_test.c.o
.PHONY : benchmark/perf_test.o

# target to build an object file
benchmark/perf_test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perf_test.dir/build.make CMakeFiles/perf_test.dir/benchmark/perf_test.c.o
.PHONY : benchmark/perf_test.c.o

benchmark/perf_test.i: benchmark/perf_test.c.i
.PHONY : benchmark/perf_test.i

# target to preprocess a source file
benchmark/perf_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perf_test.dir/build.make CMakeFiles/perf_test.dir/benchmark/perf_test.c.i
.PHONY : benchmark/perf_test.c.i

benchmark/perf_test.s: benchmark/perf_test.c.s
.PHONY : benchmark/perf_test.s

# target to generate assembly for a file
benchmark/perf_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perf_test.dir/build.make CMakeFiles/perf_test.dir/benchmark/perf_test.c.s
.PHONY : benchmark/perf_test.c.s

benchmark/unified_test.o: benchmark/unified_test.c.o
.PHONY : benchmark/unified_test.o

# target to build an object file
benchmark/unified_test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unified_test.dir/build.make CMakeFiles/unified_test.dir/benchmark/unified_test.c.o
.PHONY : benchmark/unified_test.c.o

benchmark/unified_test.i: benchmark/unified_test.c.i
.PHONY : benchmark/unified_test.i

# target to preprocess a source file
benchmark/unified_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unified_test.dir/build.make CMakeFiles/unified_test.dir/benchmark/unified_test.c.i
.PHONY : benchmark/unified_test.c.i

benchmark/unified_test.s: benchmark/unified_test.c.s
.PHONY : benchmark/unified_test.s

# target to generate assembly for a file
benchmark/unified_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unified_test.dir/build.make CMakeFiles/unified_test.dir/benchmark/unified_test.c.s
.PHONY : benchmark/unified_test.c.s

deps/msgpack-c/src/mpack/mpack-common.o: deps/msgpack-c/src/mpack/mpack-common.c.o
.PHONY : deps/msgpack-c/src/mpack/mpack-common.o

# target to build an object file
deps/msgpack-c/src/mpack/mpack-common.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-common.c.o
.PHONY : deps/msgpack-c/src/mpack/mpack-common.c.o

deps/msgpack-c/src/mpack/mpack-common.i: deps/msgpack-c/src/mpack/mpack-common.c.i
.PHONY : deps/msgpack-c/src/mpack/mpack-common.i

# target to preprocess a source file
deps/msgpack-c/src/mpack/mpack-common.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-common.c.i
.PHONY : deps/msgpack-c/src/mpack/mpack-common.c.i

deps/msgpack-c/src/mpack/mpack-common.s: deps/msgpack-c/src/mpack/mpack-common.c.s
.PHONY : deps/msgpack-c/src/mpack/mpack-common.s

# target to generate assembly for a file
deps/msgpack-c/src/mpack/mpack-common.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-common.c.s
.PHONY : deps/msgpack-c/src/mpack/mpack-common.c.s

deps/msgpack-c/src/mpack/mpack-expect.o: deps/msgpack-c/src/mpack/mpack-expect.c.o
.PHONY : deps/msgpack-c/src/mpack/mpack-expect.o

# target to build an object file
deps/msgpack-c/src/mpack/mpack-expect.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-expect.c.o
.PHONY : deps/msgpack-c/src/mpack/mpack-expect.c.o

deps/msgpack-c/src/mpack/mpack-expect.i: deps/msgpack-c/src/mpack/mpack-expect.c.i
.PHONY : deps/msgpack-c/src/mpack/mpack-expect.i

# target to preprocess a source file
deps/msgpack-c/src/mpack/mpack-expect.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-expect.c.i
.PHONY : deps/msgpack-c/src/mpack/mpack-expect.c.i

deps/msgpack-c/src/mpack/mpack-expect.s: deps/msgpack-c/src/mpack/mpack-expect.c.s
.PHONY : deps/msgpack-c/src/mpack/mpack-expect.s

# target to generate assembly for a file
deps/msgpack-c/src/mpack/mpack-expect.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-expect.c.s
.PHONY : deps/msgpack-c/src/mpack/mpack-expect.c.s

deps/msgpack-c/src/mpack/mpack-node.o: deps/msgpack-c/src/mpack/mpack-node.c.o
.PHONY : deps/msgpack-c/src/mpack/mpack-node.o

# target to build an object file
deps/msgpack-c/src/mpack/mpack-node.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-node.c.o
.PHONY : deps/msgpack-c/src/mpack/mpack-node.c.o

deps/msgpack-c/src/mpack/mpack-node.i: deps/msgpack-c/src/mpack/mpack-node.c.i
.PHONY : deps/msgpack-c/src/mpack/mpack-node.i

# target to preprocess a source file
deps/msgpack-c/src/mpack/mpack-node.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-node.c.i
.PHONY : deps/msgpack-c/src/mpack/mpack-node.c.i

deps/msgpack-c/src/mpack/mpack-node.s: deps/msgpack-c/src/mpack/mpack-node.c.s
.PHONY : deps/msgpack-c/src/mpack/mpack-node.s

# target to generate assembly for a file
deps/msgpack-c/src/mpack/mpack-node.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-node.c.s
.PHONY : deps/msgpack-c/src/mpack/mpack-node.c.s

deps/msgpack-c/src/mpack/mpack-platform.o: deps/msgpack-c/src/mpack/mpack-platform.c.o
.PHONY : deps/msgpack-c/src/mpack/mpack-platform.o

# target to build an object file
deps/msgpack-c/src/mpack/mpack-platform.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-platform.c.o
.PHONY : deps/msgpack-c/src/mpack/mpack-platform.c.o

deps/msgpack-c/src/mpack/mpack-platform.i: deps/msgpack-c/src/mpack/mpack-platform.c.i
.PHONY : deps/msgpack-c/src/mpack/mpack-platform.i

# target to preprocess a source file
deps/msgpack-c/src/mpack/mpack-platform.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-platform.c.i
.PHONY : deps/msgpack-c/src/mpack/mpack-platform.c.i

deps/msgpack-c/src/mpack/mpack-platform.s: deps/msgpack-c/src/mpack/mpack-platform.c.s
.PHONY : deps/msgpack-c/src/mpack/mpack-platform.s

# target to generate assembly for a file
deps/msgpack-c/src/mpack/mpack-platform.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-platform.c.s
.PHONY : deps/msgpack-c/src/mpack/mpack-platform.c.s

deps/msgpack-c/src/mpack/mpack-reader.o: deps/msgpack-c/src/mpack/mpack-reader.c.o
.PHONY : deps/msgpack-c/src/mpack/mpack-reader.o

# target to build an object file
deps/msgpack-c/src/mpack/mpack-reader.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-reader.c.o
.PHONY : deps/msgpack-c/src/mpack/mpack-reader.c.o

deps/msgpack-c/src/mpack/mpack-reader.i: deps/msgpack-c/src/mpack/mpack-reader.c.i
.PHONY : deps/msgpack-c/src/mpack/mpack-reader.i

# target to preprocess a source file
deps/msgpack-c/src/mpack/mpack-reader.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-reader.c.i
.PHONY : deps/msgpack-c/src/mpack/mpack-reader.c.i

deps/msgpack-c/src/mpack/mpack-reader.s: deps/msgpack-c/src/mpack/mpack-reader.c.s
.PHONY : deps/msgpack-c/src/mpack/mpack-reader.s

# target to generate assembly for a file
deps/msgpack-c/src/mpack/mpack-reader.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-reader.c.s
.PHONY : deps/msgpack-c/src/mpack/mpack-reader.c.s

deps/msgpack-c/src/mpack/mpack-writer.o: deps/msgpack-c/src/mpack/mpack-writer.c.o
.PHONY : deps/msgpack-c/src/mpack/mpack-writer.o

# target to build an object file
deps/msgpack-c/src/mpack/mpack-writer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-writer.c.o
.PHONY : deps/msgpack-c/src/mpack/mpack-writer.c.o

deps/msgpack-c/src/mpack/mpack-writer.i: deps/msgpack-c/src/mpack/mpack-writer.c.i
.PHONY : deps/msgpack-c/src/mpack/mpack-writer.i

# target to preprocess a source file
deps/msgpack-c/src/mpack/mpack-writer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-writer.c.i
.PHONY : deps/msgpack-c/src/mpack/mpack-writer.c.i

deps/msgpack-c/src/mpack/mpack-writer.s: deps/msgpack-c/src/mpack/mpack-writer.c.s
.PHONY : deps/msgpack-c/src/mpack/mpack-writer.s

# target to generate assembly for a file
deps/msgpack-c/src/mpack/mpack-writer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msgpackc.dir/build.make CMakeFiles/msgpackc.dir/deps/msgpack-c/src/mpack/mpack-writer.c.s
.PHONY : deps/msgpack-c/src/mpack/mpack-writer.c.s

examples/echo_server.o: examples/echo_server.c.o
.PHONY : examples/echo_server.o

# target to build an object file
examples/echo_server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/examples/echo_server.c.o
.PHONY : examples/echo_server.c.o

examples/echo_server.i: examples/echo_server.c.i
.PHONY : examples/echo_server.i

# target to preprocess a source file
examples/echo_server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/examples/echo_server.c.i
.PHONY : examples/echo_server.c.i

examples/echo_server.s: examples/echo_server.c.s
.PHONY : examples/echo_server.s

# target to generate assembly for a file
examples/echo_server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/examples/echo_server.c.s
.PHONY : examples/echo_server.c.s

generated/echoservice_async_client_example.o: generated/echoservice_async_client_example.c.o
.PHONY : generated/echoservice_async_client_example.o

# target to build an object file
generated/echoservice_async_client_example.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/echoservice_async_client.dir/build.make CMakeFiles/echoservice_async_client.dir/generated/echoservice_async_client_example.c.o
.PHONY : generated/echoservice_async_client_example.c.o

generated/echoservice_async_client_example.i: generated/echoservice_async_client_example.c.i
.PHONY : generated/echoservice_async_client_example.i

# target to preprocess a source file
generated/echoservice_async_client_example.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/echoservice_async_client.dir/build.make CMakeFiles/echoservice_async_client.dir/generated/echoservice_async_client_example.c.i
.PHONY : generated/echoservice_async_client_example.c.i

generated/echoservice_async_client_example.s: generated/echoservice_async_client_example.c.s
.PHONY : generated/echoservice_async_client_example.s

# target to generate assembly for a file
generated/echoservice_async_client_example.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/echoservice_async_client.dir/build.make CMakeFiles/echoservice_async_client.dir/generated/echoservice_async_client_example.c.s
.PHONY : generated/echoservice_async_client_example.c.s

generated/echoservice_gen.o: generated/echoservice_gen.c.o
.PHONY : generated/echoservice_gen.o

# target to build an object file
generated/echoservice_gen.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/echoservice_async_client.dir/build.make CMakeFiles/echoservice_async_client.dir/generated/echoservice_gen.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/echoservice_server.dir/build.make CMakeFiles/echoservice_server.dir/generated/echoservice_gen.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_generated_client.dir/build.make CMakeFiles/test_generated_client.dir/generated/echoservice_gen.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen_benchmark.dir/build.make CMakeFiles/gen_benchmark.dir/generated/echoservice_gen.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_generated_code_perf.dir/build.make CMakeFiles/test_generated_code_perf.dir/generated/echoservice_gen.c.o
.PHONY : generated/echoservice_gen.c.o

generated/echoservice_gen.i: generated/echoservice_gen.c.i
.PHONY : generated/echoservice_gen.i

# target to preprocess a source file
generated/echoservice_gen.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/echoservice_async_client.dir/build.make CMakeFiles/echoservice_async_client.dir/generated/echoservice_gen.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/echoservice_server.dir/build.make CMakeFiles/echoservice_server.dir/generated/echoservice_gen.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_generated_client.dir/build.make CMakeFiles/test_generated_client.dir/generated/echoservice_gen.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen_benchmark.dir/build.make CMakeFiles/gen_benchmark.dir/generated/echoservice_gen.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_generated_code_perf.dir/build.make CMakeFiles/test_generated_code_perf.dir/generated/echoservice_gen.c.i
.PHONY : generated/echoservice_gen.c.i

generated/echoservice_gen.s: generated/echoservice_gen.c.s
.PHONY : generated/echoservice_gen.s

# target to generate assembly for a file
generated/echoservice_gen.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/echoservice_async_client.dir/build.make CMakeFiles/echoservice_async_client.dir/generated/echoservice_gen.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/echoservice_server.dir/build.make CMakeFiles/echoservice_server.dir/generated/echoservice_gen.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_generated_client.dir/build.make CMakeFiles/test_generated_client.dir/generated/echoservice_gen.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen_benchmark.dir/build.make CMakeFiles/gen_benchmark.dir/generated/echoservice_gen.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_generated_code_perf.dir/build.make CMakeFiles/test_generated_code_perf.dir/generated/echoservice_gen.c.s
.PHONY : generated/echoservice_gen.c.s

generated/echoservice_gen_client.o: generated/echoservice_gen_client.c.o
.PHONY : generated/echoservice_gen_client.o

# target to build an object file
generated/echoservice_gen_client.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/echoservice_async_client.dir/build.make CMakeFiles/echoservice_async_client.dir/generated/echoservice_gen_client.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_generated_client.dir/build.make CMakeFiles/test_generated_client.dir/generated/echoservice_gen_client.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen_benchmark.dir/build.make CMakeFiles/gen_benchmark.dir/generated/echoservice_gen_client.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_generated_code_perf.dir/build.make CMakeFiles/test_generated_code_perf.dir/generated/echoservice_gen_client.c.o
.PHONY : generated/echoservice_gen_client.c.o

generated/echoservice_gen_client.i: generated/echoservice_gen_client.c.i
.PHONY : generated/echoservice_gen_client.i

# target to preprocess a source file
generated/echoservice_gen_client.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/echoservice_async_client.dir/build.make CMakeFiles/echoservice_async_client.dir/generated/echoservice_gen_client.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_generated_client.dir/build.make CMakeFiles/test_generated_client.dir/generated/echoservice_gen_client.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen_benchmark.dir/build.make CMakeFiles/gen_benchmark.dir/generated/echoservice_gen_client.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_generated_code_perf.dir/build.make CMakeFiles/test_generated_code_perf.dir/generated/echoservice_gen_client.c.i
.PHONY : generated/echoservice_gen_client.c.i

generated/echoservice_gen_client.s: generated/echoservice_gen_client.c.s
.PHONY : generated/echoservice_gen_client.s

# target to generate assembly for a file
generated/echoservice_gen_client.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/echoservice_async_client.dir/build.make CMakeFiles/echoservice_async_client.dir/generated/echoservice_gen_client.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_generated_client.dir/build.make CMakeFiles/test_generated_client.dir/generated/echoservice_gen_client.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gen_benchmark.dir/build.make CMakeFiles/gen_benchmark.dir/generated/echoservice_gen_client.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_generated_code_perf.dir/build.make CMakeFiles/test_generated_code_perf.dir/generated/echoservice_gen_client.c.s
.PHONY : generated/echoservice_gen_client.c.s

generated/echoservice_server_example.o: generated/echoservice_server_example.c.o
.PHONY : generated/echoservice_server_example.o

# target to build an object file
generated/echoservice_server_example.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/echoservice_server.dir/build.make CMakeFiles/echoservice_server.dir/generated/echoservice_server_example.c.o
.PHONY : generated/echoservice_server_example.c.o

generated/echoservice_server_example.i: generated/echoservice_server_example.c.i
.PHONY : generated/echoservice_server_example.i

# target to preprocess a source file
generated/echoservice_server_example.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/echoservice_server.dir/build.make CMakeFiles/echoservice_server.dir/generated/echoservice_server_example.c.i
.PHONY : generated/echoservice_server_example.c.i

generated/echoservice_server_example.s: generated/echoservice_server_example.c.s
.PHONY : generated/echoservice_server_example.s

# target to generate assembly for a file
generated/echoservice_server_example.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/echoservice_server.dir/build.make CMakeFiles/echoservice_server.dir/generated/echoservice_server_example.c.s
.PHONY : generated/echoservice_server_example.c.s

src/msgpack_wrapper.o: src/msgpack_wrapper.c.o
.PHONY : src/msgpack_wrapper.o

# target to build an object file
src/msgpack_wrapper.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uvrpc.dir/build.make CMakeFiles/uvrpc.dir/src/msgpack_wrapper.c.o
.PHONY : src/msgpack_wrapper.c.o

src/msgpack_wrapper.i: src/msgpack_wrapper.c.i
.PHONY : src/msgpack_wrapper.i

# target to preprocess a source file
src/msgpack_wrapper.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uvrpc.dir/build.make CMakeFiles/uvrpc.dir/src/msgpack_wrapper.c.i
.PHONY : src/msgpack_wrapper.c.i

src/msgpack_wrapper.s: src/msgpack_wrapper.c.s
.PHONY : src/msgpack_wrapper.s

# target to generate assembly for a file
src/msgpack_wrapper.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uvrpc.dir/build.make CMakeFiles/uvrpc.dir/src/msgpack_wrapper.c.s
.PHONY : src/msgpack_wrapper.c.s

src/uvrpc_config.o: src/uvrpc_config.c.o
.PHONY : src/uvrpc_config.o

# target to build an object file
src/uvrpc_config.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uvrpc.dir/build.make CMakeFiles/uvrpc.dir/src/uvrpc_config.c.o
.PHONY : src/uvrpc_config.c.o

src/uvrpc_config.i: src/uvrpc_config.c.i
.PHONY : src/uvrpc_config.i

# target to preprocess a source file
src/uvrpc_config.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uvrpc.dir/build.make CMakeFiles/uvrpc.dir/src/uvrpc_config.c.i
.PHONY : src/uvrpc_config.c.i

src/uvrpc_config.s: src/uvrpc_config.c.s
.PHONY : src/uvrpc_config.s

# target to generate assembly for a file
src/uvrpc_config.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uvrpc.dir/build.make CMakeFiles/uvrpc.dir/src/uvrpc_config.c.s
.PHONY : src/uvrpc_config.c.s

src/uvrpc_new.o: src/uvrpc_new.c.o
.PHONY : src/uvrpc_new.o

# target to build an object file
src/uvrpc_new.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uvrpc.dir/build.make CMakeFiles/uvrpc.dir/src/uvrpc_new.c.o
.PHONY : src/uvrpc_new.c.o

src/uvrpc_new.i: src/uvrpc_new.c.i
.PHONY : src/uvrpc_new.i

# target to preprocess a source file
src/uvrpc_new.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uvrpc.dir/build.make CMakeFiles/uvrpc.dir/src/uvrpc_new.c.i
.PHONY : src/uvrpc_new.c.i

src/uvrpc_new.s: src/uvrpc_new.c.s
.PHONY : src/uvrpc_new.s

# target to generate assembly for a file
src/uvrpc_new.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uvrpc.dir/build.make CMakeFiles/uvrpc.dir/src/uvrpc_new.c.s
.PHONY : src/uvrpc_new.c.s

src/uvrpc_utils.o: src/uvrpc_utils.c.o
.PHONY : src/uvrpc_utils.o

# target to build an object file
src/uvrpc_utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uvrpc.dir/build.make CMakeFiles/uvrpc.dir/src/uvrpc_utils.c.o
.PHONY : src/uvrpc_utils.c.o

src/uvrpc_utils.i: src/uvrpc_utils.c.i
.PHONY : src/uvrpc_utils.i

# target to preprocess a source file
src/uvrpc_utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uvrpc.dir/build.make CMakeFiles/uvrpc.dir/src/uvrpc_utils.c.i
.PHONY : src/uvrpc_utils.c.i

src/uvrpc_utils.s: src/uvrpc_utils.c.s
.PHONY : src/uvrpc_utils.s

# target to generate assembly for a file
src/uvrpc_utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uvrpc.dir/build.make CMakeFiles/uvrpc.dir/src/uvrpc_utils.c.s
.PHONY : src/uvrpc_utils.c.s

src/uvzmq_impl.o: src/uvzmq_impl.c.o
.PHONY : src/uvzmq_impl.o

# target to build an object file
src/uvzmq_impl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uvrpc.dir/build.make CMakeFiles/uvrpc.dir/src/uvzmq_impl.c.o
.PHONY : src/uvzmq_impl.c.o

src/uvzmq_impl.i: src/uvzmq_impl.c.i
.PHONY : src/uvzmq_impl.i

# target to preprocess a source file
src/uvzmq_impl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uvrpc.dir/build.make CMakeFiles/uvrpc.dir/src/uvzmq_impl.c.i
.PHONY : src/uvzmq_impl.c.i

src/uvzmq_impl.s: src/uvzmq_impl.c.s
.PHONY : src/uvzmq_impl.s

# target to generate assembly for a file
src/uvzmq_impl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/uvrpc.dir/build.make CMakeFiles/uvrpc.dir/src/uvzmq_impl.c.s
.PHONY : src/uvzmq_impl.c.s

tests/test_generated_client.o: tests/test_generated_client.c.o
.PHONY : tests/test_generated_client.o

# target to build an object file
tests/test_generated_client.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_generated_client.dir/build.make CMakeFiles/test_generated_client.dir/tests/test_generated_client.c.o
.PHONY : tests/test_generated_client.c.o

tests/test_generated_client.i: tests/test_generated_client.c.i
.PHONY : tests/test_generated_client.i

# target to preprocess a source file
tests/test_generated_client.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_generated_client.dir/build.make CMakeFiles/test_generated_client.dir/tests/test_generated_client.c.i
.PHONY : tests/test_generated_client.c.i

tests/test_generated_client.s: tests/test_generated_client.c.s
.PHONY : tests/test_generated_client.s

# target to generate assembly for a file
tests/test_generated_client.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_generated_client.dir/build.make CMakeFiles/test_generated_client.dir/tests/test_generated_client.c.s
.PHONY : tests/test_generated_client.c.s

tests/test_generated_code_perf.o: tests/test_generated_code_perf.c.o
.PHONY : tests/test_generated_code_perf.o

# target to build an object file
tests/test_generated_code_perf.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_generated_code_perf.dir/build.make CMakeFiles/test_generated_code_perf.dir/tests/test_generated_code_perf.c.o
.PHONY : tests/test_generated_code_perf.c.o

tests/test_generated_code_perf.i: tests/test_generated_code_perf.c.i
.PHONY : tests/test_generated_code_perf.i

# target to preprocess a source file
tests/test_generated_code_perf.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_generated_code_perf.dir/build.make CMakeFiles/test_generated_code_perf.dir/tests/test_generated_code_perf.c.i
.PHONY : tests/test_generated_code_perf.c.i

tests/test_generated_code_perf.s: tests/test_generated_code_perf.c.s
.PHONY : tests/test_generated_code_perf.s

# target to generate assembly for a file
tests/test_generated_code_perf.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_generated_code_perf.dir/build.make CMakeFiles/test_generated_code_perf.dir/tests/test_generated_code_perf.c.s
.PHONY : tests/test_generated_code_perf.c.s

tests/test_new_api_perf.o: tests/test_new_api_perf.c.o
.PHONY : tests/test_new_api_perf.o

# target to build an object file
tests/test_new_api_perf.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_new_api_perf.dir/build.make CMakeFiles/test_new_api_perf.dir/tests/test_new_api_perf.c.o
.PHONY : tests/test_new_api_perf.c.o

tests/test_new_api_perf.i: tests/test_new_api_perf.c.i
.PHONY : tests/test_new_api_perf.i

# target to preprocess a source file
tests/test_new_api_perf.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_new_api_perf.dir/build.make CMakeFiles/test_new_api_perf.dir/tests/test_new_api_perf.c.i
.PHONY : tests/test_new_api_perf.c.i

tests/test_new_api_perf.s: tests/test_new_api_perf.c.s
.PHONY : tests/test_new_api_perf.s

# target to generate assembly for a file
tests/test_new_api_perf.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_new_api_perf.dir/build.make CMakeFiles/test_new_api_perf.dir/tests/test_new_api_perf.c.s
.PHONY : tests/test_new_api_perf.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... mimalloc-obj-target"
	@echo "... benchmark_client"
	@echo "... benchmark_server"
	@echo "... echo_server"
	@echo "... echoservice_async_client"
	@echo "... echoservice_server"
	@echo "... gen_benchmark"
	@echo "... mimalloc"
	@echo "... mimalloc-obj"
	@echo "... mimalloc-static"
	@echo "... mimalloc-test-api"
	@echo "... mimalloc-test-api-fill"
	@echo "... mimalloc-test-stress"
	@echo "... mimalloc-test-stress-dynamic"
	@echo "... msgpackc"
	@echo "... perf_test"
	@echo "... test_generated_client"
	@echo "... test_generated_code_perf"
	@echo "... test_new_api_perf"
	@echo "... unified_test"
	@echo "... uvrpc"
	@echo "... benchmark/benchmark_client.o"
	@echo "... benchmark/benchmark_client.i"
	@echo "... benchmark/benchmark_client.s"
	@echo "... benchmark/benchmark_server.o"
	@echo "... benchmark/benchmark_server.i"
	@echo "... benchmark/benchmark_server.s"
	@echo "... benchmark/gen_benchmark.o"
	@echo "... benchmark/gen_benchmark.i"
	@echo "... benchmark/gen_benchmark.s"
	@echo "... benchmark/perf_test.o"
	@echo "... benchmark/perf_test.i"
	@echo "... benchmark/perf_test.s"
	@echo "... benchmark/unified_test.o"
	@echo "... benchmark/unified_test.i"
	@echo "... benchmark/unified_test.s"
	@echo "... deps/msgpack-c/src/mpack/mpack-common.o"
	@echo "... deps/msgpack-c/src/mpack/mpack-common.i"
	@echo "... deps/msgpack-c/src/mpack/mpack-common.s"
	@echo "... deps/msgpack-c/src/mpack/mpack-expect.o"
	@echo "... deps/msgpack-c/src/mpack/mpack-expect.i"
	@echo "... deps/msgpack-c/src/mpack/mpack-expect.s"
	@echo "... deps/msgpack-c/src/mpack/mpack-node.o"
	@echo "... deps/msgpack-c/src/mpack/mpack-node.i"
	@echo "... deps/msgpack-c/src/mpack/mpack-node.s"
	@echo "... deps/msgpack-c/src/mpack/mpack-platform.o"
	@echo "... deps/msgpack-c/src/mpack/mpack-platform.i"
	@echo "... deps/msgpack-c/src/mpack/mpack-platform.s"
	@echo "... deps/msgpack-c/src/mpack/mpack-reader.o"
	@echo "... deps/msgpack-c/src/mpack/mpack-reader.i"
	@echo "... deps/msgpack-c/src/mpack/mpack-reader.s"
	@echo "... deps/msgpack-c/src/mpack/mpack-writer.o"
	@echo "... deps/msgpack-c/src/mpack/mpack-writer.i"
	@echo "... deps/msgpack-c/src/mpack/mpack-writer.s"
	@echo "... examples/echo_server.o"
	@echo "... examples/echo_server.i"
	@echo "... examples/echo_server.s"
	@echo "... generated/echoservice_async_client_example.o"
	@echo "... generated/echoservice_async_client_example.i"
	@echo "... generated/echoservice_async_client_example.s"
	@echo "... generated/echoservice_gen.o"
	@echo "... generated/echoservice_gen.i"
	@echo "... generated/echoservice_gen.s"
	@echo "... generated/echoservice_gen_client.o"
	@echo "... generated/echoservice_gen_client.i"
	@echo "... generated/echoservice_gen_client.s"
	@echo "... generated/echoservice_server_example.o"
	@echo "... generated/echoservice_server_example.i"
	@echo "... generated/echoservice_server_example.s"
	@echo "... src/msgpack_wrapper.o"
	@echo "... src/msgpack_wrapper.i"
	@echo "... src/msgpack_wrapper.s"
	@echo "... src/uvrpc_config.o"
	@echo "... src/uvrpc_config.i"
	@echo "... src/uvrpc_config.s"
	@echo "... src/uvrpc_new.o"
	@echo "... src/uvrpc_new.i"
	@echo "... src/uvrpc_new.s"
	@echo "... src/uvrpc_utils.o"
	@echo "... src/uvrpc_utils.i"
	@echo "... src/uvrpc_utils.s"
	@echo "... src/uvzmq_impl.o"
	@echo "... src/uvzmq_impl.i"
	@echo "... src/uvzmq_impl.s"
	@echo "... tests/test_generated_client.o"
	@echo "... tests/test_generated_client.i"
	@echo "... tests/test_generated_client.s"
	@echo "... tests/test_generated_code_perf.o"
	@echo "... tests/test_generated_code_perf.i"
	@echo "... tests/test_generated_code_perf.s"
	@echo "... tests/test_new_api_perf.o"
	@echo "... tests/test_new_api_perf.i"
	@echo "... tests/test_new_api_perf.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

