#ifndef STREAM_SERVICE_READER_H
#define STREAM_SERVICE_READER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif


typedef const struct uvrpc_stream_StreamRequest_table *uvrpc_stream_StreamRequest_table_t;
typedef struct uvrpc_stream_StreamRequest_table *uvrpc_stream_StreamRequest_mutable_table_t;
typedef const flatbuffers_uoffset_t *uvrpc_stream_StreamRequest_vec_t;
typedef flatbuffers_uoffset_t *uvrpc_stream_StreamRequest_mutable_vec_t;
typedef const struct uvrpc_stream_StreamChunk_table *uvrpc_stream_StreamChunk_table_t;
typedef struct uvrpc_stream_StreamChunk_table *uvrpc_stream_StreamChunk_mutable_table_t;
typedef const flatbuffers_uoffset_t *uvrpc_stream_StreamChunk_vec_t;
typedef flatbuffers_uoffset_t *uvrpc_stream_StreamChunk_mutable_vec_t;
typedef const struct uvrpc_stream_StreamResponse_table *uvrpc_stream_StreamResponse_table_t;
typedef struct uvrpc_stream_StreamResponse_table *uvrpc_stream_StreamResponse_mutable_table_t;
typedef const flatbuffers_uoffset_t *uvrpc_stream_StreamResponse_vec_t;
typedef flatbuffers_uoffset_t *uvrpc_stream_StreamResponse_mutable_vec_t;
#ifndef uvrpc_stream_StreamRequest_file_identifier
#define uvrpc_stream_StreamRequest_file_identifier 0
#endif
/* deprecated, use uvrpc_stream_StreamRequest_file_identifier */
#ifndef uvrpc_stream_StreamRequest_identifier
#define uvrpc_stream_StreamRequest_identifier 0
#endif
#define uvrpc_stream_StreamRequest_type_hash ((flatbuffers_thash_t)0x116f15bd)
#define uvrpc_stream_StreamRequest_type_identifier "\xbd\x15\x6f\x11"
#ifndef uvrpc_stream_StreamRequest_file_extension
#define uvrpc_stream_StreamRequest_file_extension "bin"
#endif
#ifndef uvrpc_stream_StreamChunk_file_identifier
#define uvrpc_stream_StreamChunk_file_identifier 0
#endif
/* deprecated, use uvrpc_stream_StreamChunk_file_identifier */
#ifndef uvrpc_stream_StreamChunk_identifier
#define uvrpc_stream_StreamChunk_identifier 0
#endif
#define uvrpc_stream_StreamChunk_type_hash ((flatbuffers_thash_t)0xf4c616e9)
#define uvrpc_stream_StreamChunk_type_identifier "\xe9\x16\xc6\xf4"
#ifndef uvrpc_stream_StreamChunk_file_extension
#define uvrpc_stream_StreamChunk_file_extension "bin"
#endif
#ifndef uvrpc_stream_StreamResponse_file_identifier
#define uvrpc_stream_StreamResponse_file_identifier 0
#endif
/* deprecated, use uvrpc_stream_StreamResponse_file_identifier */
#ifndef uvrpc_stream_StreamResponse_identifier
#define uvrpc_stream_StreamResponse_identifier 0
#endif
#define uvrpc_stream_StreamResponse_type_hash ((flatbuffers_thash_t)0xb1a7bce3)
#define uvrpc_stream_StreamResponse_type_identifier "\xe3\xbc\xa7\xb1"
#ifndef uvrpc_stream_StreamResponse_file_extension
#define uvrpc_stream_StreamResponse_file_extension "bin"
#endif



struct uvrpc_stream_StreamRequest_table { uint8_t unused__; };

static inline size_t uvrpc_stream_StreamRequest_vec_len(uvrpc_stream_StreamRequest_vec_t vec)
__flatbuffers_vec_len(vec)
static inline uvrpc_stream_StreamRequest_table_t uvrpc_stream_StreamRequest_vec_at(uvrpc_stream_StreamRequest_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(uvrpc_stream_StreamRequest_table_t, vec, i, 0)
__flatbuffers_table_as_root(uvrpc_stream_StreamRequest)

__flatbuffers_define_scalar_field(0, uvrpc_stream_StreamRequest, chunk_count, flatbuffers_int32, int32_t, INT32_C(5))
__flatbuffers_define_scalar_field(1, uvrpc_stream_StreamRequest, chunk_size, flatbuffers_int32, int32_t, INT32_C(1024))
__flatbuffers_define_scalar_field(2, uvrpc_stream_StreamRequest, delay_ms, flatbuffers_int32, int32_t, INT32_C(0))

struct uvrpc_stream_StreamChunk_table { uint8_t unused__; };

static inline size_t uvrpc_stream_StreamChunk_vec_len(uvrpc_stream_StreamChunk_vec_t vec)
__flatbuffers_vec_len(vec)
static inline uvrpc_stream_StreamChunk_table_t uvrpc_stream_StreamChunk_vec_at(uvrpc_stream_StreamChunk_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(uvrpc_stream_StreamChunk_table_t, vec, i, 0)
__flatbuffers_table_as_root(uvrpc_stream_StreamChunk)

__flatbuffers_define_scalar_field(0, uvrpc_stream_StreamChunk, chunk_id, flatbuffers_int32, int32_t, INT32_C(0))
__flatbuffers_define_scalar_field(1, uvrpc_stream_StreamChunk, total_chunks, flatbuffers_int32, int32_t, INT32_C(0))
__flatbuffers_define_vector_field(2, uvrpc_stream_StreamChunk, data, flatbuffers_uint8_vec_t, 0)
__flatbuffers_define_scalar_field(3, uvrpc_stream_StreamChunk, is_last, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))

struct uvrpc_stream_StreamResponse_table { uint8_t unused__; };

static inline size_t uvrpc_stream_StreamResponse_vec_len(uvrpc_stream_StreamResponse_vec_t vec)
__flatbuffers_vec_len(vec)
static inline uvrpc_stream_StreamResponse_table_t uvrpc_stream_StreamResponse_vec_at(uvrpc_stream_StreamResponse_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(uvrpc_stream_StreamResponse_table_t, vec, i, 0)
__flatbuffers_table_as_root(uvrpc_stream_StreamResponse)

__flatbuffers_define_scalar_field(0, uvrpc_stream_StreamResponse, status, flatbuffers_int32, int32_t, INT32_C(0))
__flatbuffers_define_string_field(1, uvrpc_stream_StreamResponse, message, 0)


#include "flatcc/flatcc_epilogue.h"
#endif /* STREAM_SERVICE_READER_H */
