#ifndef STREAM_SERVICE_BUILDER_H
#define STREAM_SERVICE_BUILDER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef STREAM_SERVICE_READER_H
#include "stream_service_reader.h"
#endif
#ifndef FLATBUFFERS_COMMON_BUILDER_H
#include "flatbuffers_common_builder.h"
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif

static const flatbuffers_voffset_t __uvrpc_stream_StreamRequest_required[] = { 0 };
typedef flatbuffers_ref_t uvrpc_stream_StreamRequest_ref_t;
static uvrpc_stream_StreamRequest_ref_t uvrpc_stream_StreamRequest_clone(flatbuffers_builder_t *B, uvrpc_stream_StreamRequest_table_t t);
__flatbuffers_build_table(flatbuffers_, uvrpc_stream_StreamRequest, 3)

static const flatbuffers_voffset_t __uvrpc_stream_StreamChunk_required[] = { 0 };
typedef flatbuffers_ref_t uvrpc_stream_StreamChunk_ref_t;
static uvrpc_stream_StreamChunk_ref_t uvrpc_stream_StreamChunk_clone(flatbuffers_builder_t *B, uvrpc_stream_StreamChunk_table_t t);
__flatbuffers_build_table(flatbuffers_, uvrpc_stream_StreamChunk, 4)

static const flatbuffers_voffset_t __uvrpc_stream_StreamResponse_required[] = { 0 };
typedef flatbuffers_ref_t uvrpc_stream_StreamResponse_ref_t;
static uvrpc_stream_StreamResponse_ref_t uvrpc_stream_StreamResponse_clone(flatbuffers_builder_t *B, uvrpc_stream_StreamResponse_table_t t);
__flatbuffers_build_table(flatbuffers_, uvrpc_stream_StreamResponse, 2)

#define __uvrpc_stream_StreamRequest_formal_args , int32_t v0, int32_t v1, int32_t v2
#define __uvrpc_stream_StreamRequest_call_args , v0, v1, v2
static inline uvrpc_stream_StreamRequest_ref_t uvrpc_stream_StreamRequest_create(flatbuffers_builder_t *B __uvrpc_stream_StreamRequest_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, uvrpc_stream_StreamRequest, uvrpc_stream_StreamRequest_file_identifier, uvrpc_stream_StreamRequest_type_identifier)

#define __uvrpc_stream_StreamChunk_formal_args , int32_t v0, int32_t v1, flatbuffers_uint8_vec_ref_t v2, flatbuffers_bool_t v3
#define __uvrpc_stream_StreamChunk_call_args , v0, v1, v2, v3
static inline uvrpc_stream_StreamChunk_ref_t uvrpc_stream_StreamChunk_create(flatbuffers_builder_t *B __uvrpc_stream_StreamChunk_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, uvrpc_stream_StreamChunk, uvrpc_stream_StreamChunk_file_identifier, uvrpc_stream_StreamChunk_type_identifier)

#define __uvrpc_stream_StreamResponse_formal_args , int32_t v0, flatbuffers_string_ref_t v1
#define __uvrpc_stream_StreamResponse_call_args , v0, v1
static inline uvrpc_stream_StreamResponse_ref_t uvrpc_stream_StreamResponse_create(flatbuffers_builder_t *B __uvrpc_stream_StreamResponse_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, uvrpc_stream_StreamResponse, uvrpc_stream_StreamResponse_file_identifier, uvrpc_stream_StreamResponse_type_identifier)

__flatbuffers_build_scalar_field(0, flatbuffers_, uvrpc_stream_StreamRequest_chunk_count, flatbuffers_int32, int32_t, 4, 4, INT32_C(5), uvrpc_stream_StreamRequest)
__flatbuffers_build_scalar_field(1, flatbuffers_, uvrpc_stream_StreamRequest_chunk_size, flatbuffers_int32, int32_t, 4, 4, INT32_C(1024), uvrpc_stream_StreamRequest)
__flatbuffers_build_scalar_field(2, flatbuffers_, uvrpc_stream_StreamRequest_delay_ms, flatbuffers_int32, int32_t, 4, 4, INT32_C(0), uvrpc_stream_StreamRequest)

static inline uvrpc_stream_StreamRequest_ref_t uvrpc_stream_StreamRequest_create(flatbuffers_builder_t *B __uvrpc_stream_StreamRequest_formal_args)
{
    if (uvrpc_stream_StreamRequest_start(B)
        || uvrpc_stream_StreamRequest_chunk_count_add(B, v0)
        || uvrpc_stream_StreamRequest_chunk_size_add(B, v1)
        || uvrpc_stream_StreamRequest_delay_ms_add(B, v2)) {
        return 0;
    }
    return uvrpc_stream_StreamRequest_end(B);
}

static uvrpc_stream_StreamRequest_ref_t uvrpc_stream_StreamRequest_clone(flatbuffers_builder_t *B, uvrpc_stream_StreamRequest_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (uvrpc_stream_StreamRequest_start(B)
        || uvrpc_stream_StreamRequest_chunk_count_pick(B, t)
        || uvrpc_stream_StreamRequest_chunk_size_pick(B, t)
        || uvrpc_stream_StreamRequest_delay_ms_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, uvrpc_stream_StreamRequest_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, uvrpc_stream_StreamChunk_chunk_id, flatbuffers_int32, int32_t, 4, 4, INT32_C(0), uvrpc_stream_StreamChunk)
__flatbuffers_build_scalar_field(1, flatbuffers_, uvrpc_stream_StreamChunk_total_chunks, flatbuffers_int32, int32_t, 4, 4, INT32_C(0), uvrpc_stream_StreamChunk)
__flatbuffers_build_vector_field(2, flatbuffers_, uvrpc_stream_StreamChunk_data, flatbuffers_uint8, uint8_t, uvrpc_stream_StreamChunk)
__flatbuffers_build_scalar_field(3, flatbuffers_, uvrpc_stream_StreamChunk_is_last, flatbuffers_bool, flatbuffers_bool_t, 1, 1, UINT8_C(0), uvrpc_stream_StreamChunk)

static inline uvrpc_stream_StreamChunk_ref_t uvrpc_stream_StreamChunk_create(flatbuffers_builder_t *B __uvrpc_stream_StreamChunk_formal_args)
{
    if (uvrpc_stream_StreamChunk_start(B)
        || uvrpc_stream_StreamChunk_chunk_id_add(B, v0)
        || uvrpc_stream_StreamChunk_total_chunks_add(B, v1)
        || uvrpc_stream_StreamChunk_data_add(B, v2)
        || uvrpc_stream_StreamChunk_is_last_add(B, v3)) {
        return 0;
    }
    return uvrpc_stream_StreamChunk_end(B);
}

static uvrpc_stream_StreamChunk_ref_t uvrpc_stream_StreamChunk_clone(flatbuffers_builder_t *B, uvrpc_stream_StreamChunk_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (uvrpc_stream_StreamChunk_start(B)
        || uvrpc_stream_StreamChunk_chunk_id_pick(B, t)
        || uvrpc_stream_StreamChunk_total_chunks_pick(B, t)
        || uvrpc_stream_StreamChunk_data_pick(B, t)
        || uvrpc_stream_StreamChunk_is_last_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, uvrpc_stream_StreamChunk_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, uvrpc_stream_StreamResponse_status, flatbuffers_int32, int32_t, 4, 4, INT32_C(0), uvrpc_stream_StreamResponse)
__flatbuffers_build_string_field(1, flatbuffers_, uvrpc_stream_StreamResponse_message, uvrpc_stream_StreamResponse)

static inline uvrpc_stream_StreamResponse_ref_t uvrpc_stream_StreamResponse_create(flatbuffers_builder_t *B __uvrpc_stream_StreamResponse_formal_args)
{
    if (uvrpc_stream_StreamResponse_start(B)
        || uvrpc_stream_StreamResponse_status_add(B, v0)
        || uvrpc_stream_StreamResponse_message_add(B, v1)) {
        return 0;
    }
    return uvrpc_stream_StreamResponse_end(B);
}

static uvrpc_stream_StreamResponse_ref_t uvrpc_stream_StreamResponse_clone(flatbuffers_builder_t *B, uvrpc_stream_StreamResponse_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (uvrpc_stream_StreamResponse_start(B)
        || uvrpc_stream_StreamResponse_status_pick(B, t)
        || uvrpc_stream_StreamResponse_message_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, uvrpc_stream_StreamResponse_end(B));
}

#include "flatcc/flatcc_epilogue.h"
#endif /* STREAM_SERVICE_BUILDER_H */
